Repository rdkit/rdkit, pull requests merged in 2018-10, with the labels that each got.

#2073 move rdInfoLog to stderr
  Code/RDGeneral/RDLog.cpp
Labels: enhancement

#2070 Add user-defined literals for parsing SMILES and SMARTS
  Code/GraphMol/SmilesParse/SmilesParse.h
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: enhancement

#2084 Expose a CMake flag to build RDKit with -rpath
  CMakeLists.txt
  External/catch/CMakeLists.txt
Labels: enhancement

#2095 Updated .gitignore with files generated outside of build directory.
  .gitignore
Labels: enhancement

#2014 PgSQL: add support for PostgreSQL_CONFIG cmake var
  Code/PgSQL/rdkit/CMakeLists.txt
Labels: enhancement

#2005 GSoC 2018 - Fingerprints
  Code/GraphMol/Fingerprints/AtomPairGenerator.cpp
  Code/GraphMol/Fingerprints/AtomPairGenerator.h
  Code/GraphMol/Fingerprints/AtomPairs.cpp
  Code/GraphMol/Fingerprints/AtomPairs.h
  Code/GraphMol/Fingerprints/CMakeLists.txt
  Code/GraphMol/Fingerprints/FingerprintGenerator.cpp
  Code/GraphMol/Fingerprints/FingerprintGenerator.h
  Code/GraphMol/Fingerprints/FingerprintUtil.cpp
  Code/GraphMol/Fingerprints/FingerprintUtil.h
  Code/GraphMol/Fingerprints/Fingerprints.cpp
  Code/GraphMol/Fingerprints/MorganFingerprints.cpp
  Code/GraphMol/Fingerprints/MorganFingerprints.h
  Code/GraphMol/Fingerprints/MorganGenerator.cpp
  Code/GraphMol/Fingerprints/MorganGenerator.h
  Code/GraphMol/Fingerprints/RDKitFPGenerator.cpp
  Code/GraphMol/Fingerprints/RDKitFPGenerator.h
  Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.cpp
  Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.h
  Code/GraphMol/Fingerprints/Wrap/AtomPairWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/CMakeLists.txt
  Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/MorganWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/RDKitFPWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/TopologicalTorsionWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/testGenerators.py
  Code/GraphMol/Fingerprints/Wrap/test_list.py
  Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp
  Code/JavaWrappers/Fingerprints.i
  Docs/Notebooks/FingerprintGenerators.ipynb
Labels: enhancement

#2103 Update Docs For CalcBEDROC
  rdkit/ML/Scoring/Scoring.py
Labels: documentation, enhancement

#2102 Coordgen: stop printing Templates location
  External/CoordGen/CoordGen.h
Labels: enhancement

#2097 Address compile warnings & trivial improvements
  Code/DataStructs/testDatastructs.cpp
  Code/ForceField/MMFF/Params.cpp
  Code/Geometry/testTransforms.cpp
  Code/GraphMol/ChemReactions/Enumerate/EvenSamplePairs.cpp
  Code/GraphMol/ChemReactions/Enumerate/testEnumerate.cpp
  Code/GraphMol/Depictor/RDDepictor.cpp
  Code/GraphMol/Descriptors/AUTOCORR2D.cpp
  Code/GraphMol/Descriptors/AUTOCORR3D.cpp
  Code/GraphMol/Descriptors/Crippen.cpp
  Code/GraphMol/Descriptors/EEM.cpp
  Code/GraphMol/Descriptors/GETAWAY.cpp
  Code/GraphMol/Descriptors/GETAWAY.h
  Code/GraphMol/Descriptors/MORSE.cpp
  Code/GraphMol/Descriptors/PBF.cpp
  Code/GraphMol/Descriptors/RDF.cpp
  Code/GraphMol/Descriptors/WHIM.cpp
  Code/GraphMol/Descriptors/test.cpp
  Code/GraphMol/Descriptors/testAUTOCORR2D.cpp
  Code/GraphMol/Descriptors/testAUTOCORR3D.cpp
  Code/GraphMol/Descriptors/testEEM.cpp
  Code/GraphMol/Descriptors/testGETAWAY.cpp
  Code/GraphMol/Descriptors/testMORSE.cpp
  Code/GraphMol/Descriptors/testPBF.cpp
  Code/GraphMol/Descriptors/testRDF.cpp
  Code/GraphMol/Descriptors/testRDFcustom.cpp
  Code/GraphMol/Descriptors/testWHIM.cpp
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/PDBWriter.cpp
  Code/GraphMol/FileParsers/ProximityBonds.h
  Code/GraphMol/FileParsers/TDTWriter.cpp
  Code/GraphMol/Fingerprints/test1.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolInterchange/Parser.cpp
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/Normalize.cpp
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/MolStandardize/Validate.cpp
  Code/GraphMol/MolStandardize/testNormalize.cpp
  Code/GraphMol/MolStandardize/testTautomer.cpp
  Code/GraphMol/QueryOps.h
  Code/GraphMol/SmilesParse/test.cpp
  Code/GraphMol/StructChecker/ReCharge.cpp
  Code/GraphMol/StructChecker/Stereo.cpp
  Code/GraphMol/StructChecker/StructCheckerOptions.cpp
  Code/GraphMol/StructChecker/Tautomer.cpp
  Code/GraphMol/StructChecker/testStructChecker.cpp
  Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp
  Code/GraphMol/Wrap/EditableMol.cpp
  Code/GraphMol/testCanon.cpp
  Code/RDBoost/python_streambuf.h
  Code/SimDivPickers/testPickers.cpp
  Contrib/PBF/PBFRDKit.cpp
Labels: enhancement

#2122 overview.md updates
  Docs/Book/Overview.md
Labels: documentation

#2124 Docs/autodoc update
  Code/GraphMol/MolStandardize/Wrap/Fragment.cpp
  Code/GraphMol/MolStandardize/Wrap/Metal.cpp
  Code/GraphMol/MolStandardize/Wrap/Normalize.cpp
  Code/GraphMol/MolStandardize/Wrap/Validate.cpp
  Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
  Docs/Book/BackwardsIncompatibleChanges.md
  Docs/Book/Makefile
  Docs/Book/source/rdkit.Chem.Draw.rdMolDraw2D.rst
  Docs/Book/source/rdkit.Chem.Draw.rst
  Docs/Book/source/rdkit.Chem.MolStandardize.rdMolStandardize.rst
  Docs/Book/source/rdkit.Chem.MolStandardize.rst
  Docs/Book/source/rdkit.Chem.rdFingerprintGenerator.rst
  Docs/Book/source/rdkit.Chem.rst
  rdkit/Chem/MolStandardize/__init__.py
Labels: documentation

#2129 PgSQL: fix boolean definitions for Postgresql 11
  Code/PgSQL/rdkit/bfp_gin.c
  Code/PgSQL/rdkit/bfp_gist.c
  Code/PgSQL/rdkit/low_gist.c
  Code/PgSQL/rdkit/rdkit_gist.c
Labels: bug

#2130 update fingerprint tutorial notebook
  Docs/Notebooks/FingerprintGenerators.ipynb
Labels: bug, documentation

#2137 Fix typo in RecapHierarchyNode destructor
  rdkit/Chem/Recap.py
Labels: bug
