Repository rdkit/rdkit, pull requests merged in 2018-11, with the labels that each got.

#2134 Stop building against python2 in travis
  .travis.yml
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/Install.md
  Docs/Book/Overview.md
  README.md
  ReleaseNotes.md
Labels: deprecation

#2156 ShapeTverskyIndex python function
  Code/GraphMol/ShapeHelpers/Wrap/rdShapeHelpers.cpp
  Code/GraphMol/ShapeHelpers/Wrap/testShapeHelpers.py
Labels: enhancement

#2162 Added stk into the "Projects using RDKit" section of the README.
  Docs/Book/Overview.md
  README.md
Labels: documentation

#2157 there was an error in the install doc
  Docs/Book/Install.md
Labels: documentation
