Repository rdkit/rdkit, pull requests merged in 2018-04, with the labels that each got.

#1785 speedup the NumBitsInCommon operation
  Code/DataStructs/BitOps.cpp
  Code/RDGeneral/StreamOps.h
  Code/SimDivPickers/MaxMinPicker.h
Labels: enhancement

#1802 update docs for release for release
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/Install.md
  Docs/Book/Overview.md
  Docs/Book/RDKit_Book.rst
  ReleaseNotes.md
Labels: documentation

#1798 Support for a JSON-based molecule interchange format
  CMakeLists.txt
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/MolInterchange/CMakeLists.txt
  Code/GraphMol/MolInterchange/MolInterchange.h
  Code/GraphMol/MolInterchange/Parser.cpp
  Code/GraphMol/MolInterchange/Wrap/CMakeLists.txt
  Code/GraphMol/MolInterchange/Wrap/rdMolInterchange.cpp
  Code/GraphMol/MolInterchange/Wrap/testMolInterchange.py
  Code/GraphMol/MolInterchange/Writer.cpp
  Code/GraphMol/MolInterchange/details.h
  Code/GraphMol/MolInterchange/test1.cpp
  Code/GraphMol/MolInterchange/test_data/1000mols.json
  Code/GraphMol/MolInterchange/test_data/test1.json
  Code/GraphMol/MolInterchange/test_data/test2.json
  Code/GraphMol/MolInterchange/test_data/test3.json
  Code/GraphMol/PartialCharges/GasteigerCharges.cpp
  Code/GraphMol/Wrap/RingInfo.cpp
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
  rdkit/Chem/UnitTestChem.py
  rdkit/Chem/__init__.py
Labels: enhancement

#1808 Fix python linkage
  CMakeLists.txt
  Code/RDBoost/CMakeLists.txt
  Code/cmake/Modules/RDKitUtils.cmake
Labels: bug

#1813 Ifg contribution
  Contrib/IFG/README
  Contrib/IFG/ifg.py
Labels: contrib

#1814 Various small tweaks
  CMakeLists.txt
  Code/GraphMol/ChemReactions/Enumerate/EnumerationStrategyBase.h
  appveyor.yml
Labels: enhancement

#1822 Adds build matrix, make c++11 default in cmake
  .travis.yml
  CMakeLists.txt
Labels: enhancement

#1832 allow libs to not be installed
  CMakeLists.txt
  Code/cmake/Modules/RDKitUtils.cmake
Labels: bug
