Repository rdkit/rdkit, pull requests merged in 2018-06, with the labels that each got.

#1655 added Scripts/create_deb_packages.sh
  Scripts/create_deb_packages.sh
Labels: enhancement

#1897 expose MolDraw2DSVG.tagAtoms() to python
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
Labels: enhancement

#1874 Add an auto-populated file with cmake config options
  CMakeLists.txt
  Code/GraphMol/Depictor/RDDepictor.cpp
  Code/GraphMol/Depictor/RDDepictor.h
  Code/GraphMol/Depictor/Wrap/rdDepictor.cpp
  Code/GraphMol/Depictor/testDepictor.cpp
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/rxn_test1.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/PgSQL/rdkit/adapter.cpp
  Code/RDGeneral/CMakeLists.txt
  Code/RDGeneral/RDConfig.h.cmake
  Docs/Book/C++Examples/example13.cpp
  External/AvalonTools/CMakeLists.txt
  External/INCHI-API/CMakeLists.txt
  ReleaseNotes.md
Labels: enhancement

#1898 allow the cleanup step of Mol2 parsing to be disabled
  Code/GraphMol/FileParsers/FileParsers.h
  Code/GraphMol/FileParsers/Mol2FileParser.cpp
  Code/GraphMol/FileParsers/testMol2ToMol.cpp
  Code/GraphMol/FileParsers/test_data/3505.mol2
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/JavaWrappers/RWMol.i
Labels: enhancement

#1885 Add a script for calculating chiral descriptors to Contrib
  Contrib/ChiralPairs/ChiralDescriptors.py
  Contrib/ChiralPairs/README.txt
Labels: contrib

#1902 Allow Atom.GetAtomSmarts() to return isomeric SMILES
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/GraphMol/Wrap/Atom.cpp
  Code/GraphMol/Wrap/rough_test.py
  ReleaseNotes.md
Labels: changes results, enhancement

#1884 Custom property VSA
  Code/GraphMol/Descriptors/MolSurf.cpp
  Code/GraphMol/Descriptors/MolSurf.h
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
Labels: enhancement

#1935 Addresses several minor warning messages during the build
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/ChemTransforms/MolFragmenter.cpp
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/FilterCatalog/FunctionalGroupHierarchy.cpp
  Code/GraphMol/FilterCatalog/update_pains.py
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/GraphMol/StructChecker/ReCharge.cpp
  Code/GraphMol/StructChecker/Tautomer.cpp
  Code/GraphMol/molopstest.cpp
  Code/GraphMol/testPicklerGlobalSettings.cpp
  Code/SimDivPickers/testPickers.cpp
Labels: enhancement
