Repository rdkit/rdkit, pull requests merged in 2018-09, with the labels that each got.

#1732 Start to use Catch2 for new tests
  CMakeLists.txt
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/SmilesParse/CMakeLists.txt
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/catch_tests.cpp
  Code/cmake/Modules/RDKitUtils.cmake
  External/catch/CMakeLists.txt
Labels: enhancement

#2016 Add missing boost header for v1.64
  Code/GraphMol/Substruct/SubstructMatch.cpp
Labels: enhancement

#2008 port fingerprint bit rendering code from CheTo
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/images/mfp2_bit872.svg
  Docs/Book/images/rdk_bit1553.svg
  Docs/Book/images/rdk_bit1553_2.svg
  rdkit/Chem/Draw/UnitTestDraw.py
  rdkit/Chem/Draw/__init__.py
Labels: enhancement

#2030 Allow dumping interchange information into SVG files
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/FileParsers.h
  Code/GraphMol/FileParsers/SVGParser.cpp
  Code/GraphMol/FileParsers/catch_tests.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/GraphMol/ROMol.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: enhancement

#2044 patch a memory allocation problem in the maeparser v1.0.0
  External/CoordGen/CMakeLists.txt
Labels: bug

#2048 switch to v1.0.1 of the maeparser
  External/CoordGen/CMakeLists.txt
Labels: bug

#2051 Update fastcluster code
  Contrib/Fastcluster/README.md
  Contrib/Fastcluster/centroid.tsv
  Contrib/Fastcluster/clustered.tsv
  Contrib/Fastcluster/clustered_parse.tsv
  Contrib/Fastcluster/fastcluster.py
  Contrib/Fastcluster/fp.tsv
Labels: bug, contrib

#1975 roc calculation naming problem
  rdkit/ML/Scoring/Scoring.py
Labels: enhancement

#2064 add scoring test (relevant to #1975)
  rdkit/ML/test_list.py
Labels: enhancement

#2067 actually run the SmilesWriterNoNames() test
  Code/GraphMol/FileParsers/testMolWriter.cpp
Labels: enhancement

#2061 Fix memory leak in Dict operator=
  Code/GraphMol/test-valgrind.cpp
  Code/RDGeneral/Dict.h
Labels: bug
