Repository rdkit/rdkit, pull requests merged in 2019-04, with the labels that each got.

#2384 Add ExplicitBitVect prop and query
  Code/GraphMol/QueryOps.h
  Code/GraphMol/Wrap/Atom.cpp
  Code/GraphMol/Wrap/Queries.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#2385 Allow components of the MolStandardize code to be initialized from streams
  Code/GraphMol/MolOps.h
  Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogParams.cpp
  Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogParams.h
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/Charge.h
  Code/GraphMol/MolStandardize/Fragment.cpp
  Code/GraphMol/MolStandardize/Fragment.h
  Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogParams.cpp
  Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogParams.h
  Code/GraphMol/MolStandardize/MolStandardize.cpp
  Code/GraphMol/MolStandardize/Normalize.cpp
  Code/GraphMol/MolStandardize/Normalize.h
  Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogParams.cpp
  Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogParams.h
  Code/GraphMol/MolStandardize/Wrap/Charge.cpp
  Code/GraphMol/MolStandardize/Wrap/Fragment.cpp
  Code/GraphMol/MolStandardize/Wrap/Normalize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/testNormalize.cpp
  Data/MolStandardize/acid_base_pairs.txt
  Data/MolStandardize/normalizations.txt
Labels: enhancement

#2395 CXSMILES parsing chokes on HTML char codes
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/cxsmiles_test.cpp
Labels: bug

#2402 FreeSASA improvements
  External/FreeSASA/CMakeLists.txt
  External/FreeSASA/RDFreeSASA.cpp
  External/FreeSASA/RDFreeSASA.h
  External/FreeSASA/Wrap/rdFreeSASA.cpp
  External/FreeSASA/Wrap/testFreeSASA.py
  External/FreeSASA/testFreeSASA.cpp
Labels: enhancement

#2406 Trim whitespace from mol fragment SMARTS and check SMARTS presence
  Code/GraphMol/FragCatalog/FragCatalogUtils.cpp
  Code/GraphMol/FragCatalog/test1.cpp
  Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogUtils.cpp
  Code/GraphMol/MolStandardize/testFragment.cpp
Labels: enhancement

#2409 Enable Azure Pipelines builds for CI
  .azure-pipelines/linux_build.yml
  .azure-pipelines/mac_build.yml
  .azure-pipelines/vs_build.yml
  azure-pipelines.yml
Labels: enhancement

#2424 Improve installation guide [ci skip]
  Docs/Book/Install.md
Labels: documentation
