Repository rdkit/rdkit, pull requests merged in 2019-03, with the labels that each got.

#2295 Add serialization to SubstructLibrary
  Code/GraphMol/SubstructLibrary/CMakeLists.txt
  Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp
  Code/GraphMol/SubstructLibrary/SubstructLibrary.h
  Code/GraphMol/SubstructLibrary/SubstructLibrarySerialization.h
  Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
  Code/GraphMol/SubstructLibrary/Wrap/rough_test.py
  Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp
Labels: enhancement

#2297 support reading/writing atom props from SD files
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/FileParserUtils.h
  Code/GraphMol/FileParsers/ForwardSDMolSupplier.cpp
  Code/GraphMol/FileParsers/MolSupplier.h
  Code/GraphMol/FileParsers/testPropertyLists.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/Wrap/CMakeLists.txt
  Code/GraphMol/Wrap/ForwardSDMolSupplier.cpp
  Code/GraphMol/Wrap/SDMolSupplier.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/testPropertyLists.py
  rdkit/Chem/Descriptors.py
  rdkit/Chem/UnitTestDocTestsChem.py
Labels: enhancement

#2310 fix a problem with the random pickers test
  Code/SimDivPickers/Wrap/testPickers.py
Labels: bug

#2302 Update maeparser & coordgen libraries
  Code/GraphMol/FileParsers/MaeMolSupplier.cpp
  Code/GraphMol/FileParsers/MolSupplier.h
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/Wrap/MaeMolSupplier.cpp
  External/CoordGen/CMakeLists.txt
  External/CoordGen/test.cpp
Labels: enhancement

#2319 change bogus "3D" to "2D" in a test file
  Data/NCI/first_200.props.sdf
Labels: enhancement

#2290 Write enhanced stereo to cxsmiles
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: enhancement

#2326 simple docstring fix
  rdkit/Chem/AllChem.py
Labels: documentation, enhancement

#2305 Mem errors clean up
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/test1.cpp
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/SLNParse/SLNParse.cpp
  Code/GraphMol/SLNParse/SLNParse.h
  Code/GraphMol/SLNParse/SLNParseOps.h
  Code/GraphMol/SLNParse/sln.tab.cpp.cmake
  Code/GraphMol/SLNParse/sln.tab.hpp.cmake
  Code/GraphMol/SLNParse/sln.yy
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake
  Code/GraphMol/SmilesParse/smarts.yy
  Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake
  Code/GraphMol/SmilesParse/smiles.yy
  Code/GraphMol/catch_tests.cpp
  Code/GraphMol/testSGroup.cpp
  Code/Query/EqualityQuery.h
  Code/Query/Query.h
  Code/cmake/rdkit_valgrind.suppressions
Labels: enhancement

#2327 allow using system's catch2 for tests
  External/catch/CMakeLists.txt
Labels: enhancement

#2324 fixes an r-group symmetrization problem
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Labels: enhancement

#2318 Build warnings revisited
  Code/DataStructs/testDatastructs.cpp
  Code/GraphMol/ChemReactions/testReaction.cpp
  Code/GraphMol/ChemTransforms/testChemTransforms.cpp
  Code/GraphMol/Descriptors/test.cpp
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/FileParsers/MaeMolSupplier.cpp
  Code/GraphMol/FileParsers/TDTWriter.cpp
  Code/GraphMol/FileParsers/test1.cpp
  Code/GraphMol/FileParsers/testMol2ToMol.cpp
  Code/GraphMol/Fingerprints/FingerprintGenerator.cpp
  Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.cpp
  Code/GraphMol/Fingerprints/test1.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp
  Code/GraphMol/MolChemicalFeatures/testFeatures.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/GraphMol/MolStandardize/Validate.h
  Code/GraphMol/MolTransforms/test1.cpp
  Code/GraphMol/QueryOps.h
  Code/GraphMol/SLNParse/lex.yysln.cpp.cmake
  Code/GraphMol/SLNParse/sln.tab.cpp.cmake
  Code/GraphMol/SLNParse/sln.yy
  Code/GraphMol/SmilesParse/SmilesParse.h
  Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smarts.yy
  Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smiles.yy
  Code/GraphMol/StructChecker/StructCheckerOptions.cpp
  Code/GraphMol/Wrap/substructmethods.h
  Code/GraphMol/molopstest.cpp
  Code/GraphMol/test1.cpp
  Code/RDGeneral/testDict.cpp
  External/AvalonTools/AvalonTools.h
Labels: enhancement

#2328 fixes #908
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/catch_tests.cpp
Labels: bug

#2334 switch to using cmake to handle the C++ spec
  CMakeLists.txt
Labels: enhancement

#2337 Exposes substructlibrary to swig
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/SubstructLibrary.i
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/SubstructLibraryTests.java
Labels: enhancement

#2341 Dev/general csharp fixes
  Code/JavaWrappers/FilterCatalog.i
  Code/JavaWrappers/MolDraw2D.i
Labels: enhancement

#2340 change to make the SWIG builds work on windows
  Code/JavaWrappers/CMakeLists.txt
Labels: bug

#2345 Expose RGroupDecomposition to SWIG
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/RGroupDecomposition.i
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/RGroupDecompositionTests.java
  External/CoordGen/CMakeLists.txt
Labels: enhancement

#2350 update debian build script to python3
  Scripts/create_deb_packages.sh
Labels: enhancement

#2338 Add a skip_all_if_match option to the FragmentRemover
  Code/GraphMol/MolStandardize/CMakeLists.txt
  Code/GraphMol/MolStandardize/Fragment.cpp
  Code/GraphMol/MolStandardize/Fragment.h
  Code/GraphMol/MolStandardize/Wrap/Fragment.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/catch_tests.cpp
  Code/GraphMol/MolStandardize/testFragment.cpp
Labels: enhancement

#2343 Add a read-only Python wrapper for SGroups
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Abbreviations.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_AnyPol_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Component_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Copolymer_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Copolymer_alt_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Copolymer_blk_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Copolymer_ran_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Data_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Formulation_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Generic_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Link_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Mixture_02.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Mixture_False.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_Monomer_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_MultipleGroup_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_SRU_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_SRU_02.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_crosslink_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_grf_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_mer_01.mol
  Code/GraphMol/FileParsers/sgroup_test_data/Sgroups_modification_01.mol
  Code/GraphMol/Sgroup.h
  Code/GraphMol/Wrap/CMakeLists.txt
  Code/GraphMol/Wrap/Sgroup.cpp
  Code/GraphMol/Wrap/rdchem.cpp
  Code/GraphMol/Wrap/testSGroups.py
  Code/GraphMol/testSGroup.cpp
Labels: enhancement

#2354 add GetStereoIsomerCount() function to EnumerateStereoisomers
  rdkit/Chem/EnumerateStereoisomers.py
  rdkit/Chem/PropertyMol.py
  rdkit/Chem/UnitTestDocTestsChem.py
Labels: enhancement

#2355 Update coordgenlibs to v1.2.2
  External/CoordGen/CMakeLists.txt
Labels: enhancement

#2314 Adds gzstream stream, exposes to swig
  Code/CMakeLists.txt
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/MolSupplier.i
  Code/JavaWrappers/Streams.i
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/SuppliersTests.java
  Code/RDStreams/CMakeLists.txt
  Code/RDStreams/streams.cpp
  Code/RDStreams/streams.h
  appveyor.yml
Labels: enhancement

#2356 Small fixes to get DLLs to build on Windows
  Code/GraphMol/MolStandardize/testCharge.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SubstructLibrary/SubstructLibrary.h
  Code/RDGeneral/Dict.h
Labels: enhancement

#2185 Remove Unicode From AcidBasePair Name
  rdkit/Chem/MolStandardize/charge.py
Labels: bug

#2365 Update the type hint in types.h for _MolFileRLabel
  Code/RDGeneral/types.h
Labels: documentation

#2335 WIP: optional integration with YAeHMOP
  CMakeLists.txt
  External/CMakeLists.txt
  External/YAeHMOP/CMakeLists.txt
  External/YAeHMOP/EHTTools.cpp
  External/YAeHMOP/EHTTools.h
  External/YAeHMOP/Wrap/CMakeLists.txt
  External/YAeHMOP/Wrap/rdEHTTools.cpp
  External/YAeHMOP/Wrap/testEHTTools.py
  External/YAeHMOP/test1.cpp
  External/YAeHMOP/test_data/benzene.mol
  External/YAeHMOP/test_data/methanol.mol
  External/YAeHMOP/test_data/phenol.mol
Labels: enhancement

#2293 Allow custom type-handlers in the RDProps interface
  Code/DataStructs/CMakeLists.txt
  Code/DataStructs/DatastructsStreamOps.h
  Code/DataStructs/testDatastructs.cpp
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/MolPickler.h
  Code/GraphMol/testPickler.cpp
  Code/RDGeneral/RDValue-doublemagic.h
  Code/RDGeneral/RDValue-taggedunion.h
  Code/RDGeneral/StreamOps.h
  Code/RDGeneral/testDict.cpp
Labels: enhancement

#2374 improvements to the Uncharge functionality
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/Charge.h
  Code/GraphMol/MolStandardize/MolStandardize.cpp
  Code/GraphMol/MolStandardize/MolStandardize.h
  Code/GraphMol/MolStandardize/Wrap/Charge.cpp
  Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/catch_tests.cpp
  ReleaseNotes.md
Labels: enhancement

#2376 Allow C RNG to be initialized from Python
  Code/RDBoost/Wrap/RDBase.cpp
Labels: enhancement
