Repository rdkit/rdkit, pull requests merged in 2019-11, with the labels that each got.

#2756 Add doRandom to the header docs
  Code/GraphMol/SmilesParse/SmilesWrite.h
Labels: documentation, enhancement

#2751 Improvements to JS wrappers
  Code/MinimalLib/demo/demo.html
  Code/MinimalLib/docker/Dockerfile
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#2768 Salt stripper should consider bond matches as well as atom matches
  Code/GraphMol/MolStandardize/Fragment.cpp
  Code/GraphMol/MolStandardize/catch_tests.cpp
Labels: bug

#2767 Make the cartridge tests work with PostgreSQL 12
  Code/PgSQL/rdkit/expected/avalon.out
  Code/PgSQL/rdkit/expected/bfpgist-91.out
  Code/PgSQL/rdkit/expected/fps.out
  Code/PgSQL/rdkit/expected/props.out
  Code/PgSQL/rdkit/expected/rdkit-91.out
  Code/PgSQL/rdkit/expected/reaction.out
  Code/PgSQL/rdkit/expected/sfpgist.out
  Code/PgSQL/rdkit/expected/slfpgist.out
  Code/PgSQL/rdkit/sql/avalon.sql
  Code/PgSQL/rdkit/sql/bfpgist-91.sql
  Code/PgSQL/rdkit/sql/fps.sql
  Code/PgSQL/rdkit/sql/props.sql
  Code/PgSQL/rdkit/sql/rdkit-91.sql
  Code/PgSQL/rdkit/sql/reaction.sql
  Code/PgSQL/rdkit/sql/sfpgist.sql
  Code/PgSQL/rdkit/sql/slfpgist.sql
Labels: bug

#2794 Add OFFTK to open-source users
  Docs/Book/Overview.md
Labels: documentation

#2748 MatchFusedRings does not imply CompleteRingsOnly anymore
  Code/GraphMol/FMCS/FMCS.cpp
  Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
  Code/GraphMol/FMCS/Wrap/testFMCS.py
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
Labels: enhancement

#2796 Fix build without boost serialization library
  CMakeLists.txt
Labels: bug
