Repository rdkit/rdkit, pull requests merged in 2019-09, with the labels that each got.

#2638 emolecules link updated
  Docs/Book/Cartridge.md
Labels: documentation, enhancement

#2646 Fixes: Atoms in non-standard valences not being properly written to mol blocks
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/catch_tests.cpp
  Code/GraphMol/catch_tests.cpp
Labels: bug

#2652 Update maeparser to 1.2.1 and coorgen to 1.3.1
  External/CoordGen/CMakeLists.txt
Labels: enhancement

#2653 Get numpy include dir programmatically
  Docs/Book/Install.md
Labels: documentation, enhancement
