Repository rdkit/rdkit, pull requests merged in 2019-07, with the labels that each got.

#2523 add a script for benchmarking fingerprint screenout and substructure performance
  Regress/Scripts/fingerprint_screenout.py
Labels: enhancement

#2509 Python wrap enhanced stereo setters
  Code/GraphMol/StereoGroup.cpp
  Code/GraphMol/StereoGroup.h
  Code/GraphMol/Wrap/Mol.cpp
  Code/GraphMol/Wrap/StereoGroup.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/RDBoost/Wrap.h
Labels: enhancement

#2521 fix to SDWriter docs
  Code/GraphMol/Wrap/SDWriter.cpp
Labels: bug, documentation

#2498 Support XYZ format for output
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/FileParsers.h
  Code/GraphMol/FileParsers/XYZFileWriter.cpp
  Code/GraphMol/FileParsers/catch_tests.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/JavaWrappers/ROMol.i
Labels: enhancement

#2518 Fix/mmff threadsafety issues
  Code/ForceField/MMFF/Nonbonded.cpp
  Code/ForceField/MMFF/Nonbonded.h
  Code/ForceField/MMFF/Params.cpp
  Code/ForceField/MMFF/Params.h
  Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.h
  Code/GraphMol/ForceFieldHelpers/MMFF/Builder.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/CMakeLists.txt
  Code/GraphMol/ForceFieldHelpers/MMFF/testMultiThread.cpp
Labels: bug

#2542 Update maeparser and coordgen versions
  External/CoordGen/CMakeLists.txt
Labels: enhancement

#2541 Remove unused ctest: testCanon
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/testCanon.cpp
Labels: enhancement

#2534 Expose SDF loading options to LoadSDF
  ReleaseNotes.md
  rdkit/Chem/PandasTools.py
Labels: changes results, enhancement

#2528 make "R" in CTABs an AtomNull query
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/catch_tests.cpp
Labels: changes results, enhancement

#2517 - fixes ResonanceMolSupplier bug in perceiving conjugated groups
  Code/GraphMol/Resonance.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/resMolSupplierTest.cpp
Labels: bug

#2557 Code simplification for fingerprints to np array
  Docs/Book/Cookbook.md
Labels: documentation, enhancement

#2569 Do not run UnitTestMCS.py::TestTimeout in debug builds
  rdkit/CMakeLists.txt
  rdkit/Chem/Pharm2D/UnitTestMatcher.py
  rdkit/Chem/UnitTestFragmentDescriptors.py
  rdkit/Chem/UnitTestMCS.py
  rdkit/TestRunner.py
Labels: enhancement

#2551 Add RDKIT_FILEPARSERS_EXPORT to finishMolProcessing
  Code/GraphMol/FileParsers/FileParserUtils.h
Labels: bug

#2562 Enable SimilarityMaps in C++
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DQt.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.h
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/JavaWrappers/MolDraw2D.i
  Code/Numerics/CMakeLists.txt
  Code/Numerics/Conrec.h
  Code/Numerics/testConrec.cpp
  rdkit/Chem/Draw/SimilarityMaps.py
  rdkit/Chem/Draw/UnitTestSimilarityMaps.py
Labels: enhancement

#2558 Integrate Unique Ring Families from RingDecomposerLib
  CMakeLists.txt
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/FindRings.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/RingInfo.cpp
  Code/GraphMol/RingInfo.h
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/RingInfo.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/molopstest.cpp
  Code/JavaWrappers/CMakeLists.txt
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/RDGeneral/RDConfig.h.cmake
  External/CMakeLists.txt
  External/RingFamilies/CMakeLists.txt
  External/RingFamilies/URF.cpp
  External/RingFamilies/test.cpp
Labels: enhancement

#2572 Allow Point2D to be constructed from Point3D
  Code/Geometry/CMakeLists.txt
  Code/Geometry/Wrap/Point.cpp
  Code/Geometry/Wrap/testGeometry.py
  Code/Geometry/catch_tests.cpp
  Code/Geometry/point.h
Labels: enhancement

#2560 Allow providing a bounds matrix to EmbedMol
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
Labels: enhancement

#2578 Added te aromatic SMILES and ring closure extension example to RDKit_Book
  Docs/Book/RDKit_Book.rst
Labels: documentation
