Repository rdkit/rdkit, pull requests merged in 2020-09, with the labels that each got.

#3324 Updated code for chirality perception
  Code/GraphMol/CIPLabeler/catch_tests.cpp
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/Chirality.h
  Code/GraphMol/FindStereo.cpp
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/SmilesParse.h
  Code/GraphMol/Wrap/CMakeLists.txt
  Code/GraphMol/Wrap/Chirality.cpp
  Code/GraphMol/Wrap/ChiralityOps.cpp
  Code/GraphMol/Wrap/rdchem.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rdmolops.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/hanoitest.cpp
  Code/GraphMol/new_canon.cpp
  Code/GraphMol/new_canon.h
  Code/GraphMol/testChirality.cpp
  Docs/Book/RDKit_Book.rst
  Docs/Book/images/parastereo_1.png
  Docs/Book/images/parastereo_2.png
  Docs/Book/images/potential_stereo_double_bond1.png
  Docs/Book/images/potential_stereo_double_bond2.png
  Docs/Book/images/potential_stereo_double_bond3.png
  rdkit/Chem/EnumerateStereoisomers.py
  rdkit/Chem/UnitTestMol3D.py
  rdkit/Chem/__init__.py
Labels: enhancement

#3375 expose additional SubstanceGroup data members to Python
  Code/GraphMol/Wrap/SubstanceGroup.cpp
  Code/GraphMol/Wrap/testSGroups.py
Labels: enhancement

#3294 [WIP] Deprotection Library
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/Deprotect/CMakeLists.txt
  Code/GraphMol/Deprotect/Deprotect.cpp
  Code/GraphMol/Deprotect/Deprotect.h
  Code/GraphMol/Deprotect/Wrap/CMakeLists.txt
  Code/GraphMol/Deprotect/Wrap/DeprotectWrap.cpp
  Code/GraphMol/Deprotect/Wrap/rdDeprotect.cpp
  Code/GraphMol/Deprotect/Wrap/rdDeprotect.h
  Code/GraphMol/Deprotect/Wrap/rough_test.py
  Code/GraphMol/Deprotect/deprotectTest.cpp
Labels: enhancement

#3404 Recursive smarts cannot be used in the core for rgroup decomposition
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
Labels: bug

#3398 Fixes a couple of query-related bugs
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/test1.cpp
Labels: bug

#3411 Allow passing explicit removeHs, sanitize and strict flags to the MDL rxn parser
  Code/GraphMol/ChemReactions/MDLParser.cpp
  Code/GraphMol/ChemReactions/ReactionParser.h
  Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
  Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
  Code/GraphMol/ChemReactions/testReaction.cpp
Labels: enhancement

#3412 Improvements to reaction chirality handling
  Code/GraphMol/ChemReactions/ReactionRunner.cpp
  Code/GraphMol/ChemReactions/ReactionUtils.cpp
  Code/GraphMol/ChemReactions/catch_tests.cpp
  Docs/Book/RDKit_Book.rst
Labels: bug, enhancement

#3420 MolEnumerator::enumerate() should call updatePropertyCache()
  Code/GraphMol/MolEnumerator/MolEnumerator.cpp
  Code/GraphMol/MolEnumerator/enumerator_catch.cpp
Labels: bug

#3426 Replace fill-opacity= to fill-opacity: in reaction.out
  Code/PgSQL/rdkit/expected/reaction.out
Labels: bug

#3327 Some work on TautomerEnumerator
  Code/GraphMol/MolStandardize/MolStandardize.cpp
  Code/GraphMol/MolStandardize/MolStandardize.h
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/MolStandardize/Tautomer.h
  Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h
  Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp
  Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/testTautomer.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.cpp
  Data/MolStandardize/tautomerTransforms.in
  ReleaseNotes.md
Labels: Cleanup, changes results, enhancement

#3406 Add support for abbreviations
  Code/GraphMol/Abbreviations/Abbreviations.cpp
  Code/GraphMol/Abbreviations/Abbreviations.h
  Code/GraphMol/Abbreviations/AbbreviationsUtils.cpp
  Code/GraphMol/Abbreviations/CMakeLists.txt
  Code/GraphMol/Abbreviations/Wrap/CMakeLists.txt
  Code/GraphMol/Abbreviations/Wrap/rdAbbreviations.cpp
  Code/GraphMol/Abbreviations/Wrap/testAbbreviations.py
  Code/GraphMol/Abbreviations/catch_tests.cpp
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/JavaWrappers/Abbreviations.i
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/AbbreviationsTests.java
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/images/atom_labels_1.png
  Docs/Book/images/atom_labels_2.png
  Docs/Book/images/atom_labels_3.png
  rdkit/Chem/test_list.py
Labels: enhancement

#3441 Replace basestring
  Contrib/M_Kossner/Frames.py
  rdkit/utils/cactvs.py
Labels: Cleanup, enhancement

#3434 set the ChiralityPossible tag when using the new code with FindMolChiralCenters
  rdkit/Chem/__init__.py
Labels: bug

#3449 update minimallib python requirements to python3
  Code/MinimalLib/docker/Dockerfile
Labels: bug

#3440 expose PNG metadata functions to python
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#3450 expose templated coordinate generation to the JS Wrapper
  Code/MinimalLib/demo/demo.html
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
Labels: enhancement
