Repository rdkit/rdkit, pull requests merged in 2020-11, with the labels that each got.

#3536 Give a bit more time to RGD test in debug builds
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Labels: enhancement

#3525 remove the include directive for unused <access/tuptoaster.h> header
  Code/PgSQL/rdkit/bfp_gist.c
  Code/PgSQL/rdkit/low_gist.c
  Code/PgSQL/rdkit/rdkit_gist.c
Labels: Cleanup, bug

#3547 Add missing methods to remove SubstanceGroup attributes
  Code/GraphMol/SubstanceGroup.h
  Code/GraphMol/Wrap/SubstanceGroup.cpp
  Code/GraphMol/Wrap/testSGroups.py
  Code/GraphMol/catch_sgroups.cpp
Labels: bug

#3524 Removes function which is an exact duplicate of another function
  Code/GraphMol/Wrap/MolSupplier.h
  Code/GraphMol/Wrap/ResonanceMolSupplier.cpp
  Code/GraphMol/Wrap/SDMolSupplier.cpp
Labels: Cleanup, enhancement

#3538 A couple of fixes to the build system
  CMakeLists.txt
  Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.h
Labels: enhancement, infrastructure

#3535 A couple of minor improvements to FindCairo
  Code/cmake/Modules/FindCairo.cmake
Labels: enhancement, infrastructure

#3575 Fix example of SmilesToMol
  Code/GraphMol/SmilesParse/SmilesParse.h
  Code/GraphMol/Wrap/rdmolfiles.cpp
Labels: bug, documentation

#3559 correct handling of amide distances for macrocycles
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
Labels: bug

#3584 add a "comic mode" to MolDraw2D
  CMakeLists.txt
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  rdkit/Chem/Draw/__init__.py
Labels: enhancement

#3589 Update Install.md
  Docs/Book/Install.md
Labels: documentation, enhancement

#3586 Add rendering of SGroup brackets to MolDraw2D
  Code/GraphMol/MolDraw2D/DrawText.h
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.h
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.h
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolTransforms/MolTransforms.cpp
  Code/GraphMol/MolTransforms/MolTransforms.h
  Code/GraphMol/SubstanceGroup.h
Labels: enhancement
