Repository rdkit/rdkit, pull requests merged in 2020-10, with the labels that each got.

#3453 add coordgen support to demo.html
  Code/MinimalLib/demo/demo.html
Labels: enhancement

#3451 Fix dead links to inchi-trust
  External/INCHI-API/Wrap/pyInchi.cpp
Labels: bug, documentation

#3454 Two simple MolStandardizer code cleanups
  Code/GraphMol/MolStandardize/MolStandardize.cpp
Labels: Cleanup, enhancement

#3452 change default precision for coordgen
  External/CoordGen/CoordGen.h
  External/CoordGen/Wrap/rdCoordGen.cpp
  ReleaseNotes.md
Labels: changes results, enhancement

#3455 A few improvements to MolStandardize::Normalizer
  Code/GraphMol/MolStandardize/Normalize.cpp
  Code/GraphMol/MolStandardize/Normalize.h
  Code/GraphMol/MolStandardize/Wrap/Normalize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/testNormalize.cpp
Labels: enhancement

#3463 run clang-format over MolDraw2D
  Code/GraphMol/MolDraw2D/DrawText.h
  Code/GraphMol/MolDraw2D/DrawTextCairo.cpp
  Code/GraphMol/MolDraw2D/DrawTextCairo.h
  Code/GraphMol/MolDraw2D/DrawTextFT.h
  Code/GraphMol/MolDraw2D/DrawTextFTCairo.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTCairo.h
  Code/GraphMol/MolDraw2D/DrawTextFTSVG.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTSVG.h
  Code/GraphMol/MolDraw2D/DrawTextSVG.cpp
  Code/GraphMol/MolDraw2D/DrawTextSVG.h
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.h
  Code/GraphMol/MolDraw2D/MultiMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/rxn_test1.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
Labels: Cleanup

#3464 A few small tweaks to the drawing code
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
Labels: enhancement

#3459 Add Cookbook entries 30-32
  Docs/Book/Cookbook.rst
  Docs/Book/images/RDKitCB_30_im0.png
  Docs/Book/images/RDKitCB_32_im0.png
Labels: documentation, enhancement

#3466 BlockLogs was reenabling all logs, not just the ones that were disabled
  Code/RDGeneral/RDLog.cpp
Labels: bug

#3448 Get the Uncharger to deal with a larger set of acids correctly
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/test1.cpp
  Code/GraphMol/MolStandardize/testCharge.cpp
  ReleaseNotes.md
Labels: changes results, enhancement

#3469 ROMol: add inline impl for common getNumAtoms call
  Code/GraphMol/ROMol.h
Labels: enhancement, optimization

#3478 Cmake config improvements
  CMakeLists.txt
  rdkit-config-version.cmake.in
  rdkit-config.cmake.in
Labels: enhancement, infrastructure

#3481 Fix a crashing bug with None in rdMolStandardize
  Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
Labels: bug

#3480 allow fillColour to be changed from python
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
Labels: enhancement

#3467 Add nocharge algorithm example to cookbook
  Docs/Book/Cookbook.rst
  Docs/Book/images/RDKitCB_33_im0.png
  Docs/Book/images/RDKitCB_33_im1.png
  Docs/Book/images/RDKitCB_33_im2.png
Labels: documentation, enhancement

#3486 add new oxidation states for Cl, Br, I, Xe, Po, At
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/atomic_data.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: changes results, enhancement

#3484 update expected cartridge test results
  Code/PgSQL/rdkit/expected/props.out
  Code/PgSQL/rdkit/expected/reaction.out
  Code/PgSQL/rdkit/sql/props.sql
  Code/PgSQL/rdkit/sql/reaction.sql
Labels: enhancement, infrastructure

#3465 Make MetalDisconnector more robust against metallorganics
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/Metal.cpp
  Code/GraphMol/MolStandardize/Metal.h
  Code/GraphMol/MolStandardize/catch_tests.cpp
  Code/GraphMol/MolStandardize/test1.cpp
  Code/GraphMol/MolStandardize/testCharge.cpp
Labels: enhancement

#3488 Documentation update
  Docs/Book/BackwardsIncompatibleChanges.md
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/RDKit_Book.rst
  Docs/Book/source/rdkit.Chem.MolDraw.rdMolDraw2D.rst
  Docs/Book/source/rdkit.Chem.rdAbbreviations.rst
  Docs/Book/source/rdkit.Chem.rdDeprotect.rst
  Docs/Book/source/rdkit.Chem.rst
Labels: documentation, enhancement

#3475 Sphinx issue #3471
  Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
Labels: Cleanup, documentation, enhancement

#3496 add a version for the pattern fingerprint
  Code/GraphMol/Fingerprints/Fingerprints.h
  Code/GraphMol/Wrap/MolOps.cpp
Labels: enhancement

#3495 Fix undefined behavior in testCoordGen test
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/MolOps.cpp
Labels: Cleanup, bug

#3508 Fix python invalid escape sequences
  Code/GraphMol/Wrap/test_data/do_smiles.bomb.py
  Code/GraphMol/Wrap/test_data/do_smiles.py
  rdkit/Chem/EnumerateStereoisomers.py
  rdkit/Chem/MolKey/InchiInfo.py
  rdkit/Chem/Pharm3D/Pharmacophore.py
  rdkit/Chem/fmcs/fmcs.py
  rdkit/ML/Data/DataUtils.py
  rdkit/ML/Descriptors/MoleculeDescriptors.py
  rdkit/ML/Scoring/Scoring.py
  rdkit/sping/PDF/pdfgen.py
  rdkit/sping/PDF/pdfutils.py
  rdkit/sping/PDF/pidPDF.py
  rdkit/sping/PS/pidPS.py
  rdkit/sping/stringformat.py
Labels: Cleanup, enhancement

#3518 Remove accidentally included boost header
  Code/boost/serialization/singleton.hpp
Labels: Cleanup, bug

#3520 legend_height_ should be preserved after drawing the molecule
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: bug

#3512 Fix AUTOCORR2D descriptors
  rdkit/Chem/ChemUtils/DescriptorUtilities.py
  rdkit/Chem/Descriptors.py
  rdkit/Chem/UnitTestDescriptors.py
Labels: bug
