Repository rdkit/rdkit, pull requests merged in 2020-06, with the labels that each got.

#3223 Add optional timeout to RGroupDecomposition
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
  Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
  Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Labels: enhancement

#3228 gitignore source and build files from the RingFamilies external lib
  External/RingFamilies/.gitignore
Labels: Cleanup, enhancement

#3203 Formatting fix of CalcRMS
  Code/GraphMol/MolAlign/AlignMolecules.cpp
  Code/GraphMol/MolAlign/AlignMolecules.h
  Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp
Labels: Cleanup, enhancement

#3240 lock CI cairo version to (hopefully) force an install from the rdkit repo
  .azure-pipelines/linux_build.yml
Labels: bug, infrastructure

#3238 Cleanup warnings from clang-10
  Code/DataStructs/Wrap/DiscreteValueVect.cpp
  Code/DataStructs/Wrap/SparseIntVect.cpp
  Code/ForceField/MMFF/Params.cpp
  Code/ForceField/MMFF/Params.h
  Code/Geometry/Wrap/Point.cpp
  Code/Geometry/Wrap/UniformGrid3D.cpp
  Code/GraphMol/Canon.cpp
  Code/GraphMol/Depictor/DepictUtils.cpp
  Code/GraphMol/Descriptors/testRDFcustom.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/FileParsers/MolSGroupParsing.cpp
  Code/GraphMol/FindRings.cpp
  Code/GraphMol/MolAlign/AlignMolecules.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/Fragment.cpp
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/MolStandardize/Validate.cpp
  Code/GraphMol/MolStandardize/testTautomer.cpp
  Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/GraphMol/ScaffoldNetwork/catch_tests.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/SubstanceGroup.cpp
  Code/GraphMol/Wrap/Mol.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/RDGeneral/Exceptions.h
Labels: Cleanup, enhancement

#3235 Adds more options to adjustQueryProperties
  Code/GraphMol/AdjustQuery.cpp
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/test1.cpp
  Code/GraphMol/FileParsers/test_data/query_A.v3k.mol
  Code/GraphMol/FileParsers/test_data/query_Q.v3k.mol
  Code/GraphMol/MolOps.h
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/catch_adjustquery.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/test_data/adjustqueryprops_MDLfivering_1.mol
  Code/GraphMol/test_data/adjustqueryprops_MDLfivering_2.mol
  Code/GraphMol/test_data/adjustqueryprops_MDLfivering_3.mol
  Code/GraphMol/test_data/adjustqueryprops_MDLfivering_4.mol
  Code/GraphMol/test_data/adjustqueryprops_fivering_1.mol
  Code/GraphMol/test_data/adjustqueryprops_fivering_2.mol
  Code/GraphMol/test_data/adjustqueryprops_fivering_3.mol
  Code/GraphMol/test_data/adjustqueryprops_fivering_4.mol
  Code/GraphMol/test_data/adjustqueryprops_fivering_5.mol
  Code/GraphMol/test_data/adjustqueryprops_fivering_6.mol
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
Labels: enhancement

#3242 XBCORR and XBHEAD in Sgroups no longer cause parse failures
  Code/GraphMol/FileParsers/MolSGroupParsing.cpp
  Code/GraphMol/FileParsers/MolSGroupWriting.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/sgroup_test_data/repeat_groups_query1.mol
  Code/GraphMol/Wrap/SubstanceGroup.cpp
  Code/GraphMol/Wrap/testSGroups.py
Labels: bug

#3237 Support using FreeType for text rendering
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/GraphMol/MolDraw2D/DrawText.cpp
  Code/GraphMol/MolDraw2D/DrawText.h
  Code/GraphMol/MolDraw2D/DrawTextCairo.cpp
  Code/GraphMol/MolDraw2D/DrawTextCairo.h
  Code/GraphMol/MolDraw2D/DrawTextFT.cpp
  Code/GraphMol/MolDraw2D/DrawTextFT.h
  Code/GraphMol/MolDraw2D/DrawTextFTCairo.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTCairo.h
  Code/GraphMol/MolDraw2D/DrawTextFTSVG.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTSVG.h
  Code/GraphMol/MolDraw2D/DrawTextSVG.cpp
  Code/GraphMol/MolDraw2D/DrawTextSVG.h
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.h
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.h
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
  Code/RDGeneral/RDConfig.h.cmake
  Data/Fonts/Amadeus.ttf
  Data/Fonts/Telex-Regular.ttf
  Data/Fonts/amadeus_font_license.txt
  Data/Fonts/telex_font_license.txt
  ReleaseNotes.md
Labels: enhancement

#3247 LINKNODEs are ignored by the CTAB parsers
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
Labels: bug

#3205 Tautomer search
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/Fingerprints/Fingerprints.h
  Code/GraphMol/Fingerprints/PatternFingerprints.cpp
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/QueryOps.h
  Code/GraphMol/Substruct/CMakeLists.txt
  Code/GraphMol/TautomerQuery/CMakeLists.txt
  Code/GraphMol/TautomerQuery/TautomerQuery.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.h
  Code/GraphMol/TautomerQuery/Wrap/CMakeLists.txt
  Code/GraphMol/TautomerQuery/Wrap/rdTautomerQuery.cpp
  Code/GraphMol/TautomerQuery/Wrap/rough_test.py
  Code/GraphMol/TautomerQuery/catch_tests.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/TautomerQuery.i
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/TautomerQueryTests.java
Labels: enhancement

#3251 add GetStringVectProp() to SubstanceGroup class
  Code/GraphMol/Wrap/SubstanceGroup.cpp
  Code/GraphMol/Wrap/testSGroups.py
Labels: bug

#3254 Speed up ring finding by skipping nodes not in rings
  Code/GraphMol/FindRings.cpp
Labels: enhancement, optimization

#3217 fix molstogridimage on certain fragments/smarts patterns
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/RDBoost/Wrap/RDBase.cpp
  Code/RDGeneral/RDLog.cpp
  Code/RDGeneral/RDLog.h
  rdkit/Chem/Draw/UnitTestDraw.py
  rdkit/Chem/Draw/__init__.py
  rdkit/Chem/__init__.py
Labels: bug

#3250 cairo support is needed to generate PNGs
  Scripts/create_deb_packages.sh
Labels: enhancement, infrastructure
