Repository rdkit/rdkit, pull requests merged in 2020-07, with the labels that each got.

#3265 Update to Coordgen v1.4.1
  External/CoordGen/CMakeLists.txt
Labels: enhancement

#3261 Add cxsmiles query atoms to CTAB parsers and writers
  Code/GraphMol/AdjustQuery.cpp
  Code/GraphMol/ChemTransforms/ChemTransforms.cpp
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/test1.cpp
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/MolPickler.h
  Code/GraphMol/QueryOps.cpp
  Code/Query/AndQuery.h
  Code/Query/EqualityQuery.h
  Code/Query/GreaterEqualQuery.h
  Code/Query/GreaterQuery.h
  Code/Query/LessEqualQuery.h
  Code/Query/LessQuery.h
  Code/Query/NullQueryAlgebra.h
  Code/Query/OrQuery.h
  Code/Query/Query.h
  Code/Query/RangeQuery.h
  Code/Query/SetQuery.h
  Code/Query/XOrQuery.h
  Code/Query/test.cpp
  Code/Query/testExecs/.cvskeep
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
  Docs/Book/RDKit_Book.rst
Labels: enhancement

#3178 Add BCUT2D and AUTOCORR2D to desclist
  rdkit/Chem/ChemUtils/DescriptorUtilities.py
  rdkit/Chem/Descriptors.py
  rdkit/Chem/UnitTestDescriptors.py
Labels: enhancement

#3257 Support enumerating some mol file features into `MolBundles`
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/ChemReactions/Reaction.cpp
  Code/GraphMol/ChemReactions/Reaction.h
  Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
  Code/GraphMol/FileParsers/MolSGroupParsing.cpp
  Code/GraphMol/FileParsers/MolSGroupParsing.h
  Code/GraphMol/MolBundle.h
  Code/GraphMol/MolEnumerator/CMakeLists.txt
  Code/GraphMol/MolEnumerator/LinkNode.cpp
  Code/GraphMol/MolEnumerator/MolEnumerator.cpp
  Code/GraphMol/MolEnumerator/MolEnumerator.h
  Code/GraphMol/MolEnumerator/PositionVariation.cpp
  Code/GraphMol/MolEnumerator/Wrap/CMakeLists.txt
  Code/GraphMol/MolEnumerator/Wrap/rdMolEnumerator.cpp
  Code/GraphMol/MolEnumerator/Wrap/rough_test.py
  Code/GraphMol/MolEnumerator/catch_main.cpp
  Code/GraphMol/MolEnumerator/enumerator_catch.cpp
  Code/GraphMol/Wrap/MolBundle.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/testMolBundle.cpp
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/MolBundle.i
  Code/JavaWrappers/MolEnumerator.i
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/MolEnumeratorTests.java
  rdkit/Chem/AllChem.py
Labels: enhancement

#3279 rgroup speedup
  Code/GraphMol/RGroupDecomposition/RGroupData.h
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
  Code/GraphMol/RGroupDecomposition/RGroupScore.cpp
Labels: enhancement, optimization

#3286 Decouple coordgen and maeparser integrations
  .azure-pipelines/linux_build.yml
  .azure-pipelines/linux_build_cartridge.yml
  .azure-pipelines/linux_build_java.yml
  .azure-pipelines/linux_build_py37.yml
  .azure-pipelines/mac_build.yml
  .azure-pipelines/mac_build_java.yml
  .azure-pipelines/vs_build.yml
  .azure-pipelines/vs_build_dll.yml
  CMakeLists.txt
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/MolSupplier.h
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/Wrap/CMakeLists.txt
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/RDGeneral/RDConfig.h.cmake
  External/CoordGen/CMakeLists.txt
Labels: Cleanup, enhancement

#3287 Avoid really slow Windows conda builds
  Code/cmake/Modules/RDKitUtils.cmake
Labels: enhancement, infrastructure

#3289 ScaffoldNetwork not in C# wrappers
  Code/JavaWrappers/ScaffoldNetwork.i
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
Labels: bug

#3290 bonds with "either' stereo cannot be read from JSON
  Code/GraphMol/MolInterchange/Parser.cpp
  Code/GraphMol/MolInterchange/test1.cpp
Labels: bug

#3275 ScaffoldNetwork: add feature to count the number of molecules a scaffold originates from
  Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.cpp
  Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.h
  Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp
  Code/GraphMol/ScaffoldNetwork/catch_tests.cpp
Labels: enhancement

#3288 Embed default truetype font
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/GraphMol/MolDraw2D/DrawTextFT.cpp
  Code/MinimalLib/CMakeLists.txt
Labels: enhancement

#3299 Small bug fixes and cleanups from fuzz testing
  Code/GraphMol/FileParsers/FileParserUtils.h
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FindRings.cpp
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/QueryOps.h
  Code/GraphMol/ROMol.cpp
  Code/GraphMol/SubstanceGroup.cpp
  Code/RDGeneral/StreamOps.h
Labels: Cleanup, Fuzz testing, bug

#3295 Use operator() and __call__() consistently across RDKit
  Code/GraphMol/FMCS/Wrap/rdFMCS.cpp
  Code/GraphMol/FMCS/Wrap/testFMCS.py
Labels: deprecation, enhancement

#3281 Stop trying to assign hybridization to actinides
  Code/GraphMol/ConjugHybrid.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: enhancement

#3285 Get PPC builds working
  CMakeLists.txt
  Code/GraphMol/Descriptors/PMI.cpp
  Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
Labels: bug, infrastructure

#3292 Expanded support for CXSMILES features
  Code/GraphMol/AdjustQuery.cpp
  Code/GraphMol/ChemReactions/MDLParser.cpp
  Code/GraphMol/FileParsers/FileParserUtils.h
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/QueryOps.h
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/SmartsWrite.cpp
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/SmilesParse/cxsmiles_test.cpp
  Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake
  Code/GraphMol/SmilesParse/smarts.ll
  Code/GraphMol/SmilesParse/smatest.cpp
  Docs/Book/RDKit_Book.rst
  ReleaseNotes.md
Labels: enhancement
