Repository rdkit/rdkit, pull requests merged in 2020-01, with the labels that each got.

#2853 Expose SubstructLibrary serialization stream
  Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
  Code/GraphMol/SubstructLibrary/Wrap/rough_test.py
Labels: enhancement

#2870 Improve PostgreSQL cartridge install documentation
  Code/PgSQL/rdkit/Makefile
  Code/PgSQL/rdkit/README
Labels: documentation, enhancement

#2866 Update Draw.MolToImage() and Draw.MolToFile() to use the new drawing code
  rdkit/Chem/Draw/UnitTestDraw.py
  rdkit/Chem/Draw/__init__.py
Labels: Cleanup, enhancement

#2876 Fixing docs for Chem/FragmentMatcher.py
  rdkit/Chem/FragmentMatcher.py
Labels: documentation

#2889 update maven url in build system
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
Labels: bug

#2887 add a convenience function for RGD--Pandas integration
  rdkit/Chem/PandasTools.py
  rdkit/Chem/UnitTestPandasTools.py
Labels: enhancement

#2886 Add MolVS tautomer canonicalization
  Code/GraphMol/MolStandardize/MolStandardize.cpp
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/MolStandardize/Tautomer.h
  Code/GraphMol/MolStandardize/Wrap/CMakeLists.txt
  Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp
  Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/testTautomer.cpp
Labels: enhancement

#2873 Add a cartridge test to the azure devops config
  .azure-pipelines/linux_build_cartridge.yml
  azure-pipelines.yml
Labels: enhancement, infrastructure

#2884 Add a new Cookbook v2 to the RDKit docs
  Docs/Book/Cookbook.md
  Docs/Book/Cookbook.rst
  Docs/Book/images/RDKitCB_0_im0.png
  Docs/Book/images/RDKitCB_0_im1.png
  Docs/Book/images/RDKitCB_13_im0.png
  Docs/Book/images/RDKitCB_13_im1.png
  Docs/Book/images/RDKitCB_17_im0.png
  Docs/Book/images/RDKitCB_17_im1.png
  Docs/Book/images/RDKitCB_19_im0.png
  Docs/Book/images/RDKitCB_1_im0.png
  Docs/Book/images/RDKitCB_1_im1.png
  Docs/Book/images/RDKitCB_2_im0.png
  Docs/Book/images/RDKitCB_2_im1.png
  Docs/Book/images/RDKitCB_3_im0.png
  Docs/Book/images/RDKitCB_6_im0.png
  Docs/Book/images/RDKitCB_6_im1.png
  Docs/Book/images/RDKitCB_6_im2.png
  Docs/Book/images/RDKitCB_7_im0.png
  Docs/Book/images/RDKitCB_7_im1.png
  Docs/Book/images/RDKitCB_7_im2.png
  Docs/Book/images/RDKitCB_7_im3.png
  Docs/Book/images/RDKitCB_7_im4.png
  Docs/Book/images/RDKitCB_7_im5.png
  Docs/Book/images/RDKitCB_7_im6.png
  Docs/Book/images/RDKitCB_8_im0.png
Labels: documentation, enhancement

#2893 Fix redundancy in RandomSampleAllBBs
  Code/GraphMol/ChemReactions/Enumerate/EnumerationStrategyBase.h
  Code/GraphMol/ChemReactions/Enumerate/RandomSampleAllBBs.h
Labels: Cleanup

#2898 Fix to allow multistructure images in Java/C# and use MCS for c# wrapper
  Code/JavaWrappers/MolDraw2D.i
  Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
Labels: bug

#2901 java wrapper build cleanups
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
Labels: bug

#2912 cleanup of the SMILES/SMARTS parsing and writing code
  Code/GraphMol/Atom.cpp
  Code/GraphMol/Atom.h
  Code/GraphMol/Canon.cpp
  Code/GraphMol/Descriptors/AUTOCORR2D.cpp
  Code/GraphMol/Descriptors/AUTOCORR3D.cpp
  Code/GraphMol/Descriptors/GETAWAY.cpp
  Code/GraphMol/Descriptors/MORSE.cpp
  Code/GraphMol/Descriptors/MolData3Ddescriptors.cpp
  Code/GraphMol/Descriptors/RDF.cpp
  Code/GraphMol/Descriptors/WHIM.cpp
  Code/GraphMol/FileParsers/Mol2FileParser.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/testMMFFHelpers.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp
  Code/GraphMol/MolAlign/O3AAlignMolecules.cpp
  Code/GraphMol/QueryOps.h
  Code/GraphMol/SmilesParse/SmartsWrite.cpp
  Code/GraphMol/SmilesParse/SmartsWrite.h
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/SmilesParseOps.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/GraphMol/SmilesParse/smatest.cpp
  Code/GraphMol/Trajectory/trajectoryTest.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/querytest.cpp
  Code/RDGeneral/CMakeLists.txt
  Code/RDGeneral/Dict.cpp
  Code/RDGeneral/Dict.h
  Code/RDGeneral/RDProps.h
  Code/RDGeneral/testDict.cpp
  Code/RDGeneral/testRDValue.cpp
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
Labels: Cleanup, enhancement

#2918 fix doctest problem with Pandas v1.0
  rdkit/Chem/PandasTools.py
Labels: bug
