Repository rdkit/rdkit, pull requests merged in 2020-05, with the labels that each got.

#3108 Updated stk link.
  README.md
Labels: documentation

#3125 Update old windows install instructions
  Docs/Book/Install.md
Labels: documentation

#3134 Fixes #2795
  Code/PgSQL/rdkit/expected/rdkit-91.out
  Code/PgSQL/rdkit/sql/rdkit-91.sql
Labels: enhancement

#3098 Reactions should not use strict implicit valence calculations
  Code/GraphMol/ChemReactions/ReactionRunner.cpp
  Code/GraphMol/ChemReactions/testReaction.cpp
Labels: bug

#3129 Cookbook entry for ETKDG with rings
  Docs/Book/Cookbook.rst
Labels: documentation, enhancement

#3074 Set RDK_BOOST_VERSION to pass minimum required version to FindBoost
  CMakeLists.txt
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/MolDraw2D/QTDemo/CMakeLists.txt
  Code/GraphMol/Wrap/CMakeLists.txt
  Code/JavaWrappers/CMakeLists.txt
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/RDStreams/CMakeLists.txt
  External/CoordGen/CMakeLists.txt
Labels: enhancement, infrastructure

#3138 Avoid C preprocessor macros
  Code/DataStructs/BitOps.cpp
  Code/Demos/RDKit/Basement/TemplEnum/TemplEnumTools.cpp
  Code/Geometry/UniformGrid3D.cpp
  Code/GraphMol/FileParsers/PDBParser.cpp
  Code/GraphMol/FileParsers/ProximityBonds.cpp
  Code/GraphMol/MolAlign/O3AAlignMolecules.cpp
  Code/GraphMol/MolTransforms/MolTransforms.cpp
  Code/Numerics/Alignment/AlignPoints.cpp
  Code/Numerics/Conrec.h
  Code/Numerics/EigenSolvers/PowerEigenSolver.cpp
  Code/RDBoost/iterator_next.h
Labels: Cleanup, enhancement

#3159 Update the license for Github to recognize
  license.txt
Labels: documentation, enhancement

#3162 Update fuzzer dict
  Code/Fuzz/smiles_string_to_mol_fuzzer.dict
Labels: enhancement, infrastructure

#3171 fix a memory problem detected in malformed SMILES
  Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake
  Code/GraphMol/SmilesParse/smiles.yy
  Code/GraphMol/SmilesParse/test.cpp
Labels: Fuzz testing, bug

#3172 Python wrapper: SetQuery and ExpandQuery for bonds
  Code/GraphMol/Wrap/Bond.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#3165 Fix drawing of N plus
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
Labels: bug

#3182 fix a small inconsistency in the name of the inchi package
  Code/cmake/Modules/FindInchi.cmake
Labels: bug, infrastructure

#3188 remove usage of auto_ptr
  Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/GraphMol/MMPA/MMPA.cpp
  Code/GraphMol/MMPA/MMPA_UnitTest.cpp
Labels: Cleanup

#3187 Remove usage of the deprecated random_shuffle() function
  Code/GraphMol/hanoitest.cpp
  Code/GraphMol/molopstest.cpp
Labels: Cleanup, enhancement

#3124 start using boost:stacktrace
  CMakeLists.txt
  Code/RDGeneral/CMakeLists.txt
  Code/RDGeneral/Invariant.cpp
  Code/RDGeneral/RDConfig.h.cmake
Labels: enhancement
