Repository rdkit/rdkit, pull requests merged in 2020-03, with the labels that each got.

#2972 Fix build without boost serialization.
  Code/GraphMol/ScaffoldNetwork/Wrap/CMakeLists.txt
  Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp
  Code/GraphMol/ScaffoldNetwork/Wrap/testPickleScaffoldNetwork.py
  Code/GraphMol/ScaffoldNetwork/Wrap/testScaffoldNetwork.py
Labels: bug

#2982 fix a typo in the scaffold network wrappers and add some tests
  Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp
  Code/GraphMol/ScaffoldNetwork/Wrap/testScaffoldNetwork.py
Labels: bug

#2973 Add multithreaded pattern/fp generator
  .azure-pipelines/linux_build_cartridge.yml
  Code/GraphMol/SubstructLibrary/CMakeLists.txt
  Code/GraphMol/SubstructLibrary/PatternFactory.cpp
  Code/GraphMol/SubstructLibrary/PatternFactory.h
  Code/GraphMol/SubstructLibrary/SubstructLibrary.h
  Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
  Code/GraphMol/SubstructLibrary/Wrap/rough_test.py
  Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp
Labels: enhancement

#2986 add add_hs() and remove_hs() to JS wrappers
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#2985 ScaffoldNetwork rearrangements
  Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.cpp
  Code/GraphMol/ScaffoldNetwork/Wrap/testScaffoldNetwork.py
  Code/GraphMol/ScaffoldNetwork/catch_tests.cpp
Labels: enhancement

#2981 Enable larger ring matches in SMARTS expressions
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Docs/Book/RDKit_Book.rst
Labels: enhancement

#2997 Update azure-pipelines.yml
  .azure-pipelines/mac_build.yml
  .azure-pipelines/mac_build_java.yml
  azure-pipelines.yml
Labels: enhancement

#3002 adds a one-liner for getting a vector of random smiles for a molecule
  Code/GraphMol/Canon.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#3000 Fix atom highlighting in notebook PNGs
  rdkit/Chem/Draw/__init__.py
Labels: enhancement

#3007 Add support for the rest of the v3000 atom properties
  Code/GraphMol/FileParsers/FileParsers.h
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
Labels: enhancement

#2993 Add CoulombMat calculator
  Code/GraphMol/Descriptors/CMakeLists.txt
  Code/GraphMol/Descriptors/CoulombMat.cpp
  Code/GraphMol/Descriptors/CoulombMat.h
  Code/GraphMol/Descriptors/MolDescriptors3D.h
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/Descriptors/testCoulombMat.cpp
  Code/GraphMol/Descriptors/test_data/CM1.out
  Code/GraphMol/Descriptors/test_data/bobmol.sdf
Labels: enhancement

#3008 Move jupyter extension logging to the python logger
  rdkit/__init__.py
Labels: enhancement

#3011 Update Maeparser & Coordgen Dependencies
  .gitignore
  Code/cmake/Modules/Findcoordgen.cmake
  External/CoordGen/CMakeLists.txt
Labels: enhancement

#3012 Remove unnecessary files
  Code/GraphMol/Descriptors/test3D.cpp.hold
  Code/GraphMol/FileParsers/MolFileStereochem.cpp.hold
  Code/GraphMol/MolDraw2D/test1.cpp.hold
  Code/GraphMol/StructChecker/Stereo.cpp.bak
Labels: Cleanup, enhancement

#3013 allow retrieval of the atoms/bonds modified by the tautomerization
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/MolStandardize/Tautomer.h
  Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/testTautomer.cpp
Labels: enhancement

#3010 Commit of 2D draw annotation.
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.h
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/PgSQL/rdkit/expected/props.out
  Code/PgSQL/rdkit/expected/reaction.out
Labels: enhancement

#3022 Turns on cairo support (and testing) in the Azure DevOps CI builds
  .azure-pipelines/linux_build.yml
  .azure-pipelines/mac_build.yml
  .azure-pipelines/vs_build.yml
  .azure-pipelines/vs_build_dll.yml
Labels: enhancement

#3003 Allow enhanced stereo to be used in substructure search
  Code/GraphMol/Substruct/SubstructMatch.cpp
  Code/GraphMol/Substruct/SubstructMatch.h
  Code/GraphMol/Substruct/catch_tests.cpp
  Code/GraphMol/Wrap/Mol.cpp
  Docs/Book/RDKit_Book.rst
  Docs/Book/images/EnhancedStereoSSS_molA.png
  Docs/Book/images/EnhancedStereoSSS_molB.png
  Docs/Book/images/EnhancedStereoSSS_molC.png
  Docs/Book/images/EnhancedStereoSSS_molD.png
  Docs/Book/images/EnhancedStereoSSS_molE.png
  Docs/Book/images/EnhancedStereoSSS_molF.png
  Docs/Book/images/EnhancedStereoSSS_molG.png
Labels: enhancement

#3014 Add 5 new recipes to Cookbook
  Docs/Book/Cookbook.rst
  Docs/Book/images/RDKitCB_20_im0.png
  Docs/Book/images/RDKitCB_20_im1.png
  Docs/Book/images/RDKitCB_21_im0.png
  Docs/Book/images/RDKitCB_21_im1.png
  Docs/Book/images/RDKitCB_21_im2.png
  Docs/Book/images/RDKitCB_21_im3.png
  Docs/Book/images/RDKitCB_21_im4.png
  Docs/Book/images/RDKitCB_21_im5.png
  Docs/Book/images/RDKitCB_22_im0.png
  Docs/Book/images/RDKitCB_22_im1.png
  Docs/Book/images/RDKitCB_23_im0.png
  Docs/Book/images/RDKitCB_23_im1.png
Labels: documentation, enhancement

#3026 add random seed to docs to get reproducible conformations
  Docs/Book/GettingStartedInPython.rst
Labels: documentation, enhancement

#3023 Added support for Python FMCS functors
  Code/GraphMol/FMCS/FMCS.cpp
  Code/GraphMol/FMCS/FMCS.h
  Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
  Code/GraphMol/FMCS/RingMatchTableSet.h
  Code/GraphMol/FMCS/Test/testFMCS.cpp
  Code/GraphMol/FMCS/Wrap/rdFMCS.cpp
  Code/GraphMol/FMCS/Wrap/testFMCS.py
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/GraphMol/Wrap/rdchem.cpp
  Code/JavaWrappers/FMCS.i
  Code/RDBoost/Wrap.h
Labels: enhancement

#2999 Improve Conformational Sampling of Small and Large Ring Molecules
  Code/DistGeom/DistGeomUtils.cpp
  Code/DistGeom/DistGeomUtils.h
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.h
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.macrocycle.etkdg.mol
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.macrocycle.etkdgv3.mol
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.smallring.etkdgv3.mol
  Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.cpp
  Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.h
  Code/GraphMol/ForceFieldHelpers/CrystalFF/testCrystalFF.cpp
  Code/GraphMol/ForceFieldHelpers/CrystalFF/torsionPreferences_macrocycles.in
  Code/GraphMol/ForceFieldHelpers/CrystalFF/torsionPreferences_smallrings.in
  Code/JavaWrappers/DistGeom.i
Labels: enhancement

#3028 update docs for 2020.03
  CMakeLists.txt
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/images/cdk2_mol1.png
  Docs/Book/images/cdk2_mol2.png
  Docs/Book/images/cdk2_molgrid.png
  Docs/Book/images/cdk2_molgrid_aligned.png
  Docs/Book/images/similarity_map_charges.png
  Docs/Book/images/similarity_map_crippen.png
  Docs/Book/images/similarity_map_fp1.png
  Docs/Book/images/similarity_map_fp2.png
  Docs/Book/images/similarity_map_fp3.png
  Docs/Book/source/rdkit.Chem.MolDraw.rdMolDraw2D.rst
  ReleaseNotes.md
Labels: documentation, enhancement

#3032 Unset the dash pattern after drawing aromatic bonds.
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: bug

#3033 Fix/add patterns reset holders
  Code/GraphMol/SubstructLibrary/PatternFactory.cpp
  Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp
  Code/GraphMol/SubstructLibrary/Wrap/rough_test.py
Labels: bug

#3034 Tweaks and refinements to new drawing code.
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
  rdkit/Chem/Draw/__init__.py
Labels: enhancement

#3039 Updatecppdocs
  Docs/Book/BackwardsIncompatibleChanges.md
  Docs/Book/C++Examples/CMakeLists.txt
  Docs/Book/C++Examples/example1.cpp
  Docs/Book/C++Examples/example10.cpp
  Docs/Book/C++Examples/example11.cpp
  Docs/Book/C++Examples/example12.cpp
  Docs/Book/C++Examples/example13.cpp
  Docs/Book/C++Examples/example14.cpp
  Docs/Book/C++Examples/example15.cpp
  Docs/Book/C++Examples/example16.cpp
  Docs/Book/C++Examples/example17.cpp
  Docs/Book/C++Examples/example2.cpp
  Docs/Book/C++Examples/example3.cpp
  Docs/Book/C++Examples/example4.cpp
  Docs/Book/C++Examples/example5.cpp
  Docs/Book/C++Examples/example6.cpp
  Docs/Book/C++Examples/example7.cpp
  Docs/Book/C++Examples/example8.cpp
  Docs/Book/C++Examples/example9.cpp
  Docs/Book/GettingStartedInC++.md
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/Makefile
  Docs/Book/conf.py
  Docs/Book/data/test_multi_colours.py
  Docs/Book/images/atom_annotation_1.png
  Docs/Book/images/atom_highlights_1.png
  Docs/Book/images/atom_highlights_2.png
  Docs/Book/images/atom_highlights_3.png
  Docs/Book/images/stereo_annotation.png
  Docs/Book/images/substruct_search_parameters1.png
  Docs/Book/index.rst
Labels: documentation, enhancement

#3043 Add reorder tautomers function and accompanying tests
  rdkit/Chem/MolStandardize/UnitTestMolStandardize.py
  rdkit/Chem/MolStandardize/__init__.py
  rdkit/Chem/MolStandardize/tautomer.py
  rdkit/Chem/MolStandardize/test_list.py
  rdkit/Chem/test_list.py
Labels: enhancement
