Repository rdkit/rdkit, pull requests merged in 2020-02, with the labels that each got.

#2925 Update Overview.md
  Docs/Book/Overview.md
Labels: documentation

#2917 Parse and handle the stereoCare or STBOX flags in CTABs
  Code/GraphMol/AdjustQuery.cpp
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/FileParsers.h
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/catch_main.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/testPropertyLists.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/catch_main.cpp
  Code/GraphMol/catch_sgroups.cpp
  Code/PgSQL/rdkit/adapter.cpp
  Code/PgSQL/rdkit/expected/rdkit-91.out
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
Labels: enhancement

#2927 Allow custom post-match filters for substructure matching
  Code/GraphMol/Substruct/SubstructMatch.cpp
  Code/GraphMol/Substruct/SubstructMatch.h
  Code/GraphMol/Substruct/catch_tests.cpp
  Code/GraphMol/Wrap/Mol.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/Wrap/substructmethods.h
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/images/substruct_search_parameters1.png
  rdkit/Chem/Draw/IPythonConsole.py
Labels: enhancement

#2913 patch to make PandasTools tests pass with pandas v0.22
  rdkit/Chem/PandasTools.py
Labels: bug

#2945 Fix regression introduced by e245349c
  rdkit/Chem/MolStandardize/standardize.py
Labels: bug

#2911 Add a scaffold network implementation
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/ScaffoldNetwork/CMakeLists.txt
  Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.cpp
  Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.h
  Code/GraphMol/ScaffoldNetwork/Wrap/CMakeLists.txt
  Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp
  Code/GraphMol/ScaffoldNetwork/Wrap/testScaffoldNetwork.py
  Code/GraphMol/ScaffoldNetwork/catch_main.cpp
  Code/GraphMol/ScaffoldNetwork/catch_tests.cpp
  Code/GraphMol/ScaffoldNetwork/detail.h
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/ScaffoldNetwork.i
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/ScaffoldNetworkTests.java
  Code/RDBoost/Wrap.h
  Docs/Book/source/rdkit.Chem.Scaffolds.ScaffoldTree.rst
  Docs/Book/source/rdkit.Chem.Scaffolds.rdScaffoldNetwork.rst
  Docs/Book/source/rdkit.Chem.Scaffolds.rst
  rdkit/Chem/Scaffolds/ScaffoldNetwork.ipynb
Labels: enhancement

#2946 Avoid data race warning in SmilesParse.cpp
  Code/GraphMol/SmilesParse/SmilesParse.cpp
Labels: bug

#2952 Fix a problem with aromatic heteroatom tautomer enumeration
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/MolStandardize/testTautomer.cpp
  Data/MolStandardize/tautomerTransforms.in
Labels: bug

#2932 Include running the documentation tests as part of the CI runs
  .azure-pipelines/linux_build.yml
  .azure-pipelines/mac_build.yml
  .azure-pipelines/vs_build.yml
  Docs/Book/Cookbook.rst
  Docs/Book/GettingStartedInPython.rst
Labels: enhancement, infrastructure

#2957 Add BCUT 2D descriptors
  CMakeLists.txt
  Code/GraphMol/Descriptors/BCUT.cpp
  Code/GraphMol/Descriptors/BCUT.h
  Code/GraphMol/Descriptors/CMakeLists.txt
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
  Code/GraphMol/Descriptors/testBCUT.cpp
  Code/GraphMol/Descriptors/test_data/bace_200_bcut.sdf
Labels: enhancement

#2955 A couple additions to the extended Hueckel integration
  External/YAeHMOP/EHTTools.cpp
  External/YAeHMOP/EHTTools.h
  External/YAeHMOP/Wrap/rdEHTTools.cpp
  External/YAeHMOP/Wrap/testEHTTools.py
  External/YAeHMOP/test1.cpp
  External/YAeHMOP/test_data/benzene.b
  External/YAeHMOP/test_data/benzene.b.out
Labels: enhancement

#2975 Description for the data files.
  Docs/Book/data/README.md
Labels: documentation, enhancement
