Repository rdkit/rdkit, pull requests merged in 2021-07, with the labels that each got.

#4278 Fixes to integer conversions and their tests
  Code/RDGeneral/RDValue-taggedunion.h
  Code/RDGeneral/testRDValue.cpp
Labels: bug, not in release notes

#4299 Turn MRV_COORDINATE_BOND_TYPE data Substance Groups into coordinate bonds
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/RWMol.cpp
  Code/GraphMol/RWMol.h
  Code/GraphMol/Wrap/Mol.cpp
Labels: enhancement

#4318 Support using SubstructMatchParameters in RGD
  Code/GraphMol/RGroupDecomposition/RGroupCore.cpp
  Code/GraphMol/RGroupDecomposition/RGroupCore.h
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
  Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp
  Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
  Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
  Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
Labels: enhancement

#4337 Expose atomColourPalette as JSON drawOption
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
Labels: enhancement

#4339 Addresses #4329
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#4347 Two MinGW build fixes and one MSVC build fix
  CMakeLists.txt
  Code/GraphMol/FMCS/Test/testFMCS.cpp
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/GraphMol/FileParsers/GeneralFileReader.h
  Code/GraphMol/FileParsers/MolSGroupParsing.h
  Code/RDGeneral/RDExportMacros.h
  Code/cmake/Modules/RDKitUtils.cmake
Labels: bug, infrastructure

#4348 support get_json in the rdkitjs wrapper
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#4343 Improved sgroup output
  Code/GraphMol/FileParsers/MolSGroupWriting.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
Labels: enhancement

#4349 Fixes RDK_BUILD_THREADSAFE_SSS=OFF build
  .azure-pipelines/linux_build_limitexternal.yml
  CMakeLists.txt
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
  Code/GraphMol/RGroupDecomposition/RGroupFingerprintScore.cpp
  Code/GraphMol/RGroupDecomposition/RGroupGa.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/GraphMol/Substruct/SubstructMatch.cpp
  External/INCHI-API/inchi.cpp
  External/YAeHMOP/EHTTools.cpp
Labels: bug

#4353 Removed spurious dllexport on enums
  Code/GraphMol/ChemTransforms/MolFragmenter.h
  Code/GraphMol/MolHash/nmmolhash.h
  Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.h
Labels: Cleanup

#4357 Enable using the URF library in Windows static builds
  CMakeLists.txt
  External/RingFamilies/CMakeLists.txt
Labels: enhancement, infrastructure

#4356 Three more Windows build fixes
  CMakeLists.txt
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
  Code/cmake/Modules/RDKitUtils.cmake
Labels: bug, infrastructure
