Repository rdkit/rdkit, pull requests merged in 2021-04, with the labels that each got.

#4012 update clang version for linux CI fuzzer builds
  .azure-pipelines/linux_build_fuzzer.yml
Labels: bug, infrastructure

#4014 update versions for new release cycle
  CMakeLists.txt
  Docs/Book/conf.py
Labels: enhancement, not in release notes

#4017 Update coordgen to 2.0.3
  External/CoordGen/CMakeLists.txt
Labels: bug

#4020 Get SWIG wrappers working with C# again
  Code/GraphMol/MolPickler.h
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
Labels: bug

#4018 MinimalLib: add CFFI interface
  .azure-pipelines/linux_build.yml
  .azure-pipelines/mac_build.yml
  .azure-pipelines/vs_build.yml
  CMakeLists.txt
  Code/CMakeLists.txt
  Code/GraphMol/Descriptors/Property.cpp
  Code/GraphMol/DistGeomHelpers/CMakeLists.txt
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/EmbedderUtils.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/MolInterchange/Parser.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/Substruct/SubstructMatch.h
  Code/GraphMol/Substruct/SubstructUtils.cpp
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/common.h
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/simple.py
Labels: enhancement

#4033 A set of fixes for problems caused by bad input
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/RWMol.cpp
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: bug

#4046 Add datamol project
  Docs/Book/Overview.md
  README.md
Labels: documentation, enhancement

#4026 Contribute FreeWilson analysis
  Contrib/FreeWilson/README.md
  Contrib/FreeWilson/data/CHEMBL2321810.smi
  Contrib/FreeWilson/data/CHEMBL2321810_act.csv
  Contrib/FreeWilson/data/CHEMBL2321810_scaffold.mol
  Contrib/FreeWilson/freewilson.py
  Contrib/FreeWilson/pytest.ini
  Contrib/FreeWilson/requirements.txt
  Contrib/FreeWilson/setup.py
Labels: contrib, enhancement

#4054 Cleanup some problems found during an ASAN build
  Code/GraphMol/ChemTransforms/MolFragmenter.cpp
  Code/GraphMol/ChemTransforms/catch_tests.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp
  Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp
  Code/GraphMol/molopstest.cpp
Labels: bug

#3976 updates to postgreSQL cartridge
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/PgSQL/rdkit/adapter.cpp
  Code/PgSQL/rdkit/expected/props.out
  Code/PgSQL/rdkit/mol_op.c
  Code/PgSQL/rdkit/rdkit.h
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/rdkit_io.c
  Code/PgSQL/rdkit/sql/props.sql
  Docs/Book/Cartridge.md
Labels: enhancement

#4062 Add some MolStandardize functionality to the CFFI library
  Code/GraphMol/MolStandardize/MolStandardize.cpp
  Code/GraphMol/MolStandardize/MolStandardize.h
  Code/GraphMol/MolStandardize/catch_tests.cpp
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/common.h
Labels: enhancement

#4040 Allow partial deserialization of molecules
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/MolPickler.h
  Code/GraphMol/ROMol.cpp
  Code/GraphMol/ROMol.h
  Code/GraphMol/Wrap/Mol.cpp
  Code/GraphMol/testPickler.cpp
  Code/GraphMol/test_data/mol_with_confs.pkl
  Code/GraphMol/test_data/mol_with_double_confs.pkl
  Docs/Book/GettingStartedInPython.rst
Labels: enhancement, optimization

#4022 replaceSidechains creates aromatic dummy atoms
  Code/GraphMol/ChemTransforms/ChemTransforms.cpp
  Code/GraphMol/ChemTransforms/testChemTransforms.cpp
Labels: bug

#4085 Build BCUT when RDK_BUILD_DESCRIPTORS3D=OFF
  CMakeLists.txt
Labels: enhancement

#4065 Avoid that lone atoms which are part of a ring in one of the molecules become part of the MCS
  Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
  Code/GraphMol/FMCS/Wrap/testFMCS.py
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
Labels: bug

#3024 Support Chemical Markup Language, CML, for writing
  Code/GraphMol/FileParsers/CMLWriter.cpp
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/FileParsers.h
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/JavaWrappers/ROMol.i
Labels: enhancement

#4086 Making RDKit minimallib (JS lib) available through the npm package manager
  .gitignore
  Code/MinimalLib/README.md
  Code/MinimalLib/demo/demo.html
  Code/MinimalLib/docker/Dockerfile
  Code/MinimalLib/scripts/build_rdkitjs.sh
  Code/MinimalLib/scripts/npm_postpublish.sh
  Code/MinimalLib/scripts/npm_prepublish.sh
  package.json
Labels: enhancement

#4094 Update boost download location in Dockerfile
  Code/MinimalLib/docker/Dockerfile
Labels: bug, infrastructure
