Repository rdkit/rdkit, pull requests merged in 2021-01, with the labels that each got.

#3696 Move MolToSVG() to rdkit.Chem.Draw (Addresses #3694)
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/Wrap/CMakeLists.txt
  Code/GraphMol/Wrap/MolOps.cpp
Labels: bug, changes results

#3698 Add Molbundle search to SWIG
  Code/JavaWrappers/ROMol.i
Labels: enhancement

#3663 Make the scope control for Qt more idiomatic
  Code/GraphMol/MolDraw2D/Wrap/testMolDraw2DQt.py
Labels: enhancement

#3700 Added getMessage method to exceptions
  Code/JavaWrappers/RDKitExceptions.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/WrapperTests.java
Labels: enhancement

#3705 Make better use of strictParsing for SGroups
  Code/GraphMol/FileParsers/FileParsers.h
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolSGroupParsing.cpp
  Code/GraphMol/FileParsers/MolSGroupParsing.h
  Code/GraphMol/FileParsers/MolSupplier.h
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/ROMol.cpp
  Code/GraphMol/SubstanceGroup.h
Labels: enhancement

#3690 Check PIL support for tostring and fromstring
  rdkit/Chem/Draw/cairoCanvas.py
Labels: bug

#3683 update SequenceParsers.cpp
  Code/GraphMol/FileParsers/SequenceParsers.cpp
Labels: enhancement

#3714 Fix to add ZLIB_INCLUDE_DIRS for Windows build
  Code/GraphMol/FileParsers/CMakeLists.txt
Labels: bug, infrastructure

#3737 Set strictParsing to false in MinimalLib
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#3747 Fix comment to match the code in RemoveHsParameters
  Code/GraphMol/MolOps.h
Labels: bug, documentation

#3756 Include Winsock2.h instead of Windows.h in DebugTrace.h
  Code/GraphMol/FMCS/DebugTrace.h
  Code/GraphMol/FMCS/Test/testFMCS.cpp
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
Labels: enhancement

#3758 Fixes #3755
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/MolStandardize/Tautomer.h
  Code/GraphMol/MolStandardize/testTautomer.cpp
Labels: changes results
