Repository rdkit/rdkit, pull requests merged in 2021-05, with the labels that each got.

#4003 Enable storing queries in JSON
  Code/GraphMol/MolInterchange/CMakeLists.txt
  Code/GraphMol/MolInterchange/MolInterchange.h
  Code/GraphMol/MolInterchange/Parser.cpp
  Code/GraphMol/MolInterchange/Wrap/rdMolInterchange.cpp
  Code/GraphMol/MolInterchange/Writer.cpp
  Code/GraphMol/MolInterchange/details.h
  Code/GraphMol/MolInterchange/molinterchange_catch.cpp
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/MolPickler.h
  Code/GraphMol/QueryAtom.h
  Code/GraphMol/QueryBond.cpp
  Code/GraphMol/QueryBond.h
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/QueryOps.h
  Code/Query/Query.h
Labels: enhancement

#4116 update ChEMBL projects in Projects using RDKit
  README.md
Labels: documentation, enhancement

#4110 Allow MolToQPixmap to support PySide2
  rdkit/Chem/Draw/UnitTestDraw.py
  rdkit/Chem/Draw/qtCanvas.py
Labels: enhancement

#4100 handle bad input more gracefully in the minimallib
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/common.h
Labels: bug, not in release notes

#4133 preparing readme for javascript minimallib release 2021.3.2 on npm
  Code/MinimalLib/README.md
Labels: documentation, not in release notes

#4104 Normalize line endings in source code files
  .gitattributes
  Code/GraphMol/RGroupDecomposition/RGroupGa.cpp
  Code/GraphMol/RGroupDecomposition/RGroupGa.h
  Code/GraphMol/TautomerQuery/TautomerQuery.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.h
  Code/ML/Cluster/Murtagh/hc.c
  Code/ML/Cluster/Murtagh/hcdriver.c
  Code/ML/Cluster/Murtagh/hcdriver.f
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/common.h
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/cmake/Modules/FindBISON.cmake
  Contrib/FreeWilson/test/test_freewilson.py
  External/GA/util/export.h
Labels: Cleanup, enhancement

#4135 disable the fuzzer CI builds
  azure-pipelines.yml
Labels: Cleanup, Fuzz testing, not in release notes

#4142 fixed AddBond documentation
  Code/GraphMol/Wrap/EditableMol.cpp
Labels: bug, documentation

#4118 A collection of MolStandardize improvements
  Code/GraphMol/FragCatalog/test1.cpp
  Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogParams.cpp
  Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogParams.h
  Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogUtils.cpp
  Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogUtils.h
  Code/GraphMol/MolStandardize/AcidBaseCatalog/acid_base_pairs.in
  Code/GraphMol/MolStandardize/CMakeLists.txt
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/Charge.h
  Code/GraphMol/MolStandardize/Fragment.cpp
  Code/GraphMol/MolStandardize/Fragment.h
  Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogParams.cpp
  Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogParams.h
  Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogUtils.cpp
  Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogUtils.h
  Code/GraphMol/MolStandardize/FragmentCatalog/fragmentPatterns.in
  Code/GraphMol/MolStandardize/Metal.h
  Code/GraphMol/MolStandardize/MolStandardize.cpp
  Code/GraphMol/MolStandardize/MolStandardize.h
  Code/GraphMol/MolStandardize/Normalize.cpp
  Code/GraphMol/MolStandardize/Normalize.h
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/MolStandardize/Tautomer.h
  Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogEntry.cpp
  Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogEntry.h
  Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.cpp
  Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h
  Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogUtils.cpp
  Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogUtils.h
  Code/GraphMol/MolStandardize/TautomerCatalog/tautomerTransforms.in
  Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogParams.cpp
  Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogParams.h
  Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogUtils.cpp
  Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogUtils.h
  Code/GraphMol/MolStandardize/TransformCatalog/normalizations.in
  Code/GraphMol/MolStandardize/Validate.cpp
  Code/GraphMol/MolStandardize/Validate.h
  Code/GraphMol/MolStandardize/Wrap/Normalize.cpp
  Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/catch_tests.cpp
  Code/GraphMol/MolStandardize/test1.cpp
  Code/GraphMol/MolStandardize/testCharge.cpp
  Code/GraphMol/MolStandardize/testFragment.cpp
  Code/GraphMol/MolStandardize/testNormalize.cpp
  Code/GraphMol/MolStandardize/testTautomer.cpp
  Code/GraphMol/MolStandardize/test_data/acid_base_pairs2.txt
  Code/GraphMol/MolStandardize/test_data/fragmentPatterns.txt
  Code/GraphMol/MolStandardize/test_data/normalizations.txt
  Code/GraphMol/MolStandardize/test_data/tautomerTransforms.in
  Code/GraphMol/TautomerQuery/TautomerQuery.cpp
  Code/GraphMol/TautomerQuery/Wrap/rough_test.py
  Code/MinimalLib/common.h
  Data/MolStandardize/acid_base_pairs.txt
Labels: enhancement

#4166 Proper fix for CRLF endings
  .gitattributes
  Code/MinimalLib/common.h
Labels: Cleanup, enhancement, not in release notes

#4169 Some miscellaneous MinimalLib enhancements
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/common.h
  Code/MinimalLib/docs/GettingStartedInJS.html
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement
