Repository rdkit/rdkit, pull requests merged in 2021-12, with the labels that each got.

#4673 Add support for Beilstein generics when doing substructure queries
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/GenericGroups/CMakeLists.txt
  Code/GraphMol/GenericGroups/GenericGroups.cpp
  Code/GraphMol/GenericGroups/GenericGroups.h
  Code/GraphMol/GenericGroups/generic_tests.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/Substruct/CMakeLists.txt
  Code/GraphMol/Substruct/SubstructMatch.cpp
  Code/GraphMol/Substruct/SubstructMatch.h
  Code/GraphMol/Wrap/Mol.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
  Docs/Book/RDKit_Book.rst
  Docs/Book/images/ary_group.png
Labels: enhancement

#4755 Refactor the memory management of the postgres cartridge cache module
  Code/PgSQL/rdkit/cache.c
  Code/PgSQL/rdkit/cache.h
Labels: enhancement, Cleanup

#4769 Fix GenericGroups installation typos
  Code/GraphMol/GenericGroups/CMakeLists.txt
  Code/GraphMol/Substruct/CMakeLists.txt
Labels: bug, infrastructure, not in release notes

#4767 Improve CMake integration of PgSQL build
  CMakeLists.txt
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/PgSQL/rdkit/InstallPgSql.cmake.in
Labels: enhancement, infrastructure

#4777 generate the sql update files in the binary (build) directory
  Code/PgSQL/rdkit/CMakeLists.txt
Labels: enhancement, Cleanup

#4782 Fixes crashing bug with finalSubstructChecks
  Code/GraphMol/GenericGroups/generic_tests.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/Wrap/substructmethods.h
Labels: bug

#4772 Allow MolDraw2DCairo and MolDraw2DSVG to determine canvas size based on the molecule
  Code/GraphMol/MolDraw2D/DrawText.cpp
  Code/GraphMol/MolDraw2D/DrawText.h
  Code/GraphMol/MolDraw2D/DrawTextCairo.cpp
  Code/GraphMol/MolDraw2D/DrawTextCairo.h
  Code/GraphMol/MolDraw2D/DrawTextFTCairo.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTCairo.h
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.h
  Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DJS.h
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
  Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/rxn_test1.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
Labels: enhancement

#4796 silence warnings in MSVC compilations
  Code/GraphMol/Substruct/SubstructMatch.h
Labels: enhancement, Cleanup

#4791 Allow using heavy atoms only in the FragmentChooser
  Code/GraphMol/MolStandardize/Fragment.cpp
  Code/GraphMol/MolStandardize/Fragment.h
  Code/GraphMol/MolStandardize/MolStandardize.h
  Code/GraphMol/MolStandardize/Wrap/Fragment.cpp
  Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/testFragment.cpp
Labels: enhancement

#4810 Fix a number of crashing bugs in the python wrappers
  Code/GraphMol/Abbreviations/Wrap/rdAbbreviations.cpp
  Code/GraphMol/MMPA/Wrap/rdMMPA.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolInterchange/Wrap/rdMolInterchange.cpp
  Code/GraphMol/MolStandardize/Wrap/Validate.cpp
  Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp
  Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
  Code/GraphMol/SubstructLibrary/Wrap/rough_test.py
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/RDBoost/Wrap.h
Labels: bug

#4811 correctly tag unspecified branch-begin bonds in SMARTS
  Code/GraphMol/SmilesParse/SmilesParseOps.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/SmilesParse/smatest.cpp
  Code/PgSQL/rdkit/expected/rdkit-91.out
Labels: bug
