Repository rdkit/rdkit, pull requests merged in 2021-09, with the labels that each got.

#4467 Add ToList method to Sparse/ExplicitBitVector
  Code/DataStructs/Wrap/SparseIntVect.cpp
  Code/DataStructs/Wrap/testBV.py
  Code/DataStructs/Wrap/testSparseIntVect.py
  Code/DataStructs/Wrap/wrap_ExplicitBV.cpp
  Code/DataStructs/Wrap/wrap_SparseBV.cpp
Labels: enhancement

#4470 GiST support to qmol type
  Code/PgSQL/rdkit/data/qmol_data
  Code/PgSQL/rdkit/expected/molgist.out
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/sql/molgist.sql
  Code/PgSQL/rdkit/update_sql/rdkit--3.8--4.0.sql.in
Labels: enhancement

#4521 cleanup some compiler warnings
  Code/GraphMol/FMCS/Test/testFMCS.cpp
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FindRings.cpp
  Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
  Code/GraphMol/MMPA/MMPA_UnitTest.cpp
  Code/GraphMol/MolTransforms/MolTransforms.cpp
  Code/GraphMol/Substruct/catch_tests.cpp
  Code/GraphMol/Substruct/test1.cpp
  Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp
  Code/GraphMol/SubstructLibrary/catch_tests.cpp
  Code/GraphMol/TautomerQuery/catch_tests.cpp
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: enhancement, Cleanup

#4516 Add custom distance bounds parameter for ETKDG conformer generation
  Code/DistGeom/DistGeomUtils.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/EmbedderUtils.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
  Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.h
  Code/GraphMol/ForceFieldHelpers/CrystalFF/torsionPreferences_macrocycles.in
Labels: enhancement

#4518 Fixes #4504
  Code/GraphMol/Depictor/CMakeLists.txt
  Code/GraphMol/Depictor/EmbeddedFrag.cpp
  Code/GraphMol/Depictor/EmbeddedFrag.h
  Code/GraphMol/Depictor/RDDepictor.cpp
  Code/GraphMol/Depictor/Wrap/testDepictor.py
  Code/GraphMol/Depictor/catch_tests.cpp
  Code/GraphMol/Depictor/testDepictor.cpp
  Code/GraphMol/Depictor/test_data/test1.sdf
Labels: Cleanup

#4533 update github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, not in release notes

#4492 be more tolerant when kekulizing
  Code/GraphMol/Kekulize.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: enhancement

#4547 Expose get_smarts to JS
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#4543 another round of cartridge improvements
  Code/PgSQL/rdkit/expected/props.out
  Code/PgSQL/rdkit/expected/rdkit-91.out
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/sql/props.sql
  Code/PgSQL/rdkit/sql/rdkit-91.sql
  Code/PgSQL/rdkit/update_sql/rdkit--3.8--4.0.sql.in
Labels: enhancement

#4541 Additions to the jupyter integration
  rdkit/Chem/Draw/IPythonConsole.py
  rdkit/Chem/Draw/UnitTestIPython.py
Labels: enhancement

#4560 Improve performance of removing substruct/tautomer duplicates
  Code/GraphMol/Substruct/SubstructUtils.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.cpp
Labels: enhancement

#4555 Fixes a couple build warnings in QueryOps.h
  Code/GraphMol/QueryOps.h
Labels: Cleanup

#4554 remove the minimizeOnly option from the coordgen integration
  External/CoordGen/CoordGen.h
  External/CoordGen/Wrap/rdCoordGen.cpp
  External/CoordGen/Wrap/testCoordGen.py
  External/CoordGen/test.cpp
  ReleaseNotes.md
Labels: deprecation

#4536 Improve test coverage and some bug fixes
  Code/DataStructs/Wrap/testBV.py
  Code/DataStructs/Wrap/wrap_BitOps.cpp
  Code/Geometry/catch_tests.cpp
  Code/GraphMol/Abbreviations/catch_tests.cpp
  Code/GraphMol/AdjustQuery.cpp
  Code/GraphMol/Bond.cpp
  Code/GraphMol/Bond.h
  Code/GraphMol/Canon.cpp
  Code/GraphMol/Chirality.h
  Code/GraphMol/Deprotect/Deprotect.h
  Code/GraphMol/Deprotect/deprotectTest.cpp
  Code/GraphMol/FileParsers/test1.cpp
  Code/GraphMol/Matrices.cpp
  Code/GraphMol/MolCatalog/test1.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/catch_adjustquery.cpp
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/molopstest.cpp
  Code/GraphMol/testMolBundle.cpp
  Code/GraphMol/testPickler.cpp
  ReleaseNotes.md
Labels: bug, enhancement, Cleanup

#4569 Fix (new?) warnings
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/molopstest.cpp
Labels: Cleanup, not in release notes

#4563 Add support for SRUs to MolEnumerator
  Code/GraphMol/MolEnumerator/CMakeLists.txt
  Code/GraphMol/MolEnumerator/LinkNode.cpp
  Code/GraphMol/MolEnumerator/MolEnumerator.cpp
  Code/GraphMol/MolEnumerator/MolEnumerator.h
  Code/GraphMol/MolEnumerator/RepeatUnit.cpp
  Code/GraphMol/MolEnumerator/Wrap/rdMolEnumerator.cpp
  Code/GraphMol/MolEnumerator/catch_main.cpp
  Code/GraphMol/MolEnumerator/enumerator_catch.cpp
  Code/JavaWrappers/MolEnumerator.i
Labels: enhancement

#4553 fix a thread-safety bug in the UFF parameter loading
  Code/ForceField/UFF/Params.cpp
  Code/ForceField/UFF/Params.h
  Code/ForceField/UFF/testUFFForceField.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/AtomTyper.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp
  ReleaseNotes.md
Labels: bug

#4544 Major speed-up of RGD scoring
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
  Code/GraphMol/RGroupDecomposition/RGroupFingerprintScore.cpp
  Code/GraphMol/RGroupDecomposition/RGroupGa.cpp
  Code/GraphMol/RGroupDecomposition/RGroupGa.h
  Code/GraphMol/RGroupDecomposition/RGroupScore.cpp
  Code/GraphMol/RGroupDecomposition/RGroupScore.h
  Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupInternals.cpp
Labels: enhancement
