Repository rdkit/rdkit, pull requests merged in 2021-03, with the labels that each got.

#3794 DistanceGeometry: add flag to enforce trans amides
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.h
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.macrocycle1.etkdg.mol
  Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.cpp
  ReleaseNotes.md
  rdkit/Chem/Pharm3D/UnitTestEmbed.py
Labels: changes results, enhancement

#3832 Separate MolDraw2DQt into its own library
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/GraphMol/MolDraw2D/Qt/CMakeLists.txt
  Code/GraphMol/MolDraw2D/Qt/Demo/CMakeLists.txt
  Code/GraphMol/MolDraw2D/Qt/Demo/LICENSE
  Code/GraphMol/MolDraw2D/Qt/Demo/MolDisplay2DWidget.H
  Code/GraphMol/MolDraw2D/Qt/Demo/MolDisplay2DWidget.cc
  Code/GraphMol/MolDraw2D/Qt/Demo/QT4SelectItems.H
  Code/GraphMol/MolDraw2D/Qt/Demo/QT4SelectItems.cc
  Code/GraphMol/MolDraw2D/Qt/Demo/QTGet2Strings.H
  Code/GraphMol/MolDraw2D/Qt/Demo/QTGet2Strings.cc
  Code/GraphMol/MolDraw2D/Qt/Demo/RDKitSVMainWindow.H
  Code/GraphMol/MolDraw2D/Qt/Demo/RDKitSVMainWindow.cc
  Code/GraphMol/MolDraw2D/Qt/Demo/RDKitSVPanel.H
  Code/GraphMol/MolDraw2D/Qt/Demo/RDKitSVPanel.cc
  Code/GraphMol/MolDraw2D/Qt/Demo/RDKitSVSettings.H
  Code/GraphMol/MolDraw2D/Qt/Demo/RDKitSVSettings.cc
  Code/GraphMol/MolDraw2D/Qt/Demo/rdkitsv_main.cc
  Code/GraphMol/MolDraw2D/Qt/Demo/stddefs.H
  Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.cpp
  Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.h
  Code/GraphMol/MolDraw2D/Qt/DrawTextQt.cpp
  Code/GraphMol/MolDraw2D/Qt/DrawTextQt.h
  Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp
  Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.h
  Code/GraphMol/MolDraw2D/Qt/Wrap/CMakeLists.txt
  Code/GraphMol/MolDraw2D/Qt/Wrap/rdMolDraw2DQt.cpp
  Code/GraphMol/MolDraw2D/Qt/Wrap/testMolDraw2DQt.py
  Code/GraphMol/MolDraw2D/Qt/catch_qt.cpp
  Code/GraphMol/MolDraw2D/Wrap/CMakeLists.txt
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  rdkit/Chem/Draw/__init__.py
Labels: Cleanup, enhancement, infrastructure

#3808 Add tautomer query to the substructlibrary
  Code/GraphMol/SubstructLibrary/CMakeLists.txt
  Code/GraphMol/SubstructLibrary/PatternFactory.cpp
  Code/GraphMol/SubstructLibrary/PatternFactory.h
  Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp
  Code/GraphMol/SubstructLibrary/SubstructLibrary.h
  Code/GraphMol/SubstructLibrary/SubstructLibrarySerialization.h
  Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
  Code/GraphMol/SubstructLibrary/Wrap/rough_test.py
  Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.h
  Code/JavaWrappers/SubstructLibrary.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/SubstructLibraryTests.java
Labels: enhancement

#3883 Fixes Amine.Tertiary.Aromatic definition
  Data/Functional_Group_Hierarchy.txt
Labels: bug

#3878 Allow retrieving the _ErGAtomTypes property from Python
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/ReducedGraphs/ReducedGraphs.cpp
  Code/GraphMol/ReducedGraphs/Wrap/testReducedGraphs.py
  Code/GraphMol/ReducedGraphs/test1.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/molopstest.cpp
  Code/RDBoost/Wrap/RDBase.cpp
Labels: enhancement

#3888 PandasTools.RGroupDecomposition throws an error when redraw_sidechains is set to True.
  rdkit/Chem/PandasTools.py
Labels: bug

#3871 Add basic support for hydrogen bonds
  Code/GraphMol/Bond.cpp
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: enhancement

#3864 Add Kier Phi descriptor
  Code/GraphMol/Descriptors/CMakeLists.txt
  Code/GraphMol/Descriptors/ConnectivityDescriptors.cpp
  Code/GraphMol/Descriptors/ConnectivityDescriptors.h
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/Descriptors/catch_tests.cpp
  Docs/Book/GettingStartedInPython.rst
Labels: enhancement

#3894 ConfGen: Macrocycle torsion terms not being used with fused macrocycles
  Code/GraphMol/DistGeomHelpers/CMakeLists.txt
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.cpp
Labels: bug

#3875 Allow batch editing of molecules: removal only
  Code/GraphMol/Abbreviations/Abbreviations.cpp
  Code/GraphMol/Abbreviations/AbbreviationsUtils.cpp
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/ChemReactions/ReactionRunner.cpp
  Code/GraphMol/ChemTransforms/ChemTransforms.cpp
  Code/GraphMol/ChemTransforms/MolFragmenter.cpp
  Code/GraphMol/MolEnumerator/PositionVariation.cpp
  Code/GraphMol/MolHash/hashfunctions.cpp
  Code/GraphMol/MolStandardize/Fragment.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/ROMol.cpp
  Code/GraphMol/ROMol.h
  Code/GraphMol/RWMol.cpp
  Code/GraphMol/RWMol.h
  Code/GraphMol/ReducedGraphs/ReducedGraphs.cpp
  Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.cpp
  Code/GraphMol/Wrap/EditableMol.cpp
  Code/GraphMol/Wrap/Mol.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/molopstest.cpp
Labels: enhancement

#3906 Change class to struct for forward declaration
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
Labels: Cleanup, bug

#3907 Exposes InsertMol to python RWMol
  Code/GraphMol/Wrap/Mol.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#3915 Use https for Avalon and Inchi downloads
  Code/cmake/Modules/FindInchi.cmake
  External/AvalonTools/CMakeLists.txt
Labels: enhancement, infrastructure

#3916 support empty/missing SDT lines for SGroup data
  Code/GraphMol/FileParsers/MolSGroupParsing.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
Labels: enhancement

#3908 Fixes issues with unlabelled groups on aromatic nitrogens
  Code/GraphMol/RGroupDecomposition/RGroupCore.h
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
  Code/GraphMol/RGroupDecomposition/RGroupUtils.cpp
  Code/GraphMol/RGroupDecomposition/RGroupUtils.h
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/test_data/jm200186n.excerpt.out1.json
  Code/GraphMol/RGroupDecomposition/test_data/jm7b00306.excerpt.out1.json
Labels: bug

#3923 MoDraw2D: Get tests working without freetype
  .azure-pipelines/linux_build_limitexternal.yml
  Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
  Code/GraphMol/MolDraw2D/test1.cpp
  README.md
Labels: bug, infrastructure

#3927 remove an MSVC++ warning caused by #3849
  Code/Geometry/point.h
Labels: Cleanup, enhancement

#3920 include context managers for the multithreaded suppliers too
  Code/GraphMol/Wrap/MultithreadedSDMolSupplier.cpp
  Code/GraphMol/Wrap/MultithreadedSmilesMolSupplier.cpp
  Code/GraphMol/Wrap/testMultithreadedMolSupplier.py
Labels: enhancement

#3936 Fix building JavaWrappers on Windows, dynamic linking
  Code/JavaWrappers/Bond.i
  Code/JavaWrappers/GenericRDKitException.h
  Code/JavaWrappers/MolEnumerator.i
Labels: bug

#3935 Fix MolDraw2DQt exports
  Code/GraphMol/MolDraw2D/DrawText.h
  Code/GraphMol/MolDraw2D/DrawTextFT.h
  Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.h
Labels: bug

#3922 Documentation cleanup and update
  Docs/Book/BackwardsIncompatibleChanges.md
  Docs/Book/Cookbook.rst
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/RDKit_Book.rst
  Docs/Book/images/query_atoms.png
  Docs/Book/images/query_bonds.2.png
  Docs/Book/images/query_bonds.png
  README.md
  ReleaseNotes.md
Labels: documentation, enhancement

#3919 MolDraw2D: support changing annotation colours
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: enhancement

#3947 Remove temporary labels from RGD results
  Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
  Code/GraphMol/RGroupDecomposition/RGroupScore.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Labels: enhancement

#3944 Adds removeAllHydrogenRGroupsAndLabels and fixes kekulization issues
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
  Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
  Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
  Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
  Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
  Code/GraphMol/RGroupDecomposition/test_data/simple3.out1.json
  Code/GraphMol/RGroupDecomposition/test_data/simple3.out2.json
  Code/GraphMol/RGroupDecomposition/test_data/simple3.out3.json
  Code/GraphMol/RGroupDecomposition/test_data/simple3.out4.json
  Code/GraphMol/RGroupDecomposition/test_data/simple3.sdf
Labels: bug, enhancement

#3877 Make sure that added R-groups have non-zero coordinates
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/ChemTransforms/ChemTransforms.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/molopstest.cpp
Labels: bug, enhancement

#3955 appended a new project depend on RDKit
  Docs/Book/Overview.md
  README.md
Labels: documentation, enhancement

#3961 allow short atom lines in mol blocks when strictParsing is disabled
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
Labels: enhancement

#3968 Fix definition of bridgehead stereo
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/QueryOps.h
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: bug

#3970 RWMol should reset(), not release(), dp_delAtoms and dp_delBonds
  Code/GraphMol/RWMol.cpp
  Code/GraphMol/RWMol.h
Labels: bug

#3974 update to coordgen 2.0.0
  External/CoordGen/CMakeLists.txt
  External/CoordGen/CoordGen.h
  External/CoordGen/Wrap/rdCoordGen.cpp
  External/CoordGen/Wrap/testCoordGen.py
  External/CoordGen/test.cpp
Labels: enhancement

#3971 Add return codes and make RGroupDecomp less verbose
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Labels: enhancement

#3992 Update Overview.md
  Docs/Book/Overview.md
Labels: documentation, enhancement
