Repository rdkit/rdkit, pull requests merged in 2021-02, with the labels that each got.

#3769 Support new coordgen option to not always make bonds to metals zero-order
  External/CoordGen/CMakeLists.txt
  External/CoordGen/CoordGen.h
  External/CoordGen/Wrap/rdCoordGen.cpp
  External/CoordGen/test.cpp
Labels: enhancement

#3783 Fix pillow error in IPythonConsole.py
  rdkit/Chem/Draw/IPythonConsole.py
Labels: bug

#3778 Add some more comprehensive R-Group Decomposition tests
  .azure-pipelines/linux_build.yml
  .azure-pipelines/mac_build.yml
  .azure-pipelines/vs_build.yml
  CMakeLists.txt
  Code/GraphMol/RGroupDecomposition/CMakeLists.txt
  Code/GraphMol/RGroupDecomposition/RGroupUtils.cpp
  Code/GraphMol/RGroupDecomposition/RGroupUtils.h
  Code/GraphMol/RGroupDecomposition/Wrap/CMakeLists.txt
  Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
  Code/GraphMol/RGroupDecomposition/test_data/View datasets.ipynb
  Code/GraphMol/RGroupDecomposition/test_data/jm200186n.excerpt.out1.json
  Code/GraphMol/RGroupDecomposition/test_data/jm200186n.excerpt.sdf
  Code/GraphMol/RGroupDecomposition/test_data/jm7b00306.excerpt.out1.json
  Code/GraphMol/RGroupDecomposition/test_data/jm7b00306.excerpt.sdf
  Code/GraphMol/RGroupDecomposition/test_data/rgd_testing.ipynb
  Code/GraphMol/RGroupDecomposition/test_data/simple1.out1.json
  Code/GraphMol/RGroupDecomposition/test_data/simple1.out2.json
  Code/GraphMol/RGroupDecomposition/test_data/simple1.sdf
  Code/GraphMol/RGroupDecomposition/test_data/simple2.out1.json
  Code/GraphMol/RGroupDecomposition/test_data/simple2.out2.json
  Code/GraphMol/RGroupDecomposition/test_data/simple2.sdf
  Code/cmake/Modules/RDKitUtils.cmake
Labels: Testing, enhancement

#3789 lock swig version in MacOS CI builds
  .azure-pipelines/mac_build_java.yml
Labels: bug, infrastructure

#3818 Sanitize molecules when SMILES needs to be produced in PandasTools
  rdkit/Chem/PandasTools.py
Labels: bug

#3804 MolDraw2D: first pass at rendering atom lists
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/QueryOps.h
Labels: enhancement

#3812 Contrib: Added function CalcLigRMSD to calculate RMSD between pre-aligned molecules
  Contrib/CalcLigRMSD/CalcLigRMSD.py
  Contrib/CalcLigRMSD/Examples_CalcLigRMSD.ipynb
  Contrib/CalcLigRMSD/README.md
  Contrib/CalcLigRMSD/data/1C9_renamed.pdb
  Contrib/CalcLigRMSD/data/1d4i_BEG.pdb
  Contrib/CalcLigRMSD/data/3m11_AKI.pdb
  Contrib/CalcLigRMSD/data/3w2c_N15.pdb
  Contrib/CalcLigRMSD/data/4i23_1C9.pdb
  Contrib/CalcLigRMSD/data/4i24_1C9.pdb
  Contrib/CalcLigRMSD/data/4uzh_JVE.pdb
  Contrib/CalcLigRMSD/data/5dpv.pdb
  Contrib/CalcLigRMSD/data/5dt0.pdb
  Contrib/CalcLigRMSD/data/6c83.pdb
  Contrib/CalcLigRMSD/data/ACP_crystal_aligned_1.pdb
  Contrib/CalcLigRMSD/data/ACP_crystal_aligned_2.pdb
  Contrib/CalcLigRMSD/data/ACP_renamed.pdb
  Contrib/CalcLigRMSD/data/AKI_renamed.pdb
  Contrib/CalcLigRMSD/data/BEG_test.pdb
  Contrib/CalcLigRMSD/data/JVE_renamed.pdb
  Contrib/CalcLigRMSD/data/N15_renamed.pdb
  Contrib/CalcLigRMSD/data/SKE_crystal_aligned_1.pdb
  Contrib/CalcLigRMSD/data/SKE_renamed.pdb
  Contrib/CalcLigRMSD/data/aurka_protein_2c6e.pdb
  Contrib/CalcLigRMSD/data/crystal_aligned.pdb
  Contrib/CalcLigRMSD/data/docked_2c6e_ACP_pH74_netcharge1.pdb
  Contrib/CalcLigRMSD/data/docked_2c6e_AKI_pH74_netcharge1.pdb
  Contrib/CalcLigRMSD/data/docked_2c6e_JVE_pH74_netcharge1.pdb
  Contrib/CalcLigRMSD/data/docked_2c6e_N15_pH74_netcharge1.pdb
  Contrib/CalcLigRMSD/data/docked_2c6e_SKE_pH74_netcharge1.pdb
  Contrib/CalcLigRMSD/data/docked_3w2p_1C9_pH74_netcharge1.pdb
  Contrib/CalcLigRMSD/data/lig_crystal_aligned.pdb
  Contrib/CalcLigRMSD/figures/1C9.png
  Contrib/CalcLigRMSD/figures/5dpv_complex.png
  Contrib/CalcLigRMSD/figures/6c83_complex.png
  Contrib/CalcLigRMSD/figures/AKI.png
  Contrib/CalcLigRMSD/figures/BEG.png
  Contrib/CalcLigRMSD/figures/JVE.png
  Contrib/CalcLigRMSD/figures/N15.png
Labels: contrib, enhancement

#3807 Issue a warning when embedding a molecule with no Hs
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/testMMFFHelpers.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/testMultiThread.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/Builder.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/catch_graphmol.cpp
Labels: enhancement

#3831 Added 2 Cookbook examples
  Docs/Book/Cookbook.rst
  Docs/Book/images/RDKitCB_34_im0.png
  Docs/Book/images/RDKitCB_34_im1.png
  Docs/Book/images/RDKitCB_34_im2.png
Labels: documentation, enhancement

#3811 Enhanced generateDepictionMatching2DStructure functionality
  Code/GraphMol/Depictor/RDDepictor.cpp
  Code/GraphMol/Depictor/RDDepictor.h
  Code/GraphMol/Depictor/Wrap/rdDepictor.cpp
  Code/GraphMol/Depictor/Wrap/testDepictor.py
  Code/GraphMol/Depictor/testDepictor.cpp
  Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp
  Code/GraphMol/Substruct/SubstructUtils.cpp
  Code/GraphMol/Substruct/SubstructUtils.h
  Code/GraphMol/Substruct/test1.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/Wrap/substructmethods.h
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
  Code/RDBoost/Wrap.cpp
  Code/RDBoost/Wrap.h
  Docs/Book/GettingStartedInPython.rst
Labels: changes results, enhancement

#3813 Confgen: add option to use symmetry when doing RMS pruning
  Code/GraphMol/DistGeomHelpers/CMakeLists.txt
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
Labels: changes results, enhancement

#3849 cleanup a bunch of compiler warnings
  .azure-pipelines/linux_build_java.yml
  Code/Geometry/point.h
  Code/GraphMol/ChemTransforms/MolFragmenter.cpp
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/FileParsers/MolSGroupWriting.h
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/Fingerprints/MorganFingerprints.cpp
  Code/GraphMol/Fingerprints/MorganGenerator.cpp
  Code/GraphMol/Fingerprints/PatternFingerprints.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolInterchange/Parser.cpp
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/RGroupDecomposition/RGroupGa.h
  Code/GraphMol/RGroupDecomposition/RGroupUtils.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/GraphMol/Subgraphs/SubgraphUtils.h
  Code/GraphMol/SubstructLibrary/SubstructLibrarySerialization.h
  Code/RDBoost/python_streambuf.h
  Code/RDGeneral/BoostStartInclude.h
  External/GA/ga/BinaryStringChromosomePolicy.cpp
  External/GA/ga/LinkedPopLinearSel.h
  External/INCHI-API/inchi.cpp
Labels: Cleanup, enhancement
