Repository rdkit/rdkit, pull requests merged in 2022-02, with the labels that each got.

#4973 add JavaGzStreamTests
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
Labels: bug

#4980 Move isEarlyAtom to a table to reduce lock contention in getPeriodicTable
  Code/GraphMol/Atom.cpp
Labels: enhancement

#4983 Fix memory safety issues found by OSS-Fuzz
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/FileParsers/MolSGroupParsing.cpp
  Code/GraphMol/RWMol.cpp
  Code/GraphMol/catch_chirality.cpp
  Code/RDGeneral/StreamOps.h
Labels: bug, Cleanup, Fuzz testing

#4907 Clean-up Python #4815 - P1.10: Chem\MolDb
  rdkit/Chem/MolDb/FingerprintUtils.py
  rdkit/Chem/MolDb/Loader_orig.py
  rdkit/Chem/MolDb/Loader_sa.py
Labels: Cleanup

#4986 AssignStereochemistry should remove nonchiral atoms from StereoGroups
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/Chirality.h
  Code/GraphMol/ROMol.h
  Code/GraphMol/RWMol.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/SmilesParse/cxsmiles_test.cpp
  Code/GraphMol/catch_chirality.cpp
  Code/PgSQL/rdkit/expected/rdkit-91.out
  Code/PgSQL/rdkit/sql/rdkit-91.sql
Labels: bug

#4982 Support writing V3000 reactions
  Code/GraphMol/ChemReactions/ReactionParser.h
  Code/GraphMol/ChemReactions/ReactionWriter.cpp
  Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
  Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
  Code/GraphMol/ChemReactions/catch_tests.cpp
  Code/GraphMol/FileParsers/FileParserUtils.h
  Code/GraphMol/FileParsers/MolFileWriter.cpp
Labels: enhancement

#4913 Clean-up Python #4815 - P1.14: Chem\Scaffolds & Chem\SimpleEnum
  rdkit/Chem/Scaffolds/MurckoScaffold.py
  rdkit/Chem/SimpleEnum/Enumerator.py
Labels: Cleanup

#5002 resolves bad input in one of the tests
  Code/GraphMol/catch_graphmol.cpp
Labels: bug, not in release notes

#5013 operator= returns *this.
  Code/GraphMol/Conformer.h
Labels: bug, not in release notes

#4948 Refactor mol draw2 d
  Code/GraphMol/FileParsers/testPropertyLists.cpp
  Code/GraphMol/MolDraw2D/AtomSymbol.cpp
  Code/GraphMol/MolDraw2D/AtomSymbol.h
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/GraphMol/MolDraw2D/DrawAnnotation.cpp
  Code/GraphMol/MolDraw2D/DrawAnnotation.h
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/DrawMol.h
  Code/GraphMol/MolDraw2D/DrawMolMCH.cpp
  Code/GraphMol/MolDraw2D/DrawMolMCH.h
  Code/GraphMol/MolDraw2D/DrawShape.cpp
  Code/GraphMol/MolDraw2D/DrawShape.h
  Code/GraphMol/MolDraw2D/DrawText.cpp
  Code/GraphMol/MolDraw2D/DrawText.h
  Code/GraphMol/MolDraw2D/DrawTextCairo.cpp
  Code/GraphMol/MolDraw2D/DrawTextCairo.h
  Code/GraphMol/MolDraw2D/DrawTextFT.cpp
  Code/GraphMol/MolDraw2D/DrawTextFT.h
  Code/GraphMol/MolDraw2D/DrawTextFTCairo.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTCairo.h
  Code/GraphMol/MolDraw2D/DrawTextFTJS.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTJS.h
  Code/GraphMol/MolDraw2D/DrawTextFTSVG.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTSVG.h
  Code/GraphMol/MolDraw2D/DrawTextJS.cpp
  Code/GraphMol/MolDraw2D/DrawTextJS.h
  Code/GraphMol/MolDraw2D/DrawTextNotFT.cpp
  Code/GraphMol/MolDraw2D/DrawTextNotFT.h
  Code/GraphMol/MolDraw2D/DrawTextSVG.cpp
  Code/GraphMol/MolDraw2D/DrawTextSVG.h
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.h
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.h
  Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h
  Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DJS.h
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Qt/CMakeLists.txt
  Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.cpp
  Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.h
  Code/GraphMol/MolDraw2D/Qt/DrawTextQt.cpp
  Code/GraphMol/MolDraw2D/Qt/DrawTextQt.h
  Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp
  Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.h
  Code/GraphMol/MolDraw2D/StringRect.h
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/rxn_test1.cpp
  Code/GraphMol/MolDraw2D/side_by_side_images.py
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/JavaWrappers/MolDraw2D.i
  rdkit/Chem/Draw/UnitTestDraw.py
Labels: enhancement, Cleanup

#5014 Code in the docstring for `FindMolChiralCenters()` doesn't work
  rdkit/Chem/__init__.py
Labels: bug, documentation

#5011 Fix warning when generating coordinates for ZOBs
  External/CoordGen/CoordGen.h
Labels: bug

#5022 Remove extra newline from Kekulize error message.
  Code/GraphMol/Kekulize.cpp
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/WrapperTests.java
Labels: bug, documentation

#5021 Drop `gist_qmol_ops` in upgrade scripts in case it exists
  Code/PgSQL/rdkit/update_sql/rdkit--3.8--4.0.sql.in
Labels: bug

#5042 Fixes JS build broken by #4948
  Code/GraphMol/MolDraw2D/DrawTextFTJS.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTJS.h
  Code/GraphMol/MolDraw2D/DrawTextJS.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp
Labels: bug, not in release notes

#5043 enable the multithreaded LeaderPicker on linux
  Code/SimDivPickers/LeaderPicker.h
Labels: enhancement

#5045 AtomSymbol needs to have a virtual destructor
  Code/GraphMol/MolDraw2D/AtomSymbol.h
  Code/GraphMol/MolDraw2D/DrawShape.h
  Code/GraphMol/MolDraw2D/DrawTextFT.h
  Code/GraphMol/MolDraw2D/DrawTextFTCairo.h
  Code/GraphMol/MolDraw2D/DrawTextFTJS.h
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
  Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.h
Labels: bug, not in release notes

#5054 Expose MolzipParams::atomSymbols to python
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement
