Repository rdkit/rdkit, pull requests merged in 2022-12, with the labels that each got.

#5800 Remove dependency on MSVC runtime DLL in MinGW builds
  Code/RDGeneral/CMakeLists.txt
Labels: bug, Cleanup

#5835 Improvements to PandasTools.SaveXlsxFromFrame
  rdkit/Chem/PandasTools.py
Labels: enhancement

#5772 Add a timeout protection for CIP calculations
  Code/GraphMol/CIPLabeler/CIPLabeler.cpp
  Code/GraphMol/CIPLabeler/CIPLabeler.h
  Code/GraphMol/CIPLabeler/CMakeLists.txt
  Code/GraphMol/CIPLabeler/Wrap/rdCIPLabeler.cpp
  Code/GraphMol/CIPLabeler/catch_tests.cpp
  Code/GraphMol/CIPLabeler/rules/SequenceRule.cpp
  Code/GraphMol/CIPLabeler/rules/SequenceRule.h
Labels: enhancement

#5795 Get the wrappers working with SWIG 4.0
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/ChemTransforms.i
  Code/JavaWrappers/ExplicitBitVect.i
  Code/JavaWrappers/FilterCatalog.i
  Code/JavaWrappers/Fingerprints.i
  Code/JavaWrappers/RGroupDecomposition.i
  Code/JavaWrappers/SubstructLibrary.i
  Code/JavaWrappers/extend_std_vector.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/AtomPairsTests.java
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
  Code/JavaWrappers/gmwrapper/std_map.i
  Code/JavaWrappers/gmwrapper/std_vector.i
Labels: enhancement, Cleanup, infrastructure

#5836 Allow building PgSQL RPM and DEB packages
  Code/PgSQL/rdkit/CMakeLists.txt
Labels: bug, infrastructure

#5857 Set emsdk path for freetype in emscripten builds
  Code/MinimalLib/docker/Dockerfile
Labels: bug, infrastructure

#5864 Fix #5810 in V2000 mol files.
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
Labels: bug

#5804 Cleanup work on documentation Makefile
  Docs/Book/Makefile
Labels: documentation, Cleanup

#5868 Chemical drawings should be automatically enabled on Colab
  rdkit/__init__.py
Labels: bug

#5851 swap boost::tuple to std::tuple
  Code/DataStructs/MultiFPBReader.cpp
  Code/DataStructs/MultiFPBReader.h
  Code/DataStructs/Wrap/wrap_FPB.cpp
  Code/DataStructs/testMultiFPB.cpp
  Code/ForceField/MMFF/TorsionAngle.cpp
  Code/ForceField/MMFF/TorsionAngle.h
  Code/ForceField/UFF/Inversion.cpp
  Code/ForceField/UFF/Inversion.h
  Code/GraphMol/Canon.cpp
  Code/GraphMol/Canon.h
  Code/GraphMol/Fingerprints/FingerprintUtil.cpp
  Code/GraphMol/Fingerprints/FingerprintUtil.h
  Code/GraphMol/Fingerprints/MorganFingerprints.cpp
  Code/GraphMol/Fingerprints/MorganGenerator.cpp
  Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionAngleM6.h
  Code/GraphMol/ForceFieldHelpers/MMFF/Builder.h
  Code/GraphMol/ForceFieldHelpers/UFF/AtomTyper.cpp
  Code/GraphMol/FragCatalog/FragCatalogEntry.cpp
  Code/GraphMol/FragCatalog/Wrap/FragCatalog.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.h
  Code/GraphMol/StructChecker/Utilites.cpp
  Code/GraphMol/Subgraphs/SubgraphUtils.cpp
  Code/GraphMol/Subgraphs/SubgraphUtils.h
  Code/JavaWrappers/MolDraw2D.i
  Code/JavaWrappers/Subgraphs.i
  Code/JavaWrappers/boost_tuple.i
  Code/JavaWrappers/std_tuple.i
  External/INCHI-API/inchi.cpp
Labels: enhancement, Cleanup

#5886 Fix documentation example for KeyFromPropHolder
  Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
Labels: bug, documentation

#5896 Introduces AvgIpc descriptor
  rdkit/Chem/GraphDescriptors.py
  rdkit/Chem/UnitTestGraphDescriptors_2.py
Labels: enhancement

#5874 use enhanced stereo when uniquifying in SimpleEnum
  rdkit/Chem/SimpleEnum/Enumerator.py
  rdkit/Chem/SimpleEnum/UnitTestEnumerator.py
Labels: bug

#5892 Make it easy to calculate all 2D descriptors
  Docs/Book/GettingStartedInPython.rst
  rdkit/Chem/Descriptors.py
  rdkit/Chem/Graphs.py
  rdkit/Chem/UnitTestDescriptors.py
Labels: enhancement

#5904 clear MDL Rgroup labels from core atoms when we aren't using them
  Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
  Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
Labels: bug

#5891 Allow unrecognized atom types when strictParsing=False
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
Labels: bug

#5748 FingerprintGenerator refactoring
  Code/GraphMol/Fingerprints/AtomPairGenerator.cpp
  Code/GraphMol/Fingerprints/AtomPairGenerator.h
  Code/GraphMol/Fingerprints/AtomPairs.cpp
  Code/GraphMol/Fingerprints/FingerprintGenerator.cpp
  Code/GraphMol/Fingerprints/FingerprintGenerator.h
  Code/GraphMol/Fingerprints/Fingerprints.cpp
  Code/GraphMol/Fingerprints/MorganFingerprints.cpp
  Code/GraphMol/Fingerprints/MorganFingerprints.h
  Code/GraphMol/Fingerprints/MorganGenerator.cpp
  Code/GraphMol/Fingerprints/MorganGenerator.h
  Code/GraphMol/Fingerprints/RDKitFPGenerator.cpp
  Code/GraphMol/Fingerprints/RDKitFPGenerator.h
  Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.cpp
  Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.h
  Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/TopologicalTorsionWrapper.cpp
  Code/GraphMol/Fingerprints/catch_tests.cpp
  Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
  Code/GraphMol/Fingerprints/test1.cpp
  Code/GraphMol/Fingerprints/testFingerprintGenerators.cpp
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/images/mfp2_bit872.svg
  rdkit/Chem/AllChem.py
Labels: enhancement, documentation, Cleanup

#5908 Add SMILES to each group abbreviation in Cookbook
  Docs/Book/Cookbook.rst
Labels: enhancement, documentation
