Repository rdkit/rdkit, pull requests merged in 2022-01, with the labels that each got.

#4868 Fix bug with wedges being drawn backwards
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: bug

#4863 RGD: dummy atom in input structure is mishandled
  Code/GraphMol/RGroupDecomposition/RGroupData.h
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupUtils.h
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Labels: bug

#4856 Fix RunFilterCatalog() thread counts.
  Code/GraphMol/FilterCatalog/FilterCatalogRunner.cpp
Labels: bug

#4885 update MD5 for the comicneue font
  Code/GraphMol/MolDraw2D/CMakeLists.txt
Labels: infrastructure

#4879 Build documentation for 3 missing modules
  Docs/Book/source/rdkit.Chem.rdCIPLabeler.rst
  Docs/Book/source/rdkit.Chem.rdMolEnumerator.rst
  Docs/Book/source/rdkit.Chem.rdTautomerQuery.rst
  Docs/Book/source/rdkit.Chem.rst
Labels: enhancement, documentation

#4869 update CI VMs to latest versions
  .azure-pipelines/vs_build.yml
  .azure-pipelines/vs_build_dll.yml
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#4916 fix some leaks in the SWIG wrappers
  Code/JavaWrappers/MolOps.i
Labels: bug

#4865 Some refactoring of the depictor code
  Code/GraphMol/Depictor/DepictUtils.cpp
  Code/GraphMol/Depictor/DepictUtils.h
  Code/GraphMol/Depictor/EmbeddedFrag.cpp
  Code/GraphMol/Depictor/EmbeddedFrag.h
  Code/GraphMol/Depictor/RDDepictor.cpp
  Code/GraphMol/Depictor/RDDepictor.h
Labels: enhancement, Cleanup

#4927 Fix some problems turned up by ossfuzz
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/FileParsers/MolSGroupParsing.cpp
  Code/GraphMol/FileParsers/MolSGroupParsing.h
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolEnumerator/PositionVariation.cpp
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/SmartsWrite.cpp
  Code/GraphMol/SmilesParse/SmartsWrite.h
  Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smiles.yy
Labels: bug

#4859 Clean-up Python 4815 - P1.1: Chem\AtomPairs
  rdkit/Chem/AtomPairs/Pairs.py
  rdkit/Chem/AtomPairs/Sheridan.py
  rdkit/Chem/AtomPairs/Torsions.py
  rdkit/Chem/AtomPairs/Utils.py
  rdkit/Chem/AtomPairs/test_list.py
Labels: Cleanup

#4938 Updated Footnote to ChemAxon Extended Smiles
  Docs/Book/RDKit_Book.rst
Labels: documentation

#4891 Clean-up Python #4815 - P1.3: Chem\Draw
  rdkit/Chem/Draw/IPythonConsole.py
  rdkit/Chem/Draw/MolDrawing.py
  rdkit/Chem/Draw/SimilarityMaps.py
  rdkit/Chem/Draw/UnitTestDraw.py
  rdkit/Chem/Draw/UnitTestSimilarityMaps.py
  rdkit/Chem/Draw/aggCanvas.py
  rdkit/Chem/Draw/cairoCanvas.py
  rdkit/Chem/Draw/spingCanvas.py
Labels: Cleanup

#4893 Clean-up Python #4815 - P1.4: Chem\EState
  rdkit/Chem/EState/AtomTypes.py
  rdkit/Chem/EState/EState.py
  rdkit/Chem/EState/EState_VSA.py
  rdkit/Chem/EState/Fingerprinter.py
  rdkit/Chem/EState/UnitTestEState.py
  rdkit/Chem/EState/UnitTestFingerprints.py
Labels: Cleanup

#4894 Clean-up Python #4815 - P1.5: Chem\FeatMaps
  rdkit/Chem/FeatMaps/FeatMapParser.py
  rdkit/Chem/FeatMaps/FeatMapUtils.py
  rdkit/Chem/FeatMaps/FeatMaps.py
Labels: Cleanup

#4935 Fix SWIG wrappers for C#
  Code/GraphMol/SmilesParse/SmilesWrite.h
Labels: bug

#4933 Fix i-files for RDK_USE_BOOST_IOSTREAMS=OFF
  Code/JavaWrappers/MolSupplier.i
  Code/JavaWrappers/Streams.i
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/GzStreamTests.java
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/SuppliersTests.java
Labels: bug

#4954 fix CMakeLists.txt extracting link line from python LDSHARED config var
  CMakeLists.txt
Labels: bug, infrastructure

#4906 Clean-up Python #4815 - P1.9: Chem\Fraggle
  rdkit/Chem/Fraggle/FraggleSim.py
Labels: Cleanup

#4968 fix to work tests when RDK_USE_BOOST_IOSTREAMS=OFF
  Code/GraphMol/FileParsers/GeneralFileReader.h
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/FileParsers/testMultithreadedMolSupplier.cpp
Labels: bug, not in release notes

#4898 Clean-up Python #4815 - P1.8: Chem\fmcs
  rdkit/Chem/fmcs/fmcs.py
Labels: Cleanup
