Repository rdkit/rdkit, pull requests merged in 2022-06, with the labels that each got.

#5312 make the logging tests more robust
  rdkit/UnitTestLogging.py
Labels: Cleanup

#5350 Update GettingStartedInPython.rst
  Docs/Book/GettingStartedInPython.rst
Labels: documentation, Cleanup

#5356 Prevent wedging ring bonds
  Code/GraphMol/FileParsers/MolFileStereochem.cpp
  Code/GraphMol/catch_chirality.cpp
Labels: bug

#5358 Class info info missing for for wavy bonds in SVGs.
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
Labels: bug

#5343 Update docs for ReplaceSubstructs
  Code/GraphMol/Wrap/MolOps.cpp
Labels: documentation, Cleanup

#5373 Fixes #1812
  Docs/Book/Install.md
  README.md
Labels: documentation

#5322 Support conjugated terminal groups in GetBestRMS()
  Code/GraphMol/MolAlign/AlignMolecules.cpp
  Code/GraphMol/MolAlign/AlignMolecules.h
  Code/GraphMol/MolAlign/CMakeLists.txt
  Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp
  Code/GraphMol/MolAlign/Wrap/testMolAlign.py
  Code/GraphMol/MolAlign/catch_tests.cpp
  ReleaseNotes.md
Labels: enhancement, changes results

#5381 Restore #5103 that was accidentally reverted in #5132
  rdkit/Chem/PandasTools.py
Labels: bug
