Repository rdkit/rdkit, pull requests merged in 2022-04, with the labels that each got.

#5163 Very small fix to avoid an AttributeError
  rdkit/Chem/Draw/InteractiveRenderer.py
Labels: bug

#5161 update release notes, do deprecations
  Code/GraphMol/FilterCatalog/Wrap/rough_test.py
  Code/RDGeneral/RDLog.cpp
  Code/RDGeneral/RDLog.h
  ReleaseNotes.md
  rdkit/Chem/__init__.py
Labels: Cleanup

#5155 Move to C++17
  CMakeLists.txt
  Code/DataStructs/FPBReader.cpp
  Code/DataStructs/MultiFPBReader.cpp
  Code/GraphMol/Canon.cpp
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
  Code/GraphMol/FileParsers/MolFileStereochem.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FindRings.cpp
  Code/RDGeneral/Ranking.h
  Code/RDGeneral/hash/extensions.hpp
  Code/RDGeneral/hash/hash.hpp
Labels: enhancement, Cleanup

#5204 Make atom, bond iterators usable in STL algorithms
  Code/GraphMol/ROMol.h
  Code/GraphMol/catch_graphmol.cpp
Labels: enhancement

#5202 Fixes multiple definitions of symbols
  Code/DataStructs/MultiFPBReader.cpp
  Code/GraphMol/FileParsers/MolFileStereochem.cpp
  Code/GraphMol/FindStereo.cpp
  Code/RDGeneral/Ranking.h
Labels: bug, not in release notes

#5183 More consistently check for `WIN32` instead of `MSVC` in CMake files
  Code/GraphMol/CMakeLists.txt
  Code/MinimalLib/CMakeLists.txt
Labels: bug, infrastructure

#5205 Fixes array overflow in FMCS code
  Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
  Code/GraphMol/FMCS/SubstructMatchCustom.h
Labels: bug

#5211 Fix use of not thread safe function localtime()
  Code/RDGeneral/RDLog.cpp
Labels: bug, Cleanup

#5182 Check architecture of the target system to optimise popcnt
  CMakeLists.txt
Labels: bug, infrastructure

#5238 Fix qt build under VS2019
  Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.cpp
  Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.h
Labels: bug

#5243 Fix typo: quarternary --> quaternary
  Code/GraphMol/FragCatalog/Wrap/testFrags.csv
  Code/GraphMol/FragCatalog/Wrap/test_data/testFrags.csv
  Code/GraphMol/FragCatalog/test_data/testFrags.csv
  Data/FragmentDescriptors.csv
  Data/SmartsLib/RLewis_smarts.txt
  Regress/Data/RLewis_smarts.txt
Labels: Cleanup
