Repository rdkit/rdkit, pull requests merged in 2022-05, with the labels that each got.

#5212 Fix duplicate non thread safe check in VarianceDataForLabel
  Code/GraphMol/RGroupDecomposition/RGroupFingerprintScore.cpp
Labels: bug, Cleanup

#5154 Fix for RGD dummy atom bug in RDKit::replaceCore
  Code/GraphMol/ChemTransforms/ChemTransforms.cpp
  Code/GraphMol/RGroupDecomposition/RGroupData.h
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Labels: bug

#5248 Make TautomerQuery serializable
  Code/GraphMol/TautomerQuery/CMakeLists.txt
  Code/GraphMol/TautomerQuery/TautomerQuery.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.h
  Code/GraphMol/TautomerQuery/Wrap/rdTautomerQuery.cpp
  Code/GraphMol/TautomerQuery/Wrap/rough_test.py
  Code/GraphMol/TautomerQuery/catch_tests.cpp
Labels: enhancement

#5264 Add support for Pol and Mod pseudoatoms
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: enhancement

#5249 add boost::serialization support to ROMol
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/FilterCatalog/FilterMatchers.h
  Code/GraphMol/ROMol.cpp
  Code/GraphMol/ROMol.h
  Code/GraphMol/SubstructLibrary/SubstructLibrarySerialization.h
  Code/GraphMol/testPickler.cpp
Labels: enhancement

#5265 Allow the compiler to generate default ChemicalReaction copy assignment operator
  Code/GraphMol/ChemReactions/Reaction.h
  Code/GraphMol/ChemReactions/testReaction.cpp
Labels: enhancement

#5270 Make the aliphatic imine rule more closely match the definition in the paper
  Code/GraphMol/MolStandardize/TautomerCatalog/tautomerTransforms.in
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/catch_tests.cpp
  Code/GraphMol/MolStandardize/testTautomer.cpp
Labels: bug, changes results

#5291 remove extra output from CXSMILES
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: bug, not in release notes

#5293 stop outputting empty block in CXSMILES
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
Labels: bug, not in release notes

#5284 make the catch tests build faster
  Code/Geometry/catch_tests.cpp
  Code/GraphMol/Abbreviations/CMakeLists.txt
  Code/GraphMol/CIPLabeler/CMakeLists.txt
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/ChemReactions/CMakeLists.txt
  Code/GraphMol/ChemTransforms/CMakeLists.txt
  Code/GraphMol/Depictor/CMakeLists.txt
  Code/GraphMol/Deprotect/deprotectTest.cpp
  Code/GraphMol/Descriptors/CMakeLists.txt
  Code/GraphMol/DistGeomHelpers/CMakeLists.txt
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/catch_main.cpp
  Code/GraphMol/Fingerprints/CMakeLists.txt
  Code/GraphMol/GenericGroups/CMakeLists.txt
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/GraphMol/MolEnumerator/CMakeLists.txt
  Code/GraphMol/MolHash/CMakeLists.txt
  Code/GraphMol/MolInterchange/CMakeLists.txt
  Code/GraphMol/MolStandardize/CMakeLists.txt
  Code/GraphMol/RGroupDecomposition/CMakeLists.txt
  Code/GraphMol/ScaffoldNetwork/CMakeLists.txt
  Code/GraphMol/ScaffoldNetwork/catch_main.cpp
  Code/GraphMol/SmilesParse/CMakeLists.txt
  Code/GraphMol/Substruct/CMakeLists.txt
  Code/GraphMol/SubstructLibrary/CMakeLists.txt
  Code/GraphMol/TautomerQuery/CMakeLists.txt
  Code/GraphMol/catch_main.cpp
  Code/Numerics/testConrec.cpp
  Code/RDGeneral/CMakeLists.txt
  Code/SimDivPickers/catch_tests.cpp
  Code/cmake/Modules/RDKitUtils.cmake
  External/YAeHMOP/test1.cpp
Labels: Cleanup, infrastructure

#5300 Expose mappings of atom/bond indices abbreviated mol->original mol
  Code/GraphMol/Abbreviations/Abbreviations.cpp
  Code/GraphMol/Abbreviations/Abbreviations.h
  Code/GraphMol/Abbreviations/AbbreviationsUtils.cpp
  Code/GraphMol/Abbreviations/Wrap/rdAbbreviations.cpp
  Code/GraphMol/Abbreviations/Wrap/testAbbreviations.py
  Code/GraphMol/Abbreviations/catch_tests.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#5084 Initial support for non-tetrahedral stereochemistry
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/Atom.cpp
  Code/GraphMol/Atom.h
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/Canon.cpp
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/Chirality.h
  Code/GraphMol/ConjugHybrid.cpp
  Code/GraphMol/Depictor/DepictUtils.cpp
  Code/GraphMol/Depictor/RDDepictor.cpp
  Code/GraphMol/Depictor/catch_tests.cpp
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/FindStereo.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/AtomTyper.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/NontetrahedralStereo.cpp
  Code/GraphMol/SmilesParse/CMakeLists.txt
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/SmilesParseOps.cpp
  Code/GraphMol/SmilesParse/SmilesParseOps.h
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake
  Code/GraphMol/SmilesParse/lex.yysmiles.cpp.cmake
  Code/GraphMol/SmilesParse/nontetrahedral_tests.cpp
  Code/GraphMol/SmilesParse/smarts.ll
  Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake
  Code/GraphMol/SmilesParse/smarts.yy
  Code/GraphMol/SmilesParse/smatest.cpp
  Code/GraphMol/SmilesParse/smiles.ll
  Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake
  Code/GraphMol/SmilesParse/smiles.yy
  Code/GraphMol/SmilesParse/test.cpp
  Code/GraphMol/SmilesParse/test_data/inorganic_stereo.smi
  Code/GraphMol/Wrap/Atom.cpp
  Code/GraphMol/Wrap/Chirality.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/test_data/nontetrahedral_3d.sdf
  Code/Numerics/Matrix.h
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
  Docs/Book/RDKit_Book.rst
  Docs/Book/images/nontetstereo_ex1.png
  Docs/Book/images/nontetstereo_ex2.png
  Docs/Book/images/nontetstereo_missing1.png
  Docs/Book/images/nontetstereo_oh1.png
  Docs/Book/images/nontetstereo_oh2.png
  Docs/Book/images/nontetstereo_sp1.png
  Docs/Book/images/nontetstereo_sp2.png
  Docs/Book/images/nontetstereo_sp3.png
  Docs/Book/images/nontetstereo_sp4.png
  Docs/Book/images/nontetstereo_tb1.png
  Docs/Book/images/nontetstereo_tb2.png
Labels: enhancement

#5299 Add ChemicalReaction copy assignment implementation
  Code/GraphMol/ChemReactions/Reaction.h
  Code/GraphMol/ChemReactions/testReaction.cpp
Labels: bug, not in release notes

#5309 Add a global feature flag to enable the "new" stereo perception code
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/Chirality.h
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/catch_chirality.cpp
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
  Docs/Book/RDKit_Book.rst
Labels: enhancement

#5335 revert #5251, document the problem
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Docs/Book/RDKit_Book.rst
Labels: Cleanup, not in release notes
