Repository rdkit/rdkit, pull requests merged in 2022-11, with the labels that each got.

#5676 run clang_format
  Code/DataStructs/Wrap/wrap_ExplicitBV.cpp
  Code/DataStructs/Wrap/wrap_SparseBV.cpp
  Code/ForceField/Wrap/ForceField.cpp
  Code/GraphMol/Abbreviations/AbbreviationsUtils.cpp
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/Aromaticity.cpp
  Code/GraphMol/Atom.cpp
  Code/GraphMol/ChemReactions/CDXMLParser.cpp
  Code/GraphMol/ChemTransforms/ChemTransforms.cpp
  Code/GraphMol/ChemTransforms/catch_tests.cpp
  Code/GraphMol/Descriptors/testATF.cpp
  Code/GraphMol/Descriptors/testBCUT.cpp
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/GraphMol/FileParsers/CDXMLParser.cpp
  Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/FileParsers/testMultithreadedMolSupplier.cpp
  Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
  Code/GraphMol/FindRings.cpp
  Code/GraphMol/MolChemicalFeatures/testFeatures.cpp
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp
  Code/GraphMol/RGroupDecomposition/RGroupGa.cpp
  Code/GraphMol/RGroupDecomposition/RGroupScore.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupInternals.cpp
  Code/GraphMol/Resonance.cpp
  Code/GraphMol/StructChecker/AugmentedAtomData.cpp
  Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
  Code/GraphMol/Wrap/Atom.cpp
  Code/GraphMol/Wrap/Bond.cpp
  Code/GraphMol/Wrap/Conformer.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/ResonanceMolSupplier.cpp
  Code/GraphMol/Wrap/SubstanceGroup.cpp
  Code/GraphMol/Wrap/Table.cpp
  Code/GraphMol/Wrap/rdchem.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/atomic_data.cpp
  Code/MinimalLib/jswrapper.cpp
Labels: Cleanup

#5675 Do deprecations for the 2023.03 release
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/SmilesParse.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/catch_chirality.cpp
  Code/MinimalLib/common.h
  Code/MinimalLib/demo/demo.html
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/tests/tests.js
  ReleaseNotes.md
  rdkit/Chem/PandasTools.py
Labels: Cleanup

#5698 Make PandasTools.RGroupDecompositionToFrame re-entrant
  rdkit/Chem/PandasTools.py
Labels: bug

#5697 stop building catch_main when tests are disabled
  Code/RDGeneral/CMakeLists.txt
Labels: bug, infrastructure

#5722 Fixes bond index parsing for w/c/t/ctu labels in CXSMILES/CXSMARTS
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: bug

#5729 CFFI/MinimalLib fixes
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/common.h
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: bug, Cleanup

#5728 allowNontetrahedralChiralty should be honored when reading/writing SMILES
  Code/GraphMol/SmilesParse/SmilesParseOps.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/nontetrahedral_tests.cpp
Labels: bug

#5732 add includeRedundantEnvironments support to GetMorganGenerator
  Code/GraphMol/Fingerprints/CMakeLists.txt
  Code/GraphMol/Fingerprints/MorganGenerator.cpp
  Code/GraphMol/Fingerprints/MorganGenerator.h
  Code/GraphMol/Fingerprints/Wrap/MorganWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/testGenerators.py
  Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
Labels: enhancement

#5731 Enable additional parameters in prepareAndDrawMolecule() and expose them to CFFI/MinimalLib
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.h
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/common.h
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/tests/tests.js
  rdkit/Chem/Draw/InteractiveRenderer.py
Labels: enhancement

#5750 Avoid passing a NULL pointer to CanSmiles()
  External/AvalonTools/AvalonTools.cpp
  External/AvalonTools/test1.cpp
Labels: bug

#5755 Add wavy stereo bond support to cdxml
  Code/GraphMol/FileParsers/CDXMLParser.cpp
  Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
  Code/GraphMol/test_data/CDXML/wavy-single.cdxml
  Code/GraphMol/test_data/CDXML/wavy.cdxml
Labels: bug

#5786 extend the allowed valences of the alkali earths
  Code/GraphMol/Atom.cpp
  Code/GraphMol/atomic_data.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: bug

#5774 Expose getMolFrags in CFFI and MinimalLib
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/common.h
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#5802 Update macOS target platform to 10.13
  azure-pipelines.yml
Labels: bug, infrastructure

#5806 Enable get_molblock(details_json) from MinimalLib
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/common.h
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement
