Repository rdkit/rdkit, pull requests merged in 2022-09, with the labels that each got.

#5533 Pin cmake in mac and qt in linux for azure builds
  .azure-pipelines/linux_build.yml
  .azure-pipelines/mac_build.yml
Labels: infrastructure, not in release notes

#5442 New version of AssignStereochemistry
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/Chirality.h
  Code/GraphMol/FindStereo.cpp
  Code/GraphMol/Wrap/ChiralityOps.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/new_canon.cpp
  Code/GraphMol/new_canon.h
Labels: enhancement

#5484 Improved bond highlights
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/DrawMol.h
  Code/GraphMol/MolDraw2D/DrawMolMCH.cpp
  Code/GraphMol/MolDraw2D/DrawMolMCH.h
  Code/GraphMol/MolDraw2D/DrawShape.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h
  Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/rxn_test1.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/GraphMol/MolDraw2D/update_hash_codes.py
  rdkit/Chem/Draw/UnitTestDraw.py
Labels: enhancement

#5526 Add Substance Groups and Stereo Groups to debugMol()
  Code/GraphMol/ROMol.cpp
  Code/GraphMol/StereoGroup.cpp
  Code/GraphMol/StereoGroup.h
  Code/GraphMol/SubstanceGroup.cpp
  Code/GraphMol/SubstanceGroup.h
Labels: enhancement

#5277 Expose reaction drawing and additional FPs in MinimalLib
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/common.h
  Code/MinimalLib/demo/demo.html
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#5524 Include element name in atomic data
  Code/GraphMol/PeriodicTable.h
  Code/GraphMol/Wrap/Table.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/atomic_data.cpp
  Code/GraphMol/atomic_data.h
Labels: enhancement

#5503 MolDraw2D::drawMolecules() should not crash on null molecules
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: bug

#5543 fix windows dll ci builds
  .azure-pipelines/mac_build.yml
  .azure-pipelines/mac_build_java.yml
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.h
  azure-pipelines.yml
Labels: not in release notes

#5544 make it easy to create DAT SGroups from Python
  Code/GraphMol/Wrap/SubstanceGroup.cpp
  Code/GraphMol/Wrap/testSGroups.py
Labels: enhancement

#5519 Fixed scale
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: bug, not in release notes

#5561 fix warnings ahead of 2022.09 release
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/ChemTransforms/MolFragmenter.cpp
  Code/GraphMol/FileParsers/ProximityBonds.cpp
  Code/GraphMol/FindStereo.cpp
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.h
  Code/RDGeneral/RDLog.cpp
  Contrib/ConformerParser/ConformerParser.cpp
Labels: enhancement, Cleanup

#5563 mergeQueryHs will not remove isotopes
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#5581 small changes to get the RDKit to build with C++20
  Code/Catalogs/Catalog.h
  Code/RDGeneral/ConcurrentQueue.h
Labels: enhancement, Cleanup

#5580 Add ColorPalette_Vect to SWIG bindings
  Code/JavaWrappers/MolDraw2D.i
  Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/MolDrawHighlightTest.cs
Labels: enhancement

#5575 Add CXSMILES support for bond wedging and wiggly bonds
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolFileStereochem.cpp
  Code/GraphMol/FileParsers/MolFileStereochem.h
  Code/GraphMol/MolOps.h
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/SmilesParseOps.h
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: enhancement

#5587 Remove unnecessary compiler flags that would be ignored anyway
  Code/MinimalLib/docker/Dockerfile
Labels: Cleanup

#5591 Update AvalonTools to version 2.0.1
  External/AvalonTools/AvalonToolkit_1.2_patch.txt
  External/AvalonTools/CMakeLists.txt
  External/AvalonTools/download-avalontoolkit.sh
Labels: Cleanup
