Repository rdkit/rdkit, pull requests merged in 2023-05, with the labels that each got.

#6331 prep for next release cycle
  CMakeLists.txt
  Docs/Book/conf.py
  ReleaseNotes.md
Labels: infrastructure, not in release notes

#6330 bump yaehmop version
  External/YAeHMOP/CMakeLists.txt
Labels: bug, Cleanup

#6338 Added cstdint include
  Code/RDGeneral/RDLog.h
Labels: bug, Cleanup

#6340 add DebugDraw() function
  rdkit/Chem/Draw/__init__.py
Labels: enhancement

#6346 Fix swig memory leak
  Code/GraphMol/FilterCatalog/CMakeLists.txt
  Code/JavaWrappers/RWMol.i
  Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/ToMolMemoryTest.cs
Labels: bug

#6339 remove the dependency from python distutils in the top CMakeLists.txt file
  CMakeLists.txt
Labels: bug, infrastructure

#6341 take drawOptions into account when exporting structure to xlsx format
  rdkit/Chem/PandasTools.py
Labels: bug

#6361 adjustQueryProperties cleanup
  Code/GraphMol/AdjustQuery.cpp
  Code/GraphMol/Wrap/MolOps.cpp
Labels: Cleanup

#6356 Add inlines to ForceFieldHelpers header functions
  Code/GraphMol/ForceFieldHelpers/FFConvenience.h
  Code/GraphMol/ForceFieldHelpers/MMFF/MMFF.h
  Code/GraphMol/ForceFieldHelpers/UFF/UFF.h
Labels: bug

#6363 postgres cartridge: cleanup a few obsolete build options
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/PgSQL/rdkit/Makefile
  Code/PgSQL/rdkit/bfp_gin.c
  Code/PgSQL/rdkit/guc.c
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/update_sql/rdkit--3.8--4.0.sql.in
  Code/PgSQL/rdkit/update_sql/rdkit--4.1.1--4.2.sql.in
  Code/PgSQL/rdkit/update_sql/rdkit--4.2--4.3.0.sql.in
Labels: enhancement, Cleanup

#6367 straightenDepiction should not consider 0-degree rotations as multiples of 60
  Code/GraphMol/Depictor/RDDepictor.cpp
  Code/GraphMol/Depictor/testDepictor.cpp
  Code/MinimalLib/tests/tests.js
Labels: bug

#6371 CMAKE_INSTALL_PREFIX not honored during installation of the Python Files
  CMakeLists.txt
Labels: bug, Cleanup, not in release notes

#6372 expose two missing EmbedFailureCauses tags to python
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
Labels: bug

#6355 Optimize GetPropsFromDict: use tags for conversion
  Code/GraphMol/Wrap/Atom.cpp
  Code/GraphMol/Wrap/Bond.cpp
  Code/GraphMol/Wrap/Conformer.cpp
  Code/GraphMol/Wrap/Mol.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/SubstanceGroup.cpp
  Code/GraphMol/Wrap/props.hpp
  Code/GraphMol/Wrap/testPropertyLists.py
Labels: enhancement

#6391 Fix identical for-loop variable names
  Code/RDGeneral/Dict.h
Labels: Cleanup

#6385 Fixes some issues in the SubstructLibrary JS implementation
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#6415 expose some missing CXSmiles flags to python
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: bug
