Repository rdkit/rdkit, pull requests merged in 2023-07, with the labels that each got.

#6485 CMAKE_INSTALL_PREFIX not honored for Python files installation on Windows
  CMakeLists.txt
Labels: bug, infrastructure

#6456 Switch to determining atom chiral types from pseudo 3D instead of bond dirs
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
  Code/GraphMol/FileParsers/molfile_stereo_catch.cpp
  Code/GraphMol/testChirality.cpp
  Code/GraphMol/test_data/github87.mol
  rdkit/Chem/UnitTestInchi.py
Labels: enhancement

#6469 unused targetBondLength argument in the CDXML parser's scaleBonds
  Code/GraphMol/FileParsers/CDXMLParser.cpp
Labels: Cleanup, not in release notes

#6542 Add MolEnumerator to C#
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
  Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/MolEnumeratorTest.cs
Labels: bug

#6496 Make sure that molecules are shown as images by PandasTools also when DataFrames are truncated horizontally
  rdkit/Chem/PandasPatcher.py
  rdkit/Chem/UnitTestPandasTools.py
Labels: bug

#6304 refactor(python): replace deprecated unittest methods
  Code/Demos/boost/smartPtrsAndIters/test.py
  Code/GraphMol/ChemReactions/Wrap/testEnumerations.py
  Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
  Code/GraphMol/ChemReactions/Wrap/testSanitize.py
  Code/GraphMol/FilterCatalog/Wrap/rough_test.py
  Code/GraphMol/MolChemicalFeatures/Wrap/testChemicalFeatures.py
  Code/GraphMol/SLNParse/Wrap/testSLN.py
  Code/GraphMol/StructChecker/Wrap/rough_test.py
  Code/GraphMol/Wrap/rough_test.py
  Code/ML/InfoTheory/Wrap/testRanker.py
  Contrib/ConformerParser/Wrap/testConformerParser.py
  rdkit/Chem/MolStandardize/UnitTestMolStandardize.py
  rdkit/DataStructs/UnitTestcBitVect.py
  rdkit/Dbase/UnitTestDbUtils.py
Labels: bug, Cleanup

#6511 Drop the s_m_color_rgb property from MaeWriter
  Code/GraphMol/FileParsers/MaeWriter.cpp
  Code/GraphMol/FileParsers/MolWriters.h
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/Wrap/MaeWriter.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: bug

#6519 Exposed partial sanitization options to MinimalLib (both JS and CFFI)
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/common.h
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#6535 update windows DLL CI build config
  .azure-pipelines/vs_build_dll.yml
  azure-pipelines.yml
Labels: bug, infrastructure

#6548 Deprecate the pure python MolStandardize implementations.
  ReleaseNotes.md
  rdkit/Chem/MolStandardize/charge.py
  rdkit/Chem/MolStandardize/fragment.py
  rdkit/Chem/MolStandardize/metal.py
  rdkit/Chem/MolStandardize/normalize.py
  rdkit/Chem/MolStandardize/resonance.py
  rdkit/Chem/MolStandardize/standardize.py
  rdkit/Chem/MolStandardize/tautomer.py
  rdkit/Chem/MolStandardize/validate.py
  rdkit/Chem/MolStandardize/validations.py
Labels: deprecation, Cleanup

#6491 Add an in place version of most of the MolStandardize functionality
  Code/GraphMol/ChemReactions/Reaction.cpp
  Code/GraphMol/ChemReactions/Reaction.h
  Code/GraphMol/ChemReactions/ReactionRunner.cpp
  Code/GraphMol/ChemReactions/ReactionRunner.h
  Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
  Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
  Code/GraphMol/ChemReactions/catch_tests.cpp
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/Charge.h
  Code/GraphMol/MolStandardize/Fragment.cpp
  Code/GraphMol/MolStandardize/Fragment.h
  Code/GraphMol/MolStandardize/Metal.h
  Code/GraphMol/MolStandardize/MolStandardize.cpp
  Code/GraphMol/MolStandardize/MolStandardize.h
  Code/GraphMol/MolStandardize/Normalize.cpp
  Code/GraphMol/MolStandardize/Normalize.h
  Code/GraphMol/MolStandardize/Wrap/Charge.cpp
  Code/GraphMol/MolStandardize/Wrap/Fragment.cpp
  Code/GraphMol/MolStandardize/Wrap/Metal.cpp
  Code/GraphMol/MolStandardize/Wrap/Normalize.cpp
  Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/catch_tests.cpp
Labels: enhancement

#6560 Optionally forward Enhanced Stereo Group ids
  Code/GraphMol/Canon.cpp
  Code/GraphMol/ChemReactions/ReactionRunner.cpp
  Code/GraphMol/ChemTransforms/ChemTransforms.cpp
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/FileParsers/CDXMLParser.cpp
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/testExtendedStereoParsing.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolInterchange/Parser.cpp
  Code/GraphMol/MolInterchange/Writer.cpp
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/MolPickler.h
  Code/GraphMol/ROMol.cpp
  Code/GraphMol/Renumber.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/cxsmiles_test.cpp
  Code/GraphMol/StereoGroup.cpp
  Code/GraphMol/StereoGroup.h
  Code/GraphMol/Wrap/StereoGroup.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/catch_canon.cpp
Labels: enhancement

#6527 Fix issue introduced in #6473
  Code/GraphMol/FindStereo.cpp
  Code/GraphMol/catch_chirality.cpp
Labels: bug, not in release notes

#6080 Mols matrix to grid image
  rdkit/Chem/Draw/UnitTestDraw.py
  rdkit/Chem/Draw/__init__.py
Labels: enhancement
