Repository rdkit/rdkit, pull requests merged in 2023-02, with the labels that each got.

#6024 Expose fingerprint generator options to python
  Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.cpp
  Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.h
  Code/GraphMol/Fingerprints/Wrap/AtomPairWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/MorganWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/RDKitFPWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/TopologicalTorsionWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/testGenerators.py
  Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
Labels: enhancement, Cleanup

#6016 cleanup a compiler warning about a multiline comment
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
Labels: Cleanup, not in release notes

#6037 Allow SMARTS of zero order bonds to match zero order bonds
  Code/GraphMol/SmilesParse/SmartsWrite.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: enhancement

#6038 Change IUPAC metal->non-metal single bonds to dative
  Code/GraphMol/FileParsers/test1.cpp
  Code/GraphMol/MolInterchange/Parser.cpp
  Code/GraphMol/MolInterchange/Writer.cpp
  Code/GraphMol/MolInterchange/details.h
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/MolStandardize/test1.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/PgSQL/rdkit/expected/json.out
  Docs/Book/RDKit_Book.rst
Labels: enhancement

#6004 Allow WriteSDF to create v3000 SDF files
  rdkit/Chem/PandasTools.py
  rdkit/Chem/UnitTestPandasTools.py
Labels: enhancement

#6046 Replace the broken, commented out test for legacy stereo with a test that works
  Code/MinimalLib/tests/tests.js
Labels: bug, Cleanup, not in release notes

#6051 Add canonicalization of stereo groups (enhanced stereo)
  Code/GraphMol/Canon.cpp
  Code/GraphMol/Canon.h
  Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
  Code/GraphMol/ChemReactions/catch_tests.cpp
  Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
  Code/GraphMol/MolHash/Wrap/testMolHash.py
  Code/GraphMol/MolHash/catch_tests.cpp
  Code/GraphMol/MolInterchange/molinterchange_catch.cpp
  Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/catch_canon.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/new_canon.cpp
  Code/GraphMol/new_canon.h
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/WrapperTests.java
  Code/PgSQL/rdkit/expected/rdkit-91.out
  Docs/Book/RDKit_Book.rst
  ReleaseNotes.md
  rdkit/Chem/EnumerateStereoisomers.py
  rdkit/Chem/RegistrationHash.py
  rdkit/Chem/UnitTestMol3D.py
  rdkit/Chem/UnitTestRegistrationHash.py
  rdkit/Chem/test_list.py
Labels: enhancement, changes results

#6063 Remove check for ring information from Atom::Match
  Code/GraphMol/Atom.cpp
  Code/GraphMol/Substruct/test1.cpp
Labels: bug

#6053 Improve MaeMolSupplier API
  Code/GraphMol/FileParsers/MaeMolSupplier.cpp
  Code/GraphMol/FileParsers/MolSupplier.h
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/test_data/benzene.mae
  Code/GraphMol/Wrap/CompressedSDMolSupplier.cpp
  Code/GraphMol/Wrap/MaeMolSupplier.cpp
  Code/GraphMol/Wrap/MolSupplier.h
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#6066 Correct docstring for minFontSize.
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
Labels: bug, documentation

#6081 Disable POPCNT on M1
  CMakeLists.txt
Labels: Cleanup, infrastructure

#6075 Expose some stereochemistry-related functions to SWIG wrappers
  Code/JavaWrappers/RWMol.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
Labels: enhancement

#6069 Start a Maestro file (.mae) writer.
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/MaeMolSupplier.cpp
  Code/GraphMol/FileParsers/MaeWriter.cpp
  Code/GraphMol/FileParsers/MolWriters.h
  Code/GraphMol/FileParsers/PDBWriter.cpp
  Code/GraphMol/FileParsers/SDWriter.cpp
  Code/GraphMol/FileParsers/SmilesWriter.cpp
  Code/GraphMol/FileParsers/TDTWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/Wrap/CMakeLists.txt
  Code/GraphMol/Wrap/MaeWriter.cpp
  Code/GraphMol/Wrap/PDBWriter.cpp
  Code/GraphMol/Wrap/SmilesWriter.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement, changes results

#6101 Minor code cleanup
  Code/MinimalLib/common.h
Labels: bug, Cleanup

#6096 Enable "smilesSymbol" substitution in SMARTS
  Code/GraphMol/SmilesParse/SmartsWrite.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: enhancement

#6090 Add option to only include shortest paths for topological torsion fingerprints
  Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.cpp
  Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.h
  Code/GraphMol/Fingerprints/Wrap/TopologicalTorsionWrapper.cpp
  Code/GraphMol/Fingerprints/Wrap/testGenerators.py
  Code/GraphMol/Fingerprints/catch_tests.cpp
  Code/GraphMol/Subgraphs/CMakeLists.txt
  Code/GraphMol/Subgraphs/Subgraphs.cpp
  Code/GraphMol/Subgraphs/Subgraphs.h
  Code/GraphMol/Subgraphs/catch_tests.cpp
  Code/GraphMol/Wrap/MolOps.cpp
Labels: enhancement

#6110 A few SWIG tweaks
  Code/JavaWrappers/Conformer.i
  Code/JavaWrappers/MolDraw2D.i
Labels: enhancement

#6109 Another minor code cleanup
  Code/MinimalLib/common.h
Labels: enhancement, Cleanup

#5991 Adds Pat Walter's Chembl Filters extraction to the FilterCatalog
  Code/GraphMol/FilterCatalog/FilterCatalog.h
  Code/GraphMol/FilterCatalog/Filters.cpp
  Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
  Code/GraphMol/FilterCatalog/Wrap/rough_test.py
  Code/GraphMol/FilterCatalog/brenk.in
  Code/GraphMol/FilterCatalog/chembl_bms.in
  Code/GraphMol/FilterCatalog/chembl_dundee.in
  Code/GraphMol/FilterCatalog/chembl_glaxo.in
  Code/GraphMol/FilterCatalog/chembl_inpharmatica.in
  Code/GraphMol/FilterCatalog/chembl_lint.in
  Code/GraphMol/FilterCatalog/chembl_mlsmr.in
  Code/GraphMol/FilterCatalog/chembl_surechembl.in
  Code/GraphMol/FilterCatalog/filtercatalogtest.cpp
  Code/GraphMol/FilterCatalog/nih.in
  Code/GraphMol/FilterCatalog/update_pains.py
  Code/GraphMol/FilterCatalog/zinc.in
Labels: enhancement

#6124 Remove spurious full stops from warnings.
  Code/GraphMol/Chirality.cpp
Labels: Cleanup

#5647 add molecular filter examples
  Docs/Book/GettingStartedInPython.rst
Labels: enhancement, documentation

#6129 The new Filters should have a FilterSet property
  Code/GraphMol/FilterCatalog/Filters.cpp
  Docs/Book/GettingStartedInPython.rst
Labels: bug, not in release notes

#6127 Stereochemistry-related SWIG updates
  Code/JavaWrappers/ROMol.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/ChemReactionTests.java
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
  ReleaseNotes.md
Labels: enhancement, changes results
