Repository rdkit/rdkit, pull requests merged in 2023-08, with the labels that each got.

#6332 Add a new parameter to mol_adjust_query_properties for generic query parameters
  Code/GraphMol/AdjustQuery.cpp
  Code/GraphMol/GenericGroups/GenericGroups.cpp
  Code/GraphMol/GenericGroups/GenericGroups.h
  Code/GraphMol/GenericGroups/generic_tests.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/Wrap/MolOps.cpp
  Code/PgSQL/rdkit/adapter.cpp
  Code/PgSQL/rdkit/expected/query.out
  Code/PgSQL/rdkit/mol_op.c
  Code/PgSQL/rdkit/rdkit.h
  Code/PgSQL/rdkit/rdkit_io.c
  Code/PgSQL/rdkit/sql/query.sql
  Docs/Book/Cartridge.md
Labels: enhancement

#6596 Add newline to ConstrainedEmbed docstring.
  Docs/Book/Cookbook.rst
  rdkit/Chem/AllChem.py
Labels: bug, documentation

#6579 Fix vulnerabilities found by fuzzer.
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/RWMol.cpp
Labels: bug

#6570 Support additional generic groups
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/GenericGroups/GenericGroups.cpp
  Code/GraphMol/GenericGroups/GenericGroups.h
  Code/GraphMol/GenericGroups/generic_tests.cpp
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/QueryOps.h
  Docs/Book/RDKit_Book.rst
Labels: enhancement

#6580 allow building the cartridge against PostgreSQL 16
  Code/PgSQL/rdkit/rdkit.h
Labels: bug

#6618 Fix some build warnings
  Code/ForceField/ForceField.cpp
  Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
  Code/GraphMol/ChemTransforms/testChemTransforms.cpp
  Code/GraphMol/Descriptors/PMI.h
  Code/GraphMol/FileParsers/MolWriters.h
  Code/GraphMol/GeneralizedSubstruct/catch_tests.cpp
  Code/GraphMol/MolBundle.h
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/RDBoost/python_streambuf.h
  Contrib/ConformerParser/test.cpp
Labels: enhancement, Cleanup

#6619 Fix bug in StereoGroup wrapper
  Code/GraphMol/Wrap/StereoGroup.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: bug, not in release notes

#6627 clear up some compiler warnings
  Code/GraphMol/Descriptors/MORSE.cpp
  Code/GraphMol/Descriptors/RDF.cpp
  Code/GraphMol/GenericGroups/GenericGroups.cpp
  Code/GraphMol/MolPickler.cpp
Labels: Cleanup

#6630 Avoid leaking memory in case exceptions are thrown while generating FPs
  Code/GraphMol/Fingerprints/MACCS.cpp
  Code/GraphMol/Fingerprints/MorganGenerator.cpp
  Code/GraphMol/Substruct/vf2.hpp
Labels: bug, Cleanup

#6581 Add a "rootedAtAtom" to MolToSmarts
  Code/GraphMol/Canon.cpp
  Code/GraphMol/Canon.h
  Code/GraphMol/SmilesParse/SmartsWrite.cpp
  Code/GraphMol/SmilesParse/SmartsWrite.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#6639 add option to use sequential random seeds in the conformer generator
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/EmbedderUtils.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
Labels: enhancement

#6393 Support TautomerQuery and MolBundle queries in the cartridge
  Code/GraphMol/GeneralizedSubstruct/CMakeLists.txt
  Code/GraphMol/GeneralizedSubstruct/Wrap/rdGeneralizedSubstruct.cpp
  Code/GraphMol/GeneralizedSubstruct/Wrap/testGeneralizedSubstruct.py
  Code/GraphMol/GeneralizedSubstruct/catch_tests.cpp
  Code/GraphMol/MolEnumerator/MolEnumerator.cpp
  Code/GraphMol/MolEnumerator/enumerator_catch.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.h
  Code/GraphMol/TautomerQuery/catch_tests.cpp
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/PgSQL/rdkit/adapter.cpp
  Code/PgSQL/rdkit/cache.c
  Code/PgSQL/rdkit/cache.h
  Code/PgSQL/rdkit/expected/rdkit-91.out
  Code/PgSQL/rdkit/expected/xqm.out
  Code/PgSQL/rdkit/mol_op.c
  Code/PgSQL/rdkit/rdkit.h
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/rdkit_io.c
  Code/PgSQL/rdkit/sql/rdkit-91.sql
  Code/PgSQL/rdkit/sql/xqm.sql
  Code/PgSQL/rdkit/update_sql/rdkit--4.3.0--4.4.0.sql.in
Labels: enhancement

#6646 Major MCS refactoring: new features and bug fixes
  Code/GraphMol/FMCS/Composition2N.h
  Code/GraphMol/FMCS/DebugTrace.h
  Code/GraphMol/FMCS/DuplicatedSeedCache.h
  Code/GraphMol/FMCS/FMCS.cpp
  Code/GraphMol/FMCS/FMCS.h
  Code/GraphMol/FMCS/Graph.h
  Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
  Code/GraphMol/FMCS/MaximumCommonSubgraph.h
  Code/GraphMol/FMCS/RingMatchTableSet.h
  Code/GraphMol/FMCS/Seed.cpp
  Code/GraphMol/FMCS/Seed.h
  Code/GraphMol/FMCS/SubstructMatchCustom.cpp
  Code/GraphMol/FMCS/SubstructureCache.h
  Code/GraphMol/FMCS/TargetMatch.h
  Code/GraphMol/FMCS/Test/testFMCS.cpp
  Code/GraphMol/FMCS/Wrap/rdFMCS.cpp
  Code/GraphMol/FMCS/Wrap/testFMCS.py
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/GraphMol/RingInfo.cpp
  Code/GraphMol/RingInfo.h
  Code/GraphMol/Wrap/RingInfo.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/Wrap/substructmethods.h
  Code/GraphMol/molopstest.cpp
  Docs/Book/GettingStartedInPython.rst
  ReleaseNotes.md
Labels: enhancement, Cleanup

#6662 switch from boost::any to std::any
  .azure-pipelines/linux_build_java.yml
  Code/DataStructs/DatastructsStreamOps.h
  Code/Demos/boost/any_container/Makefile
  Code/Demos/boost/any_container/dict.cpp
  Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
  Code/GraphMol/FileParsers/SDWriter.cpp
  Code/GraphMol/FilterCatalog/FilterCatalogEntry.h
  Code/GraphMol/MolInterchange/Writer.cpp
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/QueryOps.h
  Code/GraphMol/Wrap/props.hpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/test1.cpp
  Code/RDGeneral/RDAny.h
  Code/RDGeneral/RDValue-doublemagic.h
  Code/RDGeneral/RDValue-taggedunion.h
  Code/RDGeneral/RDValue.h
  Code/RDGeneral/testDict.cpp
  Code/RDGeneral/testRDValue.cpp
  Code/RDGeneral/types.h
  ReleaseNotes.md
  azure-pipelines.yml
Labels: Cleanup

#6568 RASCAL MCES
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/RascalMCES/CMakeLists.txt
  Code/GraphMol/RascalMCES/PartitionSet.cpp
  Code/GraphMol/RascalMCES/PartitionSet.h
  Code/GraphMol/RascalMCES/RascalButinaCluster.cpp
  Code/GraphMol/RascalMCES/RascalCluster.cpp
  Code/GraphMol/RascalMCES/RascalClusterOptions.h
  Code/GraphMol/RascalMCES/RascalDetails.h
  Code/GraphMol/RascalMCES/RascalMCES.cpp
  Code/GraphMol/RascalMCES/RascalMCES.h
  Code/GraphMol/RascalMCES/RascalOptions.h
  Code/GraphMol/RascalMCES/RascalResult.cpp
  Code/GraphMol/RascalMCES/RascalResult.h
  Code/GraphMol/RascalMCES/Wrap/CMakeLists.txt
  Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp
  Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py
  Code/GraphMol/RascalMCES/data/chembl_1907596.smi
  Code/GraphMol/RascalMCES/data/test_cluster1.smi
  Code/GraphMol/RascalMCES/lap_a_la_scipy.cpp
  Code/GraphMol/RascalMCES/mces_catch.cpp
  Code/GraphMol/RascalMCES/mces_cluster_catch.cpp
  Docs/Book/GettingStartedInPython.rst
  Docs/Book/images/mcs_example_1.png
  Docs/Book/images/mcs_example_2.png
  Docs/Book/images/mcs_example_3.png
  Docs/Book/images/mcs_example_4.png
  Docs/Book/images/mcs_example_5.png
  Docs/Book/images/mcs_example_6.png
Labels: enhancement

#6674 Expose RascalMCES singleLargestFrag option to Python.
  Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp
  Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py
Labels: enhancement, not in release notes

#6653 Lasso highlights
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/GraphMol/MolDraw2D/DrawMolMCH.cpp
  Code/GraphMol/MolDraw2D/DrawMolMCH.h
  Code/GraphMol/MolDraw2D/DrawMolMCHCircleAndLine.cpp
  Code/GraphMol/MolDraw2D/DrawMolMCHCircleAndLine.h
  Code/GraphMol/MolDraw2D/DrawMolMCHLasso.cpp
  Code/GraphMol/MolDraw2D/DrawMolMCHLasso.h
  Code/GraphMol/MolDraw2D/DrawShape.h
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.h
  Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: enhancement

#6669 Fix a bunch of edge cases in the pseudo 3d chiral assignment code.
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
  Code/GraphMol/FileParsers/molfile_stereo_catch.cpp
  Code/GraphMol/catch_chirality.cpp
  rdkit/Chem/UnitTestInchi.py
Labels: bug, not in release notes
