Repository rdkit/rdkit, pull requests merged in 2023-09, with the labels that each got.

#6675 Fail CI builds on compiler warnings + some fixes
  .azure-pipelines/linux_build.yml
  .azure-pipelines/mac_build.yml
  Code/GraphMol/ChemReactions/Enumerate/Enumerate.cpp
  Code/GraphMol/ChemTransforms/MolFragmenter.cpp
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/Descriptors/AUTOCORR3D.cpp
  Code/GraphMol/DetermineBonds/DetermineBonds.cpp
  Code/GraphMol/DetermineBonds/README.md
  Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/GeneralizedSubstruct/TextIO.cpp
  Code/GraphMol/GeneralizedSubstruct/Wrap/rdGeneralizedSubstruct.cpp
  Code/GraphMol/MarvinParse/MarvinDefs.cpp
  Code/GraphMol/MarvinParse/MarvinDefs.h
  Code/GraphMol/MarvinParse/MarvinWriter.cpp
  Code/GraphMol/MolDraw2D/DrawMolMCHLasso.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/RascalMCES/RascalDetails.h
  Code/GraphMol/RascalMCES/RascalMCES.cpp
  Code/GraphMol/RascalMCES/RascalOptions.h
  Code/GraphMol/RascalMCES/RascalResult.cpp
  Code/GraphMol/RascalMCES/RascalResult.h
  Code/GraphMol/RascalMCES/lap_a_la_scipy.cpp
  Code/GraphMol/RascalMCES/mces_catch.cpp
  Code/GraphMol/RascalMCES/mces_cluster_catch.cpp
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/catch_organometallics.cpp
  Code/RDGeneral/BoostStartInclude.h
  Contrib/ChiralPairs/ChiralDescriptors.py
Labels: Cleanup, infrastructure

#6684 fix some more leaks
  Code/GraphMol/Depictor/testDepictor.cpp
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolStandardize/test1.cpp
Labels: Cleanup

#6680 mol_to_xqmol should not be doing adjustqueryprops by default in the cartridge
  Code/PgSQL/rdkit/expected/xqm.out
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/sql/xqm.sql
  Code/PgSQL/rdkit/update_sql/rdkit--4.3.0--4.4.0.sql.in
Labels: bug, not in release notes

#6698 make sure bond attachpt info is pickled
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/catch_pickles.cpp
  Code/PgSQL/rdkit/adapter.cpp
  Code/PgSQL/rdkit/expected/rdkit-91.out
  Code/PgSQL/rdkit/expected/xqm.out
  Code/PgSQL/rdkit/sql/rdkit-91.sql
  Code/PgSQL/rdkit/sql/xqm.sql
Labels: bug

#6690 fix order of cleanupOrganometallics() in sanitizeMol()
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: bug, not in release notes

#6678 make MolsMatrixToGridImage() work in notebook
  rdkit/Chem/Draw/UnitTestIPython.py
  rdkit/Chem/Draw/__init__.py
Labels: bug, not in release notes

#6700 expose the CDXML reaction parsers to python
  Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
  Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
Labels: enhancement

#6696 Allow some tolerance in flatness determination
  Code/GraphMol/Conformer.h
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/molfile_stereo_catch.cpp
Labels: enhancement

#6697 Do not trust the 2D/3D tag in ctab mol files
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
Labels: enhancement

#6702 Add hasQueryHs
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/molopstest.cpp
  Code/JavaWrappers/MolOps.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/MolQueryTests.java
Labels: enhancement

#6676 extract continuous lines from the conrec code
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.h
  Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/Numerics/Conrec.h
  Code/Numerics/testConrec.cpp
Labels: enhancement

#6707 add missing Python parameter and reformat
  Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
Labels: bug, not in release notes

#6712 Fixes failing flexicanvas JS test
  Code/MinimalLib/tests/tests.js
Labels: bug, not in release notes

#6717 remove incorrect comment
  Code/GraphMol/FileParsers/MolFileParser.cpp
Labels: documentation, not in release notes

#6734 Update README.md for newest RDKit UGMs
  README.md
Labels: documentation

#6709 Add trans layout for double bonds in rings
  Code/GraphMol/Depictor/DepictUtils.cpp
  Code/GraphMol/Depictor/DepictUtils.h
  Code/GraphMol/Depictor/EmbeddedFrag.cpp
  Code/GraphMol/Depictor/catch_tests.cpp
Labels: bug

#6740 Use the connect-the-dots algorithm by default in DetermineBonds
  Code/GraphMol/DetermineBonds/CMakeLists.txt
  Code/GraphMol/DetermineBonds/DetermineBonds.cpp
  Code/GraphMol/DetermineBonds/DetermineBonds.h
  Code/GraphMol/DetermineBonds/Wrap/rdDetermineBonds.cpp
  Code/GraphMol/DetermineBonds/Wrap/testDetermineBonds.py
  Code/GraphMol/DetermineBonds/catch_tests.cpp
  ReleaseNotes.md
Labels: enhancement, changes results

#6748 add to projects using RDKit section
  README.md
Labels: documentation

#6754 Extract the core matching logic into a separate function
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
  Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
  Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
  Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
Labels: enhancement
