Repository rdkit/rdkit, pull requests merged in 2023-06, with the labels that each got.

#6407 JS: Implement in-place aromatisation/kekulisation and avoid undesired exception
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#6431 Enable using JSSubstructLibrary without pattern fps
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#6409 Optionally expose MCS to JS and extend optional compilation to JSReaction and JSSubstructLibrary
  CMakeLists.txt
  Code/GraphMol/FMCS/FMCS.cpp
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
  ReleaseNotes.md
Labels: enhancement, changes results, infrastructure

#6392 Deprecate JSMol::is_valid() and JSReaction::is_valid() and return nullptr instead
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
  ReleaseNotes.md
Labels: deprecation, Cleanup, API-change

#6449 misc jswrapper.cpp cleanup
  Code/MinimalLib/jswrapper.cpp
Labels: Cleanup

#6473 Allow systems like C/C=N/[H] to be stereogenic with the new chirality code
  Code/GraphMol/FindStereo.cpp
  Code/GraphMol/catch_chirality.cpp
Labels: bug

#6443 Add support for generalized substructure searching
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/GeneralizedSubstruct/CMakeLists.txt
  Code/GraphMol/GeneralizedSubstruct/TextIO.cpp
  Code/GraphMol/GeneralizedSubstruct/Wrap/CMakeLists.txt
  Code/GraphMol/GeneralizedSubstruct/Wrap/rdGeneralizedSubstruct.cpp
  Code/GraphMol/GeneralizedSubstruct/Wrap/testGeneralizedSubstruct.py
  Code/GraphMol/GeneralizedSubstruct/XQMol.cpp
  Code/GraphMol/GeneralizedSubstruct/XQMol.h
  Code/GraphMol/GeneralizedSubstruct/catch_tests.cpp
  Code/GraphMol/MolBundle.h
  Code/GraphMol/Wrap/MolBundle.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/catch_molbundle.cpp
Labels: enhancement

#6483 pin numpy to 1.24.3
  .azure-pipelines/linux_build_py311.yml
Labels: bug, infrastructure

#6486 Fixed tests that weren't being run in testDepictor.py
  Code/GraphMol/Depictor/Wrap/testDepictor.py
Labels: bug

#6488 Replace a try..catch block with an if clause
  Code/GraphMol/FMCS/FMCS.cpp
Labels: enhancement, Cleanup

#6490 Fixes rdkit-js/issues/347
  CMakeLists.txt
  Code/MinimalLib/docker/Dockerfile
  Code/MinimalLib/docker/Dockerfile_legacy_browsers
Labels: bug, infrastructure

#6487 Get tests to work when building without exception support (i.e., legacy pure JS library)
  Code/MinimalLib/tests/tests.js
Labels: bug
