Repository rdkit/rdkit, pull requests merged in 2023-04, with the labels that each got.

#6266 Fix oxidation numbers calculation
  Code/GraphMol/Descriptors/OxidationNumbers.cpp
  Code/GraphMol/Descriptors/OxidationNumbers.h
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/Descriptors/catch_tests.cpp
  Code/GraphMol/MolStandardize/test_data/MOL_00104.mol
Labels: bug, not in release notes

#6272 deal with deprecated DataFrame.append method
  rdkit/Chem/PandasTools.py
Labels: bug, Cleanup

#6271 Fix incorrect bond check in #6266
  Code/GraphMol/Descriptors/OxidationNumbers.cpp
Labels: bug, not in release notes

#6270 Update assignSubstructureFilters.py
  Contrib/NIBRSubstructureFilters/assignSubstructureFilters.py
Labels: bug, contrib

#6269 Add support for generic matching in the PgSQL cartridge
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/PgSQL/rdkit/adapter.cpp
  Code/PgSQL/rdkit/expected/query.out
  Code/PgSQL/rdkit/guc.c
  Code/PgSQL/rdkit/mol_op.c
  Code/PgSQL/rdkit/rdkit.control
  Code/PgSQL/rdkit/rdkit.h
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/sql/query.sql
  Code/PgSQL/rdkit/update_sql/rdkit--4.2.0--4.3.0.sql.in
Labels: enhancement

#6280 allowOptionalAttachments should also include terminal query atoms matching hydrogen
  Code/GraphMol/Depictor/RDDepictor.cpp
  Code/GraphMol/Depictor/testDepictor.cpp
  Code/GraphMol/Substruct/SubstructUtils.cpp
  Code/GraphMol/Substruct/SubstructUtils.h
  Code/GraphMol/Substruct/test1.cpp
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/common.h
Labels: enhancement

#6282 Exposed queryColour in MolDrawOptions
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#6292 remove cleanupOrganometallics() from the default sanitization
  Code/GraphMol/FileParsers/test1.cpp
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/MolOps.h
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/catch_graphmol.cpp
  Docs/Book/RDKit_Book.rst
Labels: bug, not in release notes

#6259 Using Chiral Tag instead of CIPCode to ensure preservation of chirality in addHs
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: bug

#5749 Expose RDLog to SWIG wrappers
  Code/JavaWrappers/RDLogger.i
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
  Code/RDGeneral/RDLog.h
  Code/RDGeneral/catch_logs.cpp
Labels: enhancement

#6293 release prep
  CMakeLists.txt
  Docs/Book/conf.py
  ReleaseNotes.md
Labels: infrastructure

#6273 Add option to specify ring system templates for 2D coordinate generation
  Code/GraphMol/Depictor/CMakeLists.txt
  Code/GraphMol/Depictor/RDDepictor.cpp
  Code/GraphMol/Depictor/RDDepictor.h
  Code/GraphMol/Depictor/Templates.cpp
  Code/GraphMol/Depictor/Templates.h
  Code/GraphMol/Depictor/Wrap/rdDepictor.cpp
  Code/GraphMol/Depictor/Wrap/testDepictor.py
  Code/GraphMol/Depictor/testDepictor.cpp
  Code/GraphMol/Depictor/test_data/ring_system_templates.smi
Labels: enhancement, not in release notes

#6297 has_coords() now reports whether coords are 2D or 3D if present
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#6298 Improve the installation/testing instructions for linux/conda
  Docs/Book/Install.md
Labels: enhancement, documentation

#6299 Fix UnitTestPandasTools for running without pandas installed.
  .gitignore
  rdkit/Chem/UnitTestPandasTools.py
Labels: enhancement, Cleanup

#6303 Aromatic dashes look bad
  Code/GraphMol/MolDraw2D/DrawShape.h
Labels: bug

#6289 Add a new tautomer mol hash
  Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
  Code/GraphMol/MolHash/Wrap/rdMolHash.cpp
  Code/GraphMol/MolHash/Wrap/testMolHash.py
  Code/GraphMol/MolHash/catch_tests.cpp
  Code/GraphMol/MolHash/hashfunctions.cpp
  Code/GraphMol/MolHash/nmmolhash.h
  Code/PgSQL/rdkit/adapter.cpp
  Docs/Book/Cookbook.rst
  rdkit/Chem/RegistrationHash.py
  rdkit/Chem/UnitTestRegistrationHash.py
Labels: enhancement

#6319 rename database update script added in #6269
  Code/PgSQL/rdkit/update_sql/rdkit--4.2--4.3.0.sql.in
Labels: bug, not in release notes

#6324 Infrastructure updates for 2023.03 release
  CMakeLists.txt
  Docs/Book/conf.py
  ReleaseNotes.md
Labels: infrastructure, not in release notes

#6325 another attempt to get the windows ci builds working
  .azure-pipelines/vs_build.yml
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#6326 add SmilesParse as dependency to Depictor
  Code/GraphMol/Depictor/CMakeLists.txt
Labels: Cleanup, not in release notes
