Repository rdkit/rdkit, pull requests merged in 2024-10, with the labels that each got.

#7863 Current master identifies as 2023.03.1pre
  CMakeLists.txt
Labels: infrastructure, not in release notes

#7826 Simple speed up for CIPLabeler
  Code/GraphMol/CIPLabeler/Digraph.cpp
Labels: enhancement

#7882 [CI]: temporarily be explicit about using the macos-12 image
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#7883 Use smart pointer for buffer.
  Code/RDGeneral/StreamOps.h
Labels: Cleanup

#7867 Fix some mem errors in 2024.09.1
  Code/GraphMol/CIPLabeler/catch_tests.cpp
  Code/GraphMol/ChemTransforms/MolFragmenter.cpp
  Code/GraphMol/DetermineBonds/catch_tests.cpp
  Code/GraphMol/FileParsers/PDBParser.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/molfile_stereo_catch.cpp
  Code/GraphMol/FileParsers/testMolWriter.cpp
  Code/GraphMol/FileParsers/v2_suppliers_catch.cpp
  Code/GraphMol/Fingerprints/catch_tests.cpp
  Code/GraphMol/MolEnumerator/enumerator_catch.cpp
  Code/GraphMol/MolInterchange/Parser.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/test1.cpp
  External/INCHI-API/inchi.cpp
Labels: Cleanup

#7895 Expose three ROMol methods which were not previously exposed to SWIG wrappers
  Code/JavaWrappers/ROMol.i
Labels: enhancement

#7862 Improve Morgan Fingerprint Performance
  Code/GraphMol/Fingerprints/MorganGenerator.cpp
Labels: enhancement, optimization

#7884 Modernise ExplicitBitVect.
  Code/DataStructs/BitOps.cpp
  Code/DataStructs/ExplicitBitVect.cpp
  Code/DataStructs/ExplicitBitVect.h
Labels: Cleanup

#7854 Another 2x performance improvement in CIP labelling
  Code/GraphMol/CIPLabeler/CIPMol.cpp
  Code/GraphMol/CIPLabeler/CIPMol.h
Labels: enhancement, optimization

#7900 Update `PUBCHEMSHAPE_URL` and remove patch code
  External/pubchem_shape/CMakeLists.txt
Labels: Cleanup

#7853 Expose preset color palettes to MinimalLib through JSON
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#7899 Fix some more mem errors in 2024.09.1
  Code/DistGeom/Wrap/DistGeom.cpp
  Code/ForceField/Wrap/ForceField.cpp
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp
  Code/GraphMol/Fingerprints/MorganGenerator.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/Builder.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/MMFF.h
  Code/GraphMol/ForceFieldHelpers/UFF/Builder.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/UFF.h
  Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp
  Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp
  Code/GraphMol/MolCatalog/Wrap/rdMolCatalog.cpp
  Code/GraphMol/MolProcessing/Wrap/rdMolProcessing.cpp
  Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp
  Code/GraphMol/Wrap/CompressedSDMolSupplier.cpp
  Code/Numerics/Alignment/Wrap/rdAlignment.cpp
Labels: bug, Cleanup

#7834 Additional compatibility updates for commutator/negator settings for …
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/PgSQL/rdkit/rdkit.control
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/update_sql/rdkit--4.6.0--4.6.1.sql.in
Labels: enhancement

#7910 Do the announced deprecations
  Code/DistGeom/CMakeLists.txt
  Code/DistGeom/ChiralViolationContrib.cpp
  Code/DistGeom/ChiralViolationContrib.h
  Code/DistGeom/ChiralViolationContribs.cpp
  Code/DistGeom/ChiralViolationContribs.h
  Code/DistGeom/DistViolationContrib.cpp
  Code/DistGeom/DistViolationContrib.h
  Code/DistGeom/FourthDimContrib.h
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.h
  ReleaseNotes.md
  rdkit/Chem/AtomPairs/Utils.py
Labels: Cleanup, not in release notes

#7892 Optimize Butina Clustering for Performance and Expand API
  rdkit/ML/Cluster/Butina.py
  rdkit/ML/Cluster/UnitTestButina.py
Labels: enhancement, optimization

#7920 auto-close stale issues and PRs
  .github/workflows/close_stale_issues.yml
Labels: infrastructure, not in release notes

#7881 FindPython Development.Module instead of Development
  CMakeLists.txt
  External/pubchem_shape/Wrap/CMakeLists.txt
Labels: Cleanup

#7925 Update close_stale_issues.yml
  .github/workflows/close_stale_issues.yml
Labels: infrastructure, not in release notes

#7137 Fixes #7044
  Code/GraphMol/Canon.cpp
  Code/GraphMol/MolStandardize/testTautomer.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: stale

#7933 Documentation updates
  Code/GraphMol/MolOps.h
  Docs/Book/source/rdkit.Chem.rdShapeAlign.rst
  Docs/Book/source/rdkit.Chem.rst
  External/pubchem_shape/PubChemShape.hpp
  External/pubchem_shape/Wrap/cshapealign.cpp
Labels: documentation

#6777 Improved handling of SP/TB/OH reording in SMILES/SMARTS.
  Code/GraphMol/Canon.cpp
  Code/GraphMol/Chirality.h
  Code/GraphMol/Depictor/catch_tests.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/NontetrahedralStereo.cpp
  Code/GraphMol/SmilesParse/SmilesParseOps.cpp
  Code/GraphMol/SmilesParse/nontetrahedral_tests.cpp
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: enhancement

#7939 Add to Cookbook "Include a Bond Index" recipe and image
  Docs/Book/Cookbook.rst
  Docs/Book/images/RDKitCB_40_im0.png
  Docs/Book/images/RDKitCB_40_im1.png
Labels: enhancement, documentation

#7838 Support Writing CX Extensions for Reactions
  Code/GraphMol/ChemReactions/ReactionParser.h
  Code/GraphMol/ChemReactions/ReactionWriter.cpp
  Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
  Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
  Code/GraphMol/ChemReactions/catch_tests.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: enhancement

#7774 Fix 4.3.0--4.4.0 sql upgrade script
  Code/PgSQL/rdkit/update_sql/rdkit--4.3.0--4.4.0.sql.in
Labels: bug

#7924 ... and more mem errors fixed
  Code/GraphMol/CIPLabeler/catch_tests.cpp
  Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/PDBWriter.cpp
  Code/GraphMol/Wrap/SDWriter.cpp
  Code/GraphMol/Wrap/SmilesWriter.cpp
  Code/GraphMol/Wrap/TDTWriter.cpp
  Code/ML/Cluster/Murtagh/Clustering.cpp
  Code/RDBoost/python_streambuf.h
Labels: Cleanup

#7913 Replace awful enum reflection macros with Better Enums
  CMakeLists.txt
  Code/GraphMol/RGroupDecomposition/CMakeLists.txt
  Code/GraphMol/RGroupDecomposition/RGroupDecompJSONParsers.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecompJSONParsers.h
  Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecompParams.h
  Code/GraphMol/SmilesParse/CMakeLists.txt
  Code/GraphMol/SmilesParse/SmilesJSONParsers.cpp
  Code/GraphMol/SmilesParse/SmilesJSONParsers.h
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/JavaWrappers/RGroupDecomposition.i
  Code/JavaWrappers/SmilesWrite.i
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/RDGeneral/BetterEnums.h
  Code/RDGeneral/CMakeLists.txt
  ReleaseNotes.md
Labels: Cleanup, API-change

#7964 Need to reserve space before assignment
  Code/GraphMol/Chirality.cpp
Labels: bug

#7943 One final round of mem errors
  Code/DataManip/MetricMatrixCalc/Wrap/rdMetricMatrixCalc.cpp
  Code/ForceField/ForceField.cpp
  Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp
  Code/GraphMol/Descriptors/Property.cpp
  Code/GraphMol/Descriptors/Property.h
  Code/GraphMol/Descriptors/RegisterDescriptor.h
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
  Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
  Code/Numerics/Optimizer/BFGSOpt.h
  Code/SimDivPickers/MaxMinPicker.h
  Code/SimDivPickers/Wrap/MaxMinPicker.cpp
Labels: Cleanup

#7972 Fixes a regression introduced in #7582 which made all SWIG enums become type-unsafe
  Code/JavaWrappers/MolStandardize.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/MolStandardizeTest.java
Labels: bug, Cleanup

#7938 Remove deprecation warnings by switching MinimalLib to fingerprint generators
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/common.h
Labels: Cleanup

#7968 Move CI builds to macos-14
  .azure-pipelines/mac_build.yml
  .azure-pipelines/mac_build_java.yml
  azure-pipelines.yml
Labels: infrastructure
