Repository rdkit/rdkit, pull requests merged in 2024-09, with the labels that each got.

#7719 Speed up boost vector iterators
  rdkit/__init__.py
Labels: enhancement

#7786 HasPropWithValueQueryBase needs a virtual destructor
  Code/GraphMol/QueryOps.h
Labels: bug, not in release notes

#7798 Provide an RDKit wrapper around pubchem-align3d
  .azure-pipelines/linux_build_limitexternal.yml
  CMakeLists.txt
  External/CMakeLists.txt
  External/pubchem_shape/CMakeLists.txt
  External/pubchem_shape/PubChemShape.cpp
  External/pubchem_shape/PubChemShape.hpp
  External/pubchem_shape/README.md
  External/pubchem_shape/Wrap/CMakeLists.txt
  External/pubchem_shape/Wrap/cshapealign.cpp
  External/pubchem_shape/Wrap/test_rdshapealign.py
  External/pubchem_shape/sdf_align.cpp
  External/pubchem_shape/test.cpp
  External/pubchem_shape/test_data/align_with_hs.sdf
  External/pubchem_shape/test_data/bulk.pubchem.sdf
  External/pubchem_shape/test_data/test1.sdf
Labels: enhancement

#7673 Rascal match exact atom type
  Code/GraphMol/RascalMCES/RascalMCES.cpp
  Code/GraphMol/RascalMCES/RascalOptions.h
  Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp
  Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py
  Code/GraphMol/RascalMCES/mces_catch.cpp
Labels: enhancement

#7817 Avoid pubchem-align3d build failure on g++ >=13
  External/pubchem_shape/CMakeLists.txt
Labels: infrastructure, not in release notes

#7801 Fix typo (Fingeprint -> Fingerprint)
  Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
Labels: enhancement

#7322 Enable RGD highlights as in blog post
  Code/GraphMol/RGroupDecomposition/RGroupData.cpp
  Code/GraphMol/RGroupDecomposition/RGroupData.h
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
  Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecompParams.h
  Code/GraphMol/RGroupDecomposition/RGroupMatch.h
  Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
  Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
  Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/demo/rgd_demo.html
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
Labels: enhancement

#7805 A couple of fixes to the InteractiveRenderer Jupyter integration
  rdkit/Chem/Draw/InteractiveRenderer.py
Labels: bug

#7804 Drop mol_hash for legacy databases to enable upgrade to recent versions
  Code/PgSQL/rdkit/update_sql/rdkit--3.8--4.0.sql.in
Labels: bug, Cleanup

#7795 Update SA score to use FingerprintGenerators
  Contrib/SA_Score/sascorer.py
Labels: Cleanup

#7765 Expose MMFF aromaticity model for SetAromaticity
  Code/GraphMol/Aromaticity.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.h
  Code/GraphMol/MolOps.h
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/molopstest.cpp
  ReleaseNotes.md
Labels: enhancement

#7835 Rename MolProcessing header
  Code/GraphMol/MolProcessing/MolProcessing.cpp
  Code/GraphMol/MolProcessing/MolProcessing.h
  Code/GraphMol/MolProcessing/Wrap/rdMolProcessing.cpp
  Code/GraphMol/MolProcessing/processing_tests.cpp
Labels: not in release notes

#7836 beta release prep
  CMakeLists.txt
  ReleaseNotes.md
Labels: not in release notes

#7831 massive simplification of README.md
  CMakeLists.txt
  README
  README.md
Labels: documentation

#7855 Final prep for 2024.09.1 release
  CMakeLists.txt
  ReleaseNotes.md
Labels: infrastructure, not in release notes

#7858 ready next release cycle
  CMakeLists.txt
  Docs/Book/conf.py
  ReleaseNotes.md
Labels: infrastructure, not in release notes
