Repository rdkit/rdkit, pull requests merged in 2024-07, with the labels that each got.

#7571 Add atom map number to complex query atom symbol.
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: enhancement

#7584 Speed up GetPropsAsDict(), especially on Mac
  Code/GraphMol/Wrap/props.hpp
Labels: enhancement

#7433 Geometry
  Code/ForceField/MMFF/Params.h
  Code/Geometry/GridUtils.cpp
  Code/Geometry/Transform2D.cpp
  Code/Geometry/Transform2D.h
  Code/Geometry/Transform3D.cpp
  Code/Geometry/Transform3D.h
  Code/Geometry/UniformGrid3D.cpp
  Code/Geometry/point.h
  Code/Geometry/testTransforms.cpp
Labels: Cleanup

#7535 Fix/kminimization
  Code/DistGeom/DistGeomUtils.cpp
  Code/DistGeom/DistGeomUtils.h
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/DistGeomHelpers/test_data/chirality_failure_test.mol
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.etdg.mol
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.etkdg.mol
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.kdg.mol
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.macrocycle.etkdg.mol
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.macrocycle.etkdgv3.mol
  Code/GraphMol/DistGeomHelpers/test_data/simple_torsion.smallring.etkdgv3.mol
  Code/GraphMol/DistGeomHelpers/test_data/torsion.etkdg.v2.mol
  Docs/Book/GettingStartedInPython.rst
  rdkit/Chem/UnitTestDescriptors.py
Labels: bug, enhancement, Cleanup

#7589 Don't register FilterMatcherBase twice
  Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
Labels: bug

#7286 Improve PDB formatting with incomplete Monomer info
  Code/GraphMol/FileParsers/PDBWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
Labels: bug

#7600 Optimizations of the DistanceGeometry forcefield
  Code/DistGeom/CMakeLists.txt
  Code/DistGeom/ChiralViolationContrib.cpp
  Code/DistGeom/ChiralViolationContrib.h
  Code/DistGeom/ChiralViolationContribs.cpp
  Code/DistGeom/ChiralViolationContribs.h
  Code/DistGeom/DistGeomUtils.cpp
  Code/DistGeom/DistViolationContrib.h
  Code/DistGeom/DistViolationContribs.cpp
  Code/DistGeom/DistViolationContribs.h
  Code/DistGeom/FourthDimContrib.h
  Code/DistGeom/FourthDimContribs.h
  Code/ForceField/ForceField.cpp
  Code/ForceField/ForceField.h
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/DistGeomHelpers/test_data/initCoords.random.sdf
  ReleaseNotes.md
Labels: enhancement, optimization

#7648 fix(rdmolfiles): fix parameters and docstrings
  Code/GraphMol/Wrap/rdmolfiles.cpp
Labels: documentation, Cleanup

#7596 Update commutator/negator settings for operator @=
  Code/PgSQL/rdkit/CMakeLists.txt
  Code/PgSQL/rdkit/rdkit.control
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/update_sql/rdkit--4.5.0--4.6.0.sql.in
Labels: bug

#7547 Update rdkit_gist.c fixes #7493
  Code/PgSQL/rdkit/rdkit_gist.c
Labels: enhancement

#7647 MinimalLib: fix misformatted molblock and make sure unit test is actually executed
  Code/MinimalLib/common_defs.h
  Code/MinimalLib/tests/tests.js
Labels: bug

#7638 Fix parsing RBCNT from mol files, and add exporting it
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
Labels: bug

#7652 Refactor distgeom minimizations
  Code/DistGeom/DistGeomUtils.cpp
  Code/DistGeom/DistGeomUtils.h
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
Labels: Cleanup

#7667 Fix some missing headers when doing "make install"
  Code/DistGeom/CMakeLists.txt
  Code/GraphMol/CIPLabeler/CMakeLists.txt
  Code/GraphMol/MarvinParse/CMakeLists.txt
  Code/GraphMol/MarvinParse/MarvinDefs.h
  Code/RDBoost/CMakeLists.txt
Labels: Cleanup

#7582 Extend RDKit::MolStandardize with a validation and standardization Pipeline
  .azure-pipelines/linux_build_java.yml
  .azure-pipelines/mac_build_java.yml
  .azure-pipelines/vs_build_swig.yml
  .clang-format
  Code/GraphMol/MolStandardize/CMakeLists.txt
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/Pipeline.cpp
  Code/GraphMol/MolStandardize/Pipeline.h
  Code/GraphMol/MolStandardize/Validate.cpp
  Code/GraphMol/MolStandardize/Validate.h
  Code/GraphMol/MolStandardize/Wrap/CMakeLists.txt
  Code/GraphMol/MolStandardize/Wrap/Pipeline.cpp
  Code/GraphMol/MolStandardize/Wrap/Validate.cpp
  Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/testPipeline.cpp
  Code/GraphMol/MolStandardize/testValidate.cpp
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/MolStandardize.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/MolStandardizeTest.java
Labels: enhancement
