Repository rdkit/rdkit, pull requests merged in 2024-08, with the labels that each got.

#7688 Make sure angleconstraints only take angles between 0 and 180 degrees.
  Code/ForceField/AngleConstraint.cpp
  Code/ForceField/AngleConstraint.h
  Code/ForceField/CMakeLists.txt
  Code/ForceField/MMFF/AngleConstraint.h
  Code/ForceField/MMFF/Params.h
  Code/ForceField/MMFF/testMMFFForceField.cpp
  Code/ForceField/UFF/AngleConstraint.cpp
  Code/ForceField/UFF/AngleConstraint.h
  Code/ForceField/UFF/Params.h
  Code/ForceField/UFF/testUFFForceField.cpp
  Code/ForceField/Wrap/testConstraints.py
Labels: bug, Cleanup

#7698 Add support for building the CFFI lib without InChI
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/common.h
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
Labels: enhancement

#7706 Only test InChI functionality if it was built into JS MinimalLib
  Code/MinimalLib/tests/tests.js
Labels: Cleanup, not in release notes

#7700 Remove Descriptors as a dependency of many other RDKit libraries
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/ChemReactions/CMakeLists.txt
  Code/GraphMol/ChemReactions/Reaction.cpp
  Code/GraphMol/ChemReactions/ReactionRunner.cpp
  Code/GraphMol/ChemReactions/ReactionUtils.cpp
  Code/GraphMol/Deprotect/CMakeLists.txt
  Code/GraphMol/Descriptors/MolDescriptors.cpp
  Code/GraphMol/MolAlign/CMakeLists.txt
  Code/GraphMol/MolAlign/Wrap/CMakeLists.txt
  Code/GraphMol/MolHash/CMakeLists.txt
  Code/GraphMol/MolOps.h
  Code/GraphMol/MolProps.cpp
  Code/GraphMol/MolStandardize/CMakeLists.txt
  Code/GraphMol/MolStandardize/Fragment.cpp
  Code/GraphMol/StructChecker/CMakeLists.txt
  Code/GraphMol/StructChecker/StripSmallFragments.cpp
  Code/GraphMol/catch_molops.cpp
  Code/MinimalLib/CMakeLists.txt
  Code/PgSQL/rdkit/adapter.cpp
  External/INCHI-API/CMakeLists.txt
  External/INCHI-API/test.cpp
Labels: Cleanup

#7721 doc: fix -Wdocumentation-html
  Code/GraphMol/Fingerprints/MHFP.h
  Code/Numerics/Alignment/AlignPoints.cpp
  Code/RDGeneral/Dict.h
Labels: documentation, Cleanup

#7720 Some cmake cleanup work
  .azure-pipelines/linux_build_py37.yml
  .azure-pipelines/vs_build.yml
  .azure-pipelines/vs_build_dll.yml
  CMakeLists.txt
  Code/GraphMol/FilterCatalog/CMakeLists.txt
  Code/GraphMol/RGroupDecomposition/CMakeLists.txt
  Code/cmake/Modules/CodeCoverage.cmake
  Code/cmake/Modules/RDKitUtils.cmake
  External/CoordGen/CMakeLists.txt
  Projects/DbCLI/UnitTestDbCLI.py
  azure-pipelines.yml
  rdkit-stubs/CMakeLists.txt
Labels: Cleanup, infrastructure

#7734 Restore the ability to build RDKit_minimal.js after #7700
  Code/MinimalLib/CMakeLists.txt
Labels: bug, not in release notes

#7715 Reduce code duplication in ff
  Code/ForceField/AngleConstraint.cpp
  Code/ForceField/AngleConstraint.h
  Code/ForceField/CMakeLists.txt
  Code/ForceField/DistanceConstraint.cpp
  Code/ForceField/DistanceConstraint.h
  Code/ForceField/MMFF/AngleConstraint.h
  Code/ForceField/MMFF/DistanceConstraint.cpp
  Code/ForceField/MMFF/DistanceConstraint.h
  Code/ForceField/MMFF/PositionConstraint.h
  Code/ForceField/MMFF/TorsionConstraint.cpp
  Code/ForceField/MMFF/TorsionConstraint.h
  Code/ForceField/PositionConstraint.cpp
  Code/ForceField/PositionConstraint.h
  Code/ForceField/TorsionConstraint.cpp
  Code/ForceField/TorsionConstraint.h
  Code/ForceField/UFF/AngleConstraint.h
  Code/ForceField/UFF/DistanceConstraint.h
  Code/ForceField/UFF/PositionConstraint.cpp
  Code/ForceField/UFF/PositionConstraint.h
  Code/ForceField/UFF/TorsionConstraint.h
Labels: Cleanup

#7743 Expose two additional boolean flags for mol creation to MinimalLib
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/common.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#7732 Allow atom map numbers to be ignored when generating canonical SMILES
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#7749 Fix vectToString such that it outputs valid JSON
  Code/RDGeneral/RDValue.h
  Code/RDGeneral/testDict.cpp
Labels: enhancement

#7692 Adds HasPropWithValue Pickler
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/MolPickler.h
  Code/GraphMol/QueryOps.cpp
  Code/GraphMol/QueryOps.h
  Code/GraphMol/Substruct/catch_tests.cpp
  Code/GraphMol/catch_pickles.cpp
Labels: enhancement

#7775 Fix typo in 4.5.0--4.6.0 sql upgrade script
  Code/PgSQL/rdkit/update_sql/rdkit--4.5.0--4.6.0.sql.in
Labels: bug

#7778 Fix issue in #7720
  CMakeLists.txt
Labels: bug, infrastructure
