Repository rdkit/rdkit, pull requests merged in 2024-04, with the labels that each got.

#7316 re-enable yaehmop support in DetermineBonds
  CMakeLists.txt
Labels: bug

#7325 Make ctest run installed tests if RDK_INSTALL_PYTHON_TESTS
  rdkit/CMakeLists.txt
Labels: Cleanup, infrastructure

#7321 Wedge bond from atrop error
  Code/GraphMol/Atropisomers.cpp
  Code/GraphMol/FileParsers/testAtropisomers.cpp
  Code/GraphMol/FileParsers/test_data/atropisomers/atropWedgeTest.sdf
  Code/GraphMol/FileParsers/test_data/atropisomers/atropWedgeTest.sdf.expected.cxsmi
  Code/GraphMol/FileParsers/test_data/atropisomers/atropWedgeTest.sdf.expected.sdf
  Code/GraphMol/FileParsers/test_data/atropisomers/atropWedgeTest.sdf.expected2.sdf
Labels: bug

#7329 cleanup RDKit::MolOps::detectBondStereochemistry
  Code/GraphMol/Chirality.cpp
Labels: Cleanup

#7326 C# Build Net6 library and tests using cmake
  .gitignore
  CMakeLists.txt
  Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
  Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/MolToFromByteArray.cs
  Code/JavaWrappers/csharp_wrapper/RDKitDotNetCore.sln
  Code/JavaWrappers/csharp_wrapper/RdkitTests/ExplicitBitVectTest.cs
  Code/JavaWrappers/csharp_wrapper/RdkitTests/GeneralizedSubstructTest.cs
  Code/JavaWrappers/csharp_wrapper/RdkitTests/MolDraw2DCairoTest.cs
  Code/JavaWrappers/csharp_wrapper/RdkitTests/MolDrawHighlightTest.cs
  Code/JavaWrappers/csharp_wrapper/RdkitTests/MolEnumeratorTest.cs
  Code/JavaWrappers/csharp_wrapper/RdkitTests/MolToFromByteArray.cs
  Code/JavaWrappers/csharp_wrapper/RdkitTests/RDKitCSharpTest.csproj
  Code/JavaWrappers/csharp_wrapper/RdkitTests/RGroupDecompositionTest.cs
  Code/JavaWrappers/csharp_wrapper/RdkitTests/ToMolMemoryTest.cs
  Code/JavaWrappers/csharp_wrapper/RdkitTests/Usings.cs
  Code/JavaWrappers/csharp_wrapper/RdkitTests/xunit.runner.json
  Code/JavaWrappers/csharp_wrapper/swig_csharp/RDKitDotNetCoreWrapper.csproj
Labels: enhancement, infrastructure

#7278 switch to range-based for loops
  Code/DataStructs/Wrap/testDiscreteValueVect.py
  Code/GraphMol/testChirality.cpp
  ReleaseNotes.md
Labels: Cleanup

#7330 fix 1,3- 1,5- conjugated cation normalizer transforms
  Code/GraphMol/MolStandardize/TransformCatalog/normalizations.in
  Code/GraphMol/MolStandardize/testNormalize.cpp
Labels: bug, Cleanup, not in release notes

#7351 Add MolStandardize to C# wrappers
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
  Code/JavaWrappers/csharp_wrapper/RdkitTests/TestMolStandardize.cs
Labels: enhancement

#7344 Add option for RASCAL to restrict atom matching to atoms of same degree
  Code/GraphMol/RascalMCES/RascalMCES.cpp
  Code/GraphMol/RascalMCES/RascalOptions.h
  Code/GraphMol/RascalMCES/RascalResult.cpp
  Code/GraphMol/RascalMCES/RascalResult.h
  Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp
  Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py
  Code/GraphMol/RascalMCES/mces_catch.cpp
Labels: enhancement

#7345 Fixes problem from discussion 7317
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: bug

#7255 Correct unbranched alkane SMARTS to match the description given
  Data/FragmentDescriptors.csv
  ReleaseNotes.md
Labels: bug, changes results

#7301 Support handling atropisomers without coordinates
  Code/GraphMol/Atropisomers.cpp
  Code/GraphMol/Chirality.h
  Code/GraphMol/FileParsers/CDXMLParser.cpp
  Code/GraphMol/FileParsers/MolFileStereochem.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/MarvinParse/MarvinParser.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/cxsmiles_test.cpp
  Code/GraphMol/SmilesParse/test_data/ShortAtropisomerNoCoords.cxsmi
  Code/GraphMol/SmilesParse/test_data/ShortAtropisomerNoCoords.cxsmi.expected.cxsmi
  Code/GraphMol/SmilesParse/test_data/ShortAtropisomerNoCoords.cxsmi.expected.mrv
  Code/GraphMol/SmilesParse/test_data/ShortAtropisomerNoCoords.cxsmi.expected.sdf
  Code/GraphMol/SmilesParse/test_data/ShortAtropisomerNoCoords.cxsmi.expected2.cxsmi
  Code/GraphMol/SmilesParse/test_data/ShortAtropisomerNoCoords.cxsmi.expected3.cxsmi
  Code/GraphMol/WedgeBonds.cpp
  Docs/Book/RDKit_Book.rst
  Docs/Book/images/atrop_representation1.png
  Docs/Book/images/atrop_representation2.png
Labels: enhancement

#7365 Cleanup of Code/DataStructs
  Code/DataStructs/BitOps.cpp
  Code/DataStructs/BitVect.cpp
  Code/DataStructs/DiscreteValueVect.cpp
  Code/DataStructs/Utils.cpp
  Code/DataStructs/Wrap/testBV.py
  Code/DataStructs/base64.cpp
Labels: Cleanup

#7382 Fix the Uncharger 'force' option w/ non-neutralizable negatively charged sites
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/catch_tests.cpp
Labels: bug

#7377 Restore mono build
  .azure-pipelines/vs_build_swig.yml
  CMakeLists.txt
  Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
Labels: infrastructure, not in release notes

#7386 Allow reapplyMolBlockWedging() to restore the original wedging regardless the bond type
  Code/GraphMol/Chirality.h
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/WedgeBonds.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#7388 Fixes typo in minilib: MolToCXSmiles should have read MolToSmiles
  Code/MinimalLib/minilib.cpp
Labels: Cleanup, not in release notes

#7391 Fix performance issue in PR 7327
  Code/GraphMol/ChemTransforms/ChemTransforms.cpp
  Code/GraphMol/RWMol.cpp
Labels: Cleanup, not in release notes

#6733 Code/PgSQL: Fix Pointer vs Datum (Compatibility with PG16)
  Code/PgSQL/rdkit/bfp_gist.c
  Code/PgSQL/rdkit/low_gist.c
  Code/PgSQL/rdkit/rdkit_gist.c
Labels: Cleanup

#7389 Include header for boost::numeric_cast
  Code/RDGeneral/RDValue-taggedunion.h
Labels: Cleanup

#7387 Revert "fix #7221 (#7230)"
  Scripts/gen_rdkit_stubs/__init__.py
Labels: not in release notes

#7379 Fixes #7378, raw docstring to escape null chars
  rdkit/Chem/Draw/__init__.py
Labels: documentation, Cleanup

#7395 Add option for non-isomeric SMILES creation in the PostgreSQL cartridge
  Code/PgSQL/rdkit/adapter.cpp
  Code/PgSQL/rdkit/expected/rdkit-91.out
  Code/PgSQL/rdkit/mol_op.c
  Code/PgSQL/rdkit/rdkit.control
  Code/PgSQL/rdkit/rdkit.h
  Code/PgSQL/rdkit/rdkit.sql.in
  Code/PgSQL/rdkit/rdkit_io.c
  Code/PgSQL/rdkit/sql/rdkit-91.sql
  Code/PgSQL/rdkit/update_sql/rdkit--4.4.0--4.5.0.sql.in
Labels: enhancement
