Repository rdkit/rdkit, pull requests merged in 2024-11, with the labels that each got.

#7869 Use .dylib on macOS for PostgreSQL 16+
  Code/PgSQL/rdkit/CMakeLists.txt
Labels: bug, infrastructure

#7960 Expose propertyFlags to CFFI and MinimalLib
  Code/GraphMol/MolPickler.h
  Code/JavaWrappers/ROMol.i
  Code/MinimalLib/CMakeLists.txt
  Code/MinimalLib/JSONParsers.cpp
  Code/MinimalLib/JSONParsers.h
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/common.h
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#7949 Fix for trimethylcyclohexane error
  Code/GraphMol/SmilesParse/CanonicalizeStereoGroups.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: bug

#7957 Fix incorrect CIP values for some aromatic atropisomers
  Code/GraphMol/CIPLabeler/Node.cpp
  Code/GraphMol/CIPLabeler/Node.h
  Code/GraphMol/CIPLabeler/catch_tests.cpp
  Code/GraphMol/CIPLabeler/configs/AtropisomerBond.cpp
  Code/GraphMol/CIPLabeler/configs/Configuration.cpp
  Code/GraphMol/CIPLabeler/configs/Configuration.h
Labels: bug

#7996 Remove unused code from GraphMol/SmilesParse
  Code/GraphMol/SmilesParse/CMakeLists.txt
  Code/GraphMol/SmilesParse/esmiles.flex
  Code/GraphMol/SmilesParse/esmiles.y
  Code/GraphMol/SmilesParse/main.cpp
  Code/GraphMol/SmilesParse/primes.h
  Code/GraphMol/SmilesParse/regress.txt
  Code/GraphMol/SmilesParse/runflex.sh
  Code/GraphMol/SmilesParse/smamain.cpp
Labels: Cleanup

#8005 Mol to smiles docs
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/GraphMol/Wrap/rdmolfiles.cpp
Labels: documentation

#7994 Expose tautomer scoring functions to python
  Code/GraphMol/MolStandardize/Tautomer.cpp
  Code/GraphMol/MolStandardize/Tautomer.h
  Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/catch_tests.cpp
Labels: enhancement

#8004 expanded documentation in Chem and AllChem
  rdkit/Chem/AllChem.py
  rdkit/Chem/__init__.py
Labels: documentation

#8007 Fix potential division by zero in UFF TorsionAngle
  Code/ForceField/UFF/TorsionAngle.cpp
Labels: bug

#8000 Implemented two more JSON parsers for CFFI and MinimalLib
  Code/GraphMol/MolOps.h
  Code/MinimalLib/JSONParsers.cpp
  Code/MinimalLib/JSONParsers.h
  Code/MinimalLib/cffi_test.c
  Code/MinimalLib/cffiwrapper.cpp
  Code/MinimalLib/cffiwrapper.h
  Code/MinimalLib/common.h
  Code/MinimalLib/jswrapper.cpp
  Code/MinimalLib/minilib.cpp
  Code/MinimalLib/minilib.h
  Code/MinimalLib/tests/tests.js
Labels: enhancement

#8011 Avoid division by zero in DrawMol
  Code/GraphMol/MolDraw2D/DrawMol.cpp
Labels: Cleanup

#7978 SynthonSpace Search
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/SynthonSpaceSearch/CMakeLists.txt
  Code/GraphMol/SynthonSpaceSearch/SubstructureResults.h
  Code/GraphMol/SynthonSpaceSearch/Synthon.cpp
  Code/GraphMol/SynthonSpaceSearch/Synthon.h
  Code/GraphMol/SynthonSpaceSearch/SynthonSet.cpp
  Code/GraphMol/SynthonSpaceSearch/SynthonSet.h
  Code/GraphMol/SynthonSpaceSearch/SynthonSpace.cpp
  Code/GraphMol/SynthonSpaceSearch/SynthonSpace.h
  Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearch_details.cpp
  Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearch_details.h
  Code/GraphMol/SynthonSpaceSearch/Wrap/CMakeLists.txt
  Code/GraphMol/SynthonSpaceSearch/Wrap/rdSynthonSpaceSearch.cpp
  Code/GraphMol/SynthonSpaceSearch/Wrap/testSynthonSpaceSearch.py
  Code/GraphMol/SynthonSpaceSearch/data/Syntons_5567.csv
  Code/GraphMol/SynthonSpaceSearch/data/amide_space.txt
  Code/GraphMol/SynthonSpaceSearch/data/amide_space_enum.smi
  Code/GraphMol/SynthonSpaceSearch/data/doebner_miller_space.txt
  Code/GraphMol/SynthonSpaceSearch/data/doebner_miller_space_enum.smi
  Code/GraphMol/SynthonSpaceSearch/data/idorsia_toy_space.spc
  Code/GraphMol/SynthonSpaceSearch/data/idorsia_toy_space_a.txt
  Code/GraphMol/SynthonSpaceSearch/data/idorsia_toy_space_enum.smi
  Code/GraphMol/SynthonSpaceSearch/data/map_numbers.txt
  Code/GraphMol/SynthonSpaceSearch/data/triazole_space.txt
  Code/GraphMol/SynthonSpaceSearch/data/triazole_space_enum.smi
  Code/GraphMol/SynthonSpaceSearch/data/urea_3.txt
  Code/GraphMol/SynthonSpaceSearch/data/urea_space.txt
  Code/GraphMol/SynthonSpaceSearch/data/urea_space_enum.smi
  Code/GraphMol/SynthonSpaceSearch/synthon_space_search_catch.cpp
Labels: enhancement

#8012 remove no-op macros and dead code (pt 1)
  Code/Demos/RDKit/Draw/demo.cpp
  Code/GraphMol/Canon.cpp
  Code/GraphMol/FMCS/testFMCS_Unit.cpp
  Code/GraphMol/FileParsers/testMolWriter.cpp
  Code/GraphMol/Fingerprints/PatternFingerprints.cpp
  Code/GraphMol/SmilesParse/smatest.cpp
  Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp
  Code/GraphMol/molopstest.cpp
  Code/GraphMol/testChirality.cpp
  Code/GraphMol/testPickler.cpp
Labels: Cleanup

#8013 Avoid division by zero in AlignPoints
  Code/Numerics/Alignment/AlignPoints.cpp
Labels: Cleanup

#8008 Throw when attempting to normalize a Zero RDGeom::Point
  Code/ForceField/UFF/Utils.cpp
  Code/Geometry/point.h
  Code/GraphMol/AddHs.cpp
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/WedgeBonds.cpp
  Code/GraphMol/catch_molops.cpp
  Code/Numerics/Vector.h
Labels: Cleanup

#7810 Catch exceptions in MultithreadedMolSupplier callbacks
  Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp
  Code/GraphMol/FileParsers/multithreaded_supplier_catch.cpp
Labels: bug

#8016 Fix probe molecule transformation for ShapeAlign
  External/pubchem_shape/CMakeLists.txt
  External/pubchem_shape/PubChemShape.cpp
  External/pubchem_shape/test.cpp
  External/pubchem_shape/test_data/P17612.sdf
Labels: bug

#8029 improve defaults for the shape-based alignment
  External/pubchem_shape/PubChemShape.hpp
  External/pubchem_shape/Wrap/cshapealign.cpp
  External/pubchem_shape/Wrap/test_rdshapealign.py
  External/pubchem_shape/test.cpp
Labels: enhancement, changes results

#8030 disable UBSAN builds in CI
  .azure-pipelines/linux_build_ubsan.yml
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#8014 Fix shifting of a potentially negative number
  Code/GraphMol/MMPA/MMPA.cpp
  Code/GraphMol/MMPA/MMPA.h
  Code/GraphMol/MMPA/MMPA_UnitTest.cpp
Labels: Cleanup

#8040 fixing the doc string in the shape alignment code
  External/pubchem_shape/Wrap/cshapealign.cpp
Labels: documentation

#8046 Remove explicit default constructor from Compute2DCoordParameters
  Code/GraphMol/Depictor/RDDepictor.h
Labels: Cleanup

#8048 Synthon space2
  Code/GraphMol/SynthonSpaceSearch/Synthon.cpp
  Code/GraphMol/SynthonSpaceSearch/SynthonSpace.cpp
  Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearch_details.cpp
  Code/GraphMol/SynthonSpaceSearch/data/gregs_space_fail.txt
  Code/GraphMol/SynthonSpaceSearch/synthon_space_search_catch.cpp
Labels: bug, not in release notes

#8049 Improve doc string for ParseAbbreviations in python wrapper.
  Code/GraphMol/Abbreviations/Wrap/rdAbbreviations.cpp
Labels: documentation
