Repository rdkit/rdkit, pull requests merged in 2024-02, with the labels that each got.

#7113 Add v2 API for the molecule CDXML parser
  Code/GraphMol/FileParsers/CDXMLParser.cpp
  Code/GraphMol/FileParsers/CDXMLParser.h
  Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
Labels: enhancement

#7110 [v2 API] MRV parsers
  Code/GraphMol/MarvinParse/MarvinParser.cpp
  Code/GraphMol/MarvinParse/MarvinParser.h
  Code/GraphMol/MarvinParse/testMrvToMol.cpp
Labels: enhancement

#7088 Add a 'force' option to MolStandardizer::Uncharger
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/Charge.h
  Code/GraphMol/MolStandardize/Wrap/Charge.cpp
  Code/GraphMol/MolStandardize/catch_tests.cpp
Labels: enhancement

#7139 require SWIG 4.1+ at cmake config time
  Code/JavaWrappers/CMakeLists.txt
Labels: Cleanup, infrastructure

#7098 Support atropisomers in the conformer generator
  Code/GraphMol/Atropisomers.h
  Code/GraphMol/CIPLabeler/configs/AtropisomerBond.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/DistGeomHelpers/test_data/atropisomers.sdf
  Code/GraphMol/new_canon.cpp
Labels: enhancement

#7143 Install MolFileStereochem.h again
  Code/GraphMol/FileParsers/CMakeLists.txt
Labels: bug, infrastructure, not in release notes

#7147 fix a memory overwrite caused by #7098
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
Labels: bug, not in release notes

#7160 C sharp failing to build
  Code/JavaWrappers/ROMol.i
  Code/JavaWrappers/RWMol.i
Labels: bug, not in release notes

#7165 fix: add PandasTools support for pandas 2.2
  rdkit/Chem/PandasPatcher.py
Labels: bug

#7178 Fix leaking Bonds on unmatched ring closures
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: bug

#7180 fix a problem with reading older pickles
  Code/GraphMol/MolPickler.cpp
  Code/GraphMol/catch_pickles.cpp
  Code/GraphMol/test_data/mol_with_sgroups_and_stereo.pkl
Labels: bug, not in release notes

#7182 Update MinimalLib Dockerfiles
  Code/MinimalLib/docker/Dockerfile
  Code/MinimalLib/docker/Dockerfile_legacy_browsers
Labels: enhancement, infrastructure

#7173 update cookbook, draw molecule with atom indices
  Docs/Book/Cookbook.rst
  Docs/Book/images/RDKitCB_0_im1.png
Labels: enhancement, documentation

#7188 Don't reset computed properties if already empty
  Code/RDGeneral/RDProps.h
Labels: enhancement, optimization

#7172 Improve output of debugMol
  Code/GraphMol/Atom.cpp
  Code/GraphMol/Atom.h
  Code/GraphMol/Bond.cpp
  Code/GraphMol/StereoGroup.cpp
  Code/GraphMol/catch_graphmol.cpp
Labels: enhancement

#7191 Fix a few issues found while attempting to build stubs as part of a Windows conda build
  CMakeLists.txt
  Scripts/gen_rdkit_stubs/__init__.py
  Scripts/gen_rdkit_stubs/worker.py
Labels: infrastructure

#7187 switch the TFD code to use a fingerprint generator
  rdkit/Chem/TorsionFingerprints.py
Labels: enhancement

#7168 V2 API for the MolSuppliers
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/FileParsers.h
  Code/GraphMol/FileParsers/ForwardSDMolSupplier.cpp
  Code/GraphMol/FileParsers/MaeMolSupplier.cpp
  Code/GraphMol/FileParsers/MolSupplier.h
  Code/GraphMol/FileParsers/MolSupplier.v1API.h
  Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp
  Code/GraphMol/FileParsers/MultithreadedMolSupplier.h
  Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.cpp
  Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h
  Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.cpp
  Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.h
  Code/GraphMol/FileParsers/PDBSupplier.cpp
  Code/GraphMol/FileParsers/SDMolSupplier.cpp
  Code/GraphMol/FileParsers/SmilesMolSupplier.cpp
  Code/GraphMol/FileParsers/TDTMolSupplier.cpp
  Code/GraphMol/FileParsers/v2_suppliers_catch.cpp
  Code/GraphMol/SmilesParse/SmilesParse.h
  Code/GraphMol/Wrap/ForwardSDMolSupplier.cpp
  Code/GraphMol/Wrap/MaeMolSupplier.cpp
  Code/JavaWrappers/MolSupplier.i
  ReleaseNotes.md
Labels: enhancement
