Repository rdkit/rdkit, pull requests merged in 2024-03, with the labels that each got.

#7205 [CI] add csharp build on windows
  .azure-pipelines/vs_build_swig.yml
  azure-pipelines.yml
Labels: infrastructure

#7186 RGD code cleanup
  Code/GraphMol/RGroupDecomposition/RGroupCore.cpp
  Code/GraphMol/RGroupDecomposition/RGroupCore.h
  Code/GraphMol/RGroupDecomposition/RGroupData.cpp
  Code/GraphMol/RGroupDecomposition/RGroupData.h
  Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
  Code/GraphMol/RGroupDecomposition/RGroupDecompData.cpp
  Code/GraphMol/RGroupDecomposition/RGroupScore.cpp
Labels: Cleanup

#7204 Add some ExplicitBitVect operations to Swig
  Code/JavaWrappers/ExplicitBitVect.i
  Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/ExplicitBitVectTest.cs
Labels: enhancement

#7183 allow perception of stereo from T-shaped structures
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/FileParsers/molfile_stereo_catch.cpp
  Code/GraphMol/catch_chirality.cpp
  ReleaseNotes.md
Labels: enhancement, changes results

#7145 optimize batch operations when editing molecules
  Code/GraphMol/Conformer.cpp
  Code/GraphMol/RWMol.cpp
  Code/GraphMol/RWMol.h
Labels: enhancement, optimization

#7212 Do not wedge bonds to attachment points
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/WedgeBonds.cpp
  Code/GraphMol/catch_chirality.cpp
Labels: enhancement, not in release notes

#7211 Fix Uncharger applying to already neutralized perhalic groups
  Code/GraphMol/MolStandardize/Charge.cpp
  Code/GraphMol/MolStandardize/testCharge.cpp
Labels: bug

#7217 Build documentation preview upon opening a pull request
  .github/workflows/documentation-links.yml
Labels: documentation, infrastructure

#7222 v1 Mol Suppliers missing the moveTo method
  Code/GraphMol/FileParsers/MolSupplier.h
  Code/GraphMol/FileParsers/MolSupplier.v1API.h
Labels: bug, not in release notes

#7225 Revert "Build documentation preview upon opening a pull request"
  .github/workflows/documentation-links.yml
Labels: infrastructure, not in release notes

#7226 make things work with pandas 2.2
  rdkit/Chem/PandasPatcher.py
Labels: bug, not in release notes

#7206 Fixes #7181
  Code/DistGeom/DistGeomUtils.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.cpp
  Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.h
Labels: bug

#7232 Fix `Chem.Randomize.py`
  rdkit/Chem/Randomize.py
  rdkit/Chem/UnitTestRandomize.py
Labels: bug, Cleanup

#7200 fix a problem with tautomeric systems being extended too far
  Code/GraphMol/MolHash/catch_tests.cpp
  Code/GraphMol/MolHash/hashfunctions.cpp
  ReleaseNotes.md
Labels: bug, changes results

#7227 remove the broken Dbase.DbReport module
  ReleaseNotes.md
  rdkit/Dbase/DbReport.py
Labels: deprecation, Cleanup

#7249 Remove duplicate entry
  Data/FragmentDescriptors.csv
Labels: bug

#7258 Make _NonExplicit3DChirality a public property
  Code/GraphMol/Chirality.cpp
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
Labels: bug, not in release notes

#7245 Avoid rebuilding FreeSASA at every build for no good reason
  External/FreeSASA/CMakeLists.txt
Labels: Cleanup, infrastructure

#7229 Custom decimal precision
  Code/GraphMol/FileParsers/FileParserUtils.h
  Code/GraphMol/FileParsers/FileWriters.h
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/XYZFileWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/testMolWriter.cpp
  Code/GraphMol/FileParsers/test_data/precision.v3k.mol
  Code/GraphMol/MarvinParse/MarvinDefs.cpp
  Code/GraphMol/MarvinParse/MarvinDefs.h
  Code/GraphMol/MarvinParse/MarvinParser.h
  Code/GraphMol/MarvinParse/MarvinWriter.cpp
  Code/GraphMol/MarvinParse/testMrvToMol.cpp
  Code/GraphMol/MarvinParse/test_data/precision.mrv.expected.mrv
  Code/GraphMol/Wrap/rdmolfiles.cpp
Labels: enhancement

#7233 remove a bunch of std::endls
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/MolSGroupWriting.cpp
  Code/GraphMol/FileParsers/TplFileWriter.cpp
  Code/GraphMol/MolDraw2D/DrawTextFTSVG.cpp
  Code/GraphMol/MolDraw2D/DrawTextSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
Labels: Cleanup

#7228 Some modernization of core GraphMol classes
  Code/GraphMol/Atom.cpp
  Code/GraphMol/Bond.cpp
  Code/GraphMol/Conformer.cpp
  Code/GraphMol/Conformer.h
  Code/GraphMol/MonomerInfo.h
  Code/GraphMol/QueryAtom.h
  Code/GraphMol/QueryBond.h
  Code/GraphMol/ROMol.cpp
  Code/GraphMol/RWMol.cpp
Labels: enhancement, Cleanup

#7253 add HetAtomProtomerv2
  Code/GraphMol/MolHash/Wrap/rdMolHash.cpp
  Code/GraphMol/MolHash/Wrap/testMolHash.py
  Code/GraphMol/MolHash/catch_tests.cpp
  Code/GraphMol/MolHash/hashfunctions.cpp
  Code/GraphMol/MolHash/nmmolhash.h
  Docs/Book/Cookbook.rst
Labels: enhancement

#7269 Support zero order bonds in V3K CTABs
  Code/GraphMol/FileParsers/MolFileParser.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/catch_chirality.cpp
Labels: enhancement

#7270 add option to symmetrize conjugated terminal groups when RMS pruning conformers
  Code/GraphMol/DistGeomHelpers/CMakeLists.txt
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/EmbedderUtils.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/MolAlign/AlignMolecules.cpp
  Code/GraphMol/MolAlign/AlignMolecules.h
  ReleaseNotes.md
Labels: enhancement, changes results

#7271 beta release prep
  CMakeLists.txt
  ReleaseNotes.md
Labels: infrastructure, not in release notes

#7272 Deprecate legacy molecule drawing code
  ReleaseNotes.md
Labels: deprecation, Cleanup, not in release notes

#7274 Update ring fusion cache when needed
  Code/GraphMol/RingInfo.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/molopstest.cpp
Labels: bug

#7234 Add Double Cubic Lattice Volume (DCLV).
  Code/GraphMol/Descriptors/CMakeLists.txt
  Code/GraphMol/Descriptors/DCLV.cpp
  Code/GraphMol/Descriptors/DCLV.h
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
  Code/GraphMol/Descriptors/catch_tests.cpp
  Code/GraphMol/Descriptors/test_data/1mup.pdb
  Code/GraphMol/Descriptors/test_data/TZL_model.sdf
  Docs/Book/GettingStartedInPython.rst
Labels: enhancement

#7279 fix a leak in the new DCLV code
  Code/GraphMol/Descriptors/DCLV.cpp
  Code/GraphMol/Descriptors/DCLV.h
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
Labels: bug, not in release notes

#7308 tag 2024.03 release
  CMakeLists.txt
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  ReleaseNotes.md
Labels: infrastructure, not in release notes

#7314 open new release cycle
  CMakeLists.txt
  Docs/Book/conf.py
  ReleaseNotes.md
Labels: infrastructure, not in release notes
