Repository rdkit/rdkit, pull requests merged in 2024-01, with the labels that each got.

#7029 fix GCC 13.2 warnings about redundant move in return statement
  Code/GraphMol/FMCS/Wrap/rdFMCS.cpp
  Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
  Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp
  Code/GraphMol/MolChemicalFeatures/Wrap/ChemicalFeatureUtils.cpp
  External/FreeSASA/Wrap/rdFreeSASA.cpp
Labels: Cleanup

#7010 New tests for specical query atoms and atropisomers
  Code/GraphMol/CIPLabeler/Wrap/pyCIPLabelWrapTest.py
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/FileParsers/test1.cpp
  Code/GraphMol/FileParsers/testAtropisomers.cpp
  Code/GraphMol/FileParsers/test_data/AtomQuery1.mol
  Code/GraphMol/FileParsers/test_data/AtomQuery2.mol
  Code/GraphMol/FileParsers/test_data/AtomQuery3.mol
  Code/GraphMol/FileParsers/test_data/cdk2_stereo.csv
  Code/GraphMol/GenericGroups/CMakeLists.txt
  Code/GraphMol/GenericGroups/GenericGroups.h
  Code/GraphMol/GenericGroups/generic_tests.cpp
  Code/GraphMol/MarvinParse/testMrvToMol.cpp
  Code/GraphMol/MarvinParse/test_data/FalseChiral.mrv
  Code/GraphMol/MarvinParse/test_data/FalseChiral.mrv.noreapply.expected.mrv
  Code/GraphMol/MarvinParse/test_data/FalseChiral.mrv.noreapply.expected.sdf
  Code/GraphMol/MarvinParse/test_data/FalseChiral.mrv.nosan.expected.mrv
  Code/GraphMol/MarvinParse/test_data/FalseChiral.mrv.nosan.expected.sdf
  Code/GraphMol/MarvinParse/test_data/FalseChiral.mrv.nosan.noreapply.expected.mrv
  Code/GraphMol/MarvinParse/test_data/FalseChiral.mrv.nosan.noreapply.expected.sdf
  Code/GraphMol/MarvinParse/test_data/NewChiralTest.mrv.noreapply.expected.mrv
  Code/GraphMol/MarvinParse/test_data/NewChiralTest.mrv.noreapply.expected.sdf
  Code/GraphMol/MarvinParse/test_data/NewChiralTest.mrv.nosan.noreapply.expected.mrv
  Code/GraphMol/MarvinParse/test_data/NewChiralTest.mrv.nosan.noreapply.expected.sdf
  Code/GraphMol/MarvinParse/test_data/NewChiralTestAllChiral.mrv.noreapply.expected.mrv
  Code/GraphMol/MarvinParse/test_data/NewChiralTestAllChiral.mrv.noreapply.expected.sdf
  Code/GraphMol/MarvinParse/test_data/NewChiralTestAllChiral.mrv.nosan.noreapply.expected.mrv
  Code/GraphMol/MarvinParse/test_data/NewChiralTestAllChiral.mrv.nosan.noreapply.expected.sdf
  Code/GraphMol/MarvinParse/test_data/NewChiralTestNoChiral.mrv.noreapply.chiral.sdf
  Code/GraphMol/MarvinParse/test_data/NewChiralTestNoChiral.mrv.noreapply.expected.mrv
  Code/GraphMol/MarvinParse/test_data/NewChiralTestNoChiral.mrv.noreapply.expected.sdf
  Code/GraphMol/MarvinParse/test_data/NewChiralTestNoChiral.mrv.nosan.noreapply.expected.mrv
  Code/GraphMol/MarvinParse/test_data/NewChiralTestNoChiral.mrv.nosan.noreapply.expected.sdf
  Code/GraphMol/molopstest.cpp
Labels: Cleanup

#7049 2 new projects using RDKit
  README.md
Labels: documentation

#7032 Update distance bounds calculation for conjugated double bonds in macrocycles
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
Labels: bug

#7035 fix check of python version when updating Filters.cpp
  Code/GraphMol/FilterCatalog/CMakeLists.txt
Labels: Cleanup, infrastructure

#6203 [v2 API] SMILES/SMARTS parsers
  Code/GraphMol/SmilesParse/CMakeLists.txt
  Code/GraphMol/SmilesParse/SmilesParse.cpp
  Code/GraphMol/SmilesParse/SmilesParse.h
  Code/GraphMol/SmilesParse/v2catch_tests.cpp
  Code/JavaWrappers/RDKitExceptions.i
  Code/JavaWrappers/RWMol.i
  Code/JavaWrappers/SmilesParse.i
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
Labels: enhancement, Cleanup

#7082 lock the versions of a bunch of stuff used in the CI builds
  .azure-pipelines/linux_build.yml
  .azure-pipelines/linux_build_limitexternal.yml
  .azure-pipelines/linux_build_py311.yml
  .azure-pipelines/mac_build.yml
  .azure-pipelines/vs_build.yml
  .azure-pipelines/vs_build_dll.yml
Labels: Cleanup, infrastructure

#7085 refactoring of MolStandardize validation module
  Code/GraphMol/MolStandardize/Validate.cpp
  Code/GraphMol/MolStandardize/Validate.h
  Code/GraphMol/MolStandardize/Wrap/Validate.cpp
  Code/GraphMol/MolStandardize/test2.cpp
  Code/GraphMol/MolStandardize/testValidate.cpp
  ReleaseNotes.md
Labels: enhancement, Cleanup

#7056 fragmentation of mol loses any sgroups
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/test_data/sgroupFragments/DataSgroup.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/DataSgroupMissingUnitsDisplayed.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSGroupSUP_MUL.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSgroupCOP_SUP.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSgroupDAT_SUP.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSgroupMUL_MUL.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSgroupMUL_SUP.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSgroupSRU_SUP.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSgroupSUPEXP_SUP.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSgroupSUPEXP_SUP2.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSgroupSUP_SUP.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/EmbeddedSgroupSUP_SUP2.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/GenericSgroup.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/MarvinOldSuperGroupTest.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/MonomerSgroup.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/MultipleSgroup.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/MultipleSgroupParentInMiddleOfAtomBlock.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/SgroupExpanded.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/SgroupMultAttach.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/Sgroup_MUL_ParentInMiddle.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/copolymer_sgroup.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/modification_sgroup.sdf
  Code/GraphMol/FileParsers/test_data/sgroupFragments/polymerSalt.mol
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/RWMol.cpp
  Code/GraphMol/StereoGroup.cpp
  Code/GraphMol/StereoGroup.h
  Code/GraphMol/testChirality.cpp
Labels: bug

#7096 update font md5 sum
  Code/GraphMol/MolDraw2D/CMakeLists.txt
Labels: infrastructure, not in release notes

#7100 Compatibility with pathlib.Path
  Code/RDBoost/Wrap.h
  Code/RDBoost/Wrap/RDBase.cpp
  rdkit/Chem/Suppliers/UnitTestSDMolSupplier.py
Labels: enhancement

#7063 fix several warnings originating from the swig wrappers
  Code/GraphMol/FilterCatalog/FilterMatcherBase.h
  Code/JavaWrappers/Atom.i
  Code/JavaWrappers/Bond.i
  Code/JavaWrappers/FMCS.i
  Code/JavaWrappers/FilterCatalog.i
  Code/JavaWrappers/ROMol.i
  Code/JavaWrappers/SubstanceGroup.i
  Code/JavaWrappers/SubstructLibrary.i
  Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
Labels: Cleanup

#7055 Lipinski Rule of 5 was incorrectly described.
  Docs/Book/GettingStartedInPython.rst
Labels: documentation

#7103 chore: fix blog link to new blog location
  README.md
Labels: documentation

#7095 support sanitization of reaction product templates
  Code/GraphMol/ChemReactions/CDXMLParser.cpp
  Code/GraphMol/ChemReactions/SanitizeRxn.cpp
  Code/GraphMol/ChemReactions/SanitizeRxn.h
  Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
  Code/GraphMol/ChemReactions/catch_tests.cpp
Labels: enhancement
