Repository rdkit/rdkit, pull requests merged in 2025-05, with the labels that each got.

#8477 Set default Eigen3 version to 3.4.0
  External/Eigen/CMakeLists.txt
Labels: enhancement, infrastructure

#8504 Fix arrowhead8500
  Code/GraphMol/MolDraw2D/DrawShape.cpp
  Code/GraphMol/MolDraw2D/DrawShape.h
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DDetails.h
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: bug

#8517 Explain DrawArrow and rawCoords=True
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
Labels: enhancement, documentation

#8518 add support for allene- and cumulene-like structures to KDG
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
Labels: enhancement

#8450 Modernization of some substructure code
  Code/GraphMol/GenericGroups/GenericGroups.cpp
  Code/GraphMol/GenericGroups/GenericGroups.h
  Code/GraphMol/GenericGroups/generic_tests.cpp
  Code/GraphMol/Substruct/SubstructMatch.cpp
  Code/GraphMol/Substruct/SubstructMatch.h
  Code/GraphMol/Substruct/SubstructUtils.cpp
  Code/GraphMol/Substruct/SubstructUtils.h
  Code/GraphMol/Substruct/catch_tests.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.cpp
  Code/GraphMol/TautomerQuery/TautomerQuery.h
  Code/GraphMol/Wrap/Mol.cpp
  Regress/Scripts/new_timings.py
Labels: Cleanup

#8521 A few mem fixes in tests
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/FileParsers/testMolWriter.cpp
  Code/GraphMol/FileParsers/v2_suppliers_catch.cpp
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/querytest.cpp
Labels: Cleanup

#8414 Change default ETversion.
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
Labels: enhancement

#8528 Fix ETKDG double bond check from #8518
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
Labels: bug

#8545 Avoid a large number of warnings when building MinimalLib with emscripten
  CMakeLists.txt
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/MolDraw2D/CMakeLists.txt
  Code/MinimalLib/CMakeLists.txt
  Code/cmake/Modules/RDKitUtils.cmake
  External/CoordGen/CMakeLists.txt
Labels: enhancement, infrastructure

#8541 allow limiting the number of stereo groups to process
  Code/GraphMol/SmilesParse/CanonicalizeStereoGroups.cpp
  Code/GraphMol/SmilesParse/CanonicalizeStereoGroups.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/Wrap/MolOps.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#8555 Explicitly wrap raw pointer into emscripten::val object with allow_raw_pointers() policy
  Code/MinimalLib/jswrapper.cpp
Labels: bug, Cleanup

#8540 Fix irritating warning when DrawMolMCHLasso compiled.
  Code/GraphMol/MolDraw2D/DrawMolMCHLasso.cpp
Labels: Cleanup

#8557 Support Ctrl+C in determineBondOrders
  Code/GraphMol/DetermineBonds/DetermineBonds.cpp
  Code/GraphMol/DetermineBonds/Wrap/rdDetermineBonds.cpp
  Code/GraphMol/DetermineBonds/catch_tests.cpp
Labels: enhancement

#8558 fix a problem with stereogroups involving bonds and getMolFrags()
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/RWMol.cpp
  Code/GraphMol/StereoGroup.cpp
  Code/GraphMol/StereoGroup.h
  Code/GraphMol/molopstest.cpp
Labels: bug, not in release notes
