Repository rdkit/rdkit, pull requests merged in 2025-07, with the labels that each got.

#8623 Scsr sgroup error
  Code/GraphMol/FileParsers/SCSRMolFileParser.cpp
  Code/GraphMol/FileParsers/macromols_catch.cpp
  Code/GraphMol/FileParsers/test_data/macromols/Conjugate.mol
Labels: bug

#8636 fix a typo in a CI file
  .azure-pipelines/vs_build.yml
Labels: infrastructure, not in release notes

#8640 Mem fixes
  Code/GraphMol/EnumerateStereoisomers/Wrap/rdEnumerateStereoisomers.cpp
  Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp
  Code/RDGeneral/ConcurrentQueue.h
Labels: bug

#8609 Add option to draw all CIP codes in DrawMol.cpp
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/DrawMol.h
  Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/MinimalLib/docs/GettingStartedInJS.html
Labels: enhancement
