Repository rdkit/rdkit, pull requests merged in 2025-10, with the labels that each got.

#8835 Implement a mechanism to patch .pyi files as proposed in #8749
  Scripts/gen_rdkit_stubs/__init__.py
  Scripts/gen_rdkit_stubs/patch/rdkit/Chem/inchi.pyi.diff
  Scripts/gen_rdkit_stubs/worker.py
Labels: enhancement, infrastructure

#8837 run clang-tidy and clang-format on the chemdraw files
  External/ChemDraw/ChemDrawStartInclude.h
  External/ChemDraw/bond.cpp
  External/ChemDraw/bond.h
  External/ChemDraw/bracket.cpp
  External/ChemDraw/bracket.h
  External/ChemDraw/chemdraw.cpp
  External/ChemDraw/chemdraw.h
  External/ChemDraw/chemdraw_doc.h
  External/ChemDraw/chemdrawreaction.cpp
  External/ChemDraw/chemdrawreaction.h
  External/ChemDraw/fragment.cpp
  External/ChemDraw/fragment.h
  External/ChemDraw/node.cpp
  External/ChemDraw/node.h
  External/ChemDraw/reaction.cpp
  External/ChemDraw/reaction.h
  External/ChemDraw/test-chiral.cpp
  External/ChemDraw/test-reactions.cpp
  External/ChemDraw/test.cpp
  External/ChemDraw/test_3d.cpp
  External/ChemDraw/test_6k.cpp
  External/ChemDraw/utils.cpp
  External/ChemDraw/utils.h
  External/ChemDraw/writer.cpp
Labels: Cleanup

#8848 new release prep
  CMakeLists.txt
  Docs/Book/conf.py
  ReleaseNotes.md
Labels: infrastructure, not in release notes
