Repository rdkit/rdkit, pull requests merged in 2025-08, with the labels that each got.

#8685 Fix documentation errors for rdShapeAlign
  External/pubchem_shape/Wrap/cshapealign.cpp
Labels: documentation

#8693 Explicitly set COMPOSE_BAKE to false
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#8675 Fix parse error messages for bad characters
  Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smarts.yy
  Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake
  Code/GraphMol/SmilesParse/smiles.yy
  Code/GraphMol/SmilesParse/test.cpp
Labels: bug

#8694 Fix build with Boost 1.89.0
  CMakeLists.txt
  Docs/Book/C++Examples/CMakeLists.txt
  rdkit-config.cmake.in
Labels: bug, infrastructure

#8706 Fix drawing of very short arcs in lasso.
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: bug

#8709 increase max time for win64 CI builds
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#8731 Fixes a bug with bad H positions in output conformer
  External/pubchem_shape/PubChemShape.cpp
  External/pubchem_shape/PubChemShape.hpp
  External/pubchem_shape/test.cpp
  External/pubchem_shape/test_data/hcount_ex1_1.mol
  External/pubchem_shape/test_data/hcount_ex1_2.mol
Labels: bug

#8733 patch a memory allocation problem in the pubchem shape code
  External/pubchem_shape/CMakeLists.txt
Labels: bug

#8681 Expose CDX support to FileParsers and ChemDraw to SWIG
  .azure-pipelines/linux_build_limitexternal.yml
  CMakeLists.txt
  Code/GraphMol/FileParsers/CDXMLParser.cpp
  Code/GraphMol/FileParsers/CDXMLParser.h
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Code/GraphMol/Wrap/test_cdxml.py
  Code/GraphMol/test_data/CDX/structure_1.cdx
  Code/GraphMol/test_data/CDX/structure_2.cdx
  Code/GraphMol/test_data/CDX/structure_3.cdx
  Code/GraphMol/test_data/CDX/structure_4.cdx
  Code/GraphMol/test_data/CDX/structure_5.cdx
  Code/GraphMol/test_data/CDX/structure_6.cdx
  Code/GraphMol/test_data/CDXML/ring-stereo1.cdx
  Code/JavaWrappers/CMakeLists.txt
  Code/JavaWrappers/ChemDraw.i
  Code/JavaWrappers/RWMol.i
  Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
  Code/JavaWrappers/csharp_wrapper/RdkitTests/MolToFromByteArray.cs
  Code/JavaWrappers/gmwrapper/CMakeLists.txt
  Code/JavaWrappers/gmwrapper/GraphMolJava.i
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/ChemDrawTest.java
  Code/JavaWrappers/gmwrapper/src-test/org/RDKit/WrapperTests.java
  Code/RDGeneral/RDConfig.h.cmake
  External/ChemDraw/Wrap/rdChemDraw.cpp
  External/ChemDraw/chemdraw.cpp
  External/ChemDraw/chemdraw.h
Labels: enhancement
