Repository rdkit/rdkit, pull requests merged in 2025-09, with the labels that each got.

#8773 Avoid code duplication through a templated function and improve JSON parsing of Boolean flags
  Code/GraphMol/SmilesParse/SmilesJSONParsers.cpp
  Code/GraphMol/SmilesParse/cxsmiles_test.cpp
  Code/MinimalLib/JSONParsers.cpp
  Code/RDGeneral/JSONHelpers.h
Labels: bug, Hackathon idea

#8781 Changed linux build from source docs to use miniconda
  Docs/Book/Install.md
Labels: documentation

#8792 fix a mistake caused by a dumb suggestion I made to #8757
  Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
Labels: bug, not in release notes

#8810 Stop External/rapidjson-1.1.0 and Code/RDGeneral going to ${CMAKE_SOURCE_DIR}
  Code/GraphMol/MolInterchange/CMakeLists.txt
  Code/cmake/Modules/RDKitUtils.cmake
Labels: infrastructure

#8756 DCLV updates
  Code/GraphMol/Descriptors/DCLV.cpp
  Code/GraphMol/Descriptors/DCLV.h
  Code/GraphMol/Descriptors/DCLV_dots.h
  Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
  Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
  Code/GraphMol/Descriptors/catch_tests.cpp
  Code/GraphMol/Descriptors/test_data/ethane.sdf
Labels: enhancement
