Repository rdkit/rdkit, pull requests merged in 2025-02, with the labels that each got.

#8214 Use GetUniqueCombinations_new instead of GetUniqueCombinations
  ReleaseNotes.md
  rdkit/Chem/Pharm2D/UnitTestUtils.py
  rdkit/Chem/Pharm2D/Utils.py
Labels: optimization

#8267 Restore functionality of the MinimalLib Dockerfile and improve exception handling performance
  Code/MinimalLib/docker/Dockerfile
Labels: infrastructure

#8248 Rascal: Add option to specify minimum clique size directly.
  Code/GraphMol/RascalMCES/RascalMCES.cpp
  Code/GraphMol/RascalMCES/RascalOptions.h
  Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp
  Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py
  Code/GraphMol/RascalMCES/mces_catch.cpp
Labels: enhancement

#8270 Revert Dockerfile to JavaScript-based exceptions (with an option for switching to native WASM)
  Code/MinimalLib/docker/Dockerfile
Labels: Cleanup, not in release notes

#8249 MolDraw2D: add separate colors for atom and bond annotations
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/MolDraw2D.h
  Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  ReleaseNotes.md
Labels: enhancement, changes results

#8277 Tweak mol fragmenter
  Code/GraphMol/ChemTransforms/MolFragmenter.cpp
Labels: enhancement

#8276 Some mem fixes.
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
  External/INCHI-API/inchi.cpp
Labels: bug

#8283 Expose basinThresh to the python layer
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
Labels: enhancement

#8282 Fix buffer size in pickersCLI.cpp
  Code/SimDivPickers/pickersCLI.cpp
Labels: bug

#8290 try adding a CI job to build the minimallib docker image
  Code/MinimalLib/docker/Dockerfile_CI
  azure-pipelines.yml
Labels: infrastructure

#8291 Another mem leak fix to the InChI conversion
  External/INCHI-API/inchi.cpp
Labels: bug

#8272 trimethylcyclohexane chirality error
  Code/GraphMol/FindStereo.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
Labels: bug

#8298 Fix memory leaks in MolStandardize SWIG Wrapper
  Code/GraphMol/RGroupDecomposition/RGroupFingerprintScore.cpp
  Code/JavaWrappers/MolStandardize.i
Labels: bug

#8297 Make MaeWriter to throw on errors.
  Code/GraphMol/FileParsers/FileWriters.h
  Code/GraphMol/FileParsers/MaeWriter.cpp
  Code/GraphMol/FileParsers/PDBWriter.cpp
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  ReleaseNotes.md
Labels: enhancement, changes results

#8300 bump InChI version to 1.07.3
  Code/cmake/Modules/FindInchi.cmake
Labels: enhancement
