Repository rdkit/rdkit, pull requests merged in 2025-01, with the labels that each got.

#8148 relax two tolerances for ARM64 builds
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
Labels: Cleanup

#8134 fix: apply modernize-use-nullptr
  Code/GraphMol/FilterCatalog/Filters.cpp
  Code/GraphMol/NontetrahedralStereo.cpp
  Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake
  Code/GraphMol/SmilesParse/lex.yysmiles.cpp.cmake
  Code/JavaWrappers/MorganFingerprints.h
  Code/RDGeneral/LocaleSwitcher.cpp
  Code/SimDivPickers/LeaderPicker.h
Labels: Cleanup

#8035 remove no-op macros and dead code (pt 2)
  Code/Demos/RDKit/Basement/BinaryIO/iotest.cpp
  Code/Demos/RDKit/Basement/TemplEnum/TemplEnumTools.cpp
  Code/Features/CMakeLists.txt
  Code/Features/testFeatures.cpp
  Code/GraphMol/ChemReactions/testReaction.cpp
  Code/GraphMol/ChemTransforms/testChemTransforms.cpp
  Code/GraphMol/Chirality.cpp
  Code/GraphMol/Depictor/testDepictor.cpp
  Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
  Code/GraphMol/FileParsers/MolFileWriter.cpp
  Code/GraphMol/FileParsers/molfile_stereo_catch.cpp
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/MolStandardize/testNormalize.cpp
  Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
  Code/GraphMol/SLNParse/SLNAttribs.cpp
  Code/GraphMol/catch_graphmol.cpp
  Code/GraphMol/itertest.cpp
  Code/PgSQL/rdkit/adapter.cpp
  Code/RDGeneral/testDict.cpp
Labels: Cleanup

#8110 Conformer embedding timeout
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Embedder.h
  Code/GraphMol/DistGeomHelpers/EmbedderUtils.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
Labels: enhancement

#8166 Unify Mol rendering in IPython
  rdkit/Chem/Draw/IPythonConsole.py
Labels: bug

#8176 bump the inchi version to 1.07.2
  Code/PgSQL/rdkit/adapter.cpp
  Code/cmake/Modules/FindInchi.cmake
Labels: enhancement

#8187 Update InChi links
  External/INCHI-API/Wrap/pyInchi.cpp
Labels: documentation

#8190 some optimizations of triangle smoothing and the bounds matrix code
  Code/DistGeom/BoundsMatrix.h
  Code/DistGeom/TriangleSmooth.cpp
  Code/Numerics/Matrix.h
Labels: enhancement, optimization

#8173 improve handling of esters, amides, etc. in the v2 tautomer hash
  Code/GraphMol/MolHash/CMakeLists.txt
  Code/GraphMol/MolHash/catch_tests.cpp
  Code/GraphMol/MolHash/hashfunctions.cpp
Labels: bug, changes results

#8037 remove no-op macros and dead code (pt 4)
  Code/DataStructs/DiscreteValueVect.cpp
  Code/Demos/RDKit/Basement/TemplEnum/main.cpp
  Code/Demos/RDKit/Basement/xpcom/IRDKit.h
  Code/Demos/sqlite/rdk_funcs.cpp
  Code/ForceField/ForceField.cpp
  Code/ForceField/MMFF/TorsionAngle.cpp
  Code/ForceField/UFF/TorsionAngle.cpp
  Code/ForceField/UFF/testUFFForceField.cpp
  Code/Geometry/point.h
  Code/GraphMol/Aromaticity.cpp
  Code/GraphMol/ChemReactions/Reaction.cpp
  Code/GraphMol/ChemReactions/catch_tests.cpp
  Code/GraphMol/Descriptors/DCLV.cpp
  Code/GraphMol/Descriptors/catch_tests.cpp
  Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
  Code/GraphMol/FileParsers/MolSupplier.v1API.h
  Code/GraphMol/FileParsers/SequenceWriters.cpp
  Code/GraphMol/FileParsers/testMol2ToMol.cpp
  Code/GraphMol/FindRings.cpp
  Code/GraphMol/Fingerprints/test1.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/Builder.cpp
  Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp
  Code/GraphMol/FragCatalog/FragFPGenerator.cpp
  Code/GraphMol/Kekulize.cpp
  Code/GraphMol/MolChemicalFeatures/Wrap/ChemicalFeatureUtils.cpp
  Code/GraphMol/MolDraw2D/Qt/DrawTextQt.h
  Code/GraphMol/MolInterchange/test1.cpp
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/SLNParse/test.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.cpp
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/SmilesParse/test.cpp
  Code/GraphMol/Substruct/SubstructMatch.cpp
  Code/GraphMol/WedgeBonds.cpp
  Code/GraphMol/Wrap/MultithreadedSDMolSupplier.cpp
  Code/GraphMol/bulktest.cpp
  Code/Numerics/Optimizer/BFGSOpt.h
  Code/RDBoost/Wrap/RDBase.cpp
  Code/RDBoost/list_indexing_suite.hpp
  Code/SimDivPickers/pickersCLI.cpp
Labels: Cleanup

#8197 support Ctrl-C in conformer generation
  Code/GraphMol/DistGeomHelpers/Embedder.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
Labels: enhancement

#8212 Add option to omit brackets when drawing query atoms.
  Code/GraphMol/MolDraw2D/DrawMol.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: enhancement

#8116 Vulnerability fixes
  Code/GraphMol/FileParsers/MolSGroupParsing.cpp
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
Labels: bug

#8220 Fix typo in documentation
  Code/ForceField/UFF/AngleBend.h
Labels: documentation

#8175 Condense MMFF Contribs into single contrib per type.
  Code/DistGeom/DistGeomUtils.cpp
  Code/ForceField/MMFF/AngleBend.cpp
  Code/ForceField/MMFF/AngleBend.h
  Code/ForceField/MMFF/BondStretch.cpp
  Code/ForceField/MMFF/BondStretch.h
  Code/ForceField/MMFF/Nonbonded.cpp
  Code/ForceField/MMFF/Nonbonded.h
  Code/ForceField/MMFF/OopBend.cpp
  Code/ForceField/MMFF/OopBend.h
  Code/ForceField/MMFF/StretchBend.cpp
  Code/ForceField/MMFF/StretchBend.h
  Code/ForceField/MMFF/TorsionAngle.cpp
  Code/ForceField/MMFF/TorsionAngle.h
  Code/GraphMol/ForceFieldHelpers/MMFF/Builder.cpp
  Code/GraphMol/ForceFieldHelpers/MMFF/testMMFFHelpers.cpp
  Code/GraphMol/ForceFieldHelpers/catch_tests.cpp
Labels: enhancement, optimization, API-change

#8208 DistViolationContribs optimization
  Code/DistGeom/DistViolationContribs.cpp
  Code/DistGeom/DistViolationContribs.h
Labels: optimization

#8223 Optimisation of fingerprint Synthon Search
  Code/GraphMol/SynthonSpaceSearch/SynthonSpace.h
  Code/GraphMol/SynthonSpaceSearch/SynthonSpaceFingerprintSearcher.cpp
  Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearch_details.cpp
  Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearch_details.h
  Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearcher.cpp
  Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSubstructureSearcher.cpp
Labels: optimization

#8216 Option to put padding round elements of reaction.
  Code/GraphMol/MolDraw2D/DrawMol.h
  Code/GraphMol/MolDraw2D/MolDraw2D.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h
  Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
  Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/catch_tests.cpp
Labels: enhancement
