Repository rdkit/rdkit, pull requests merged in 2025-06, with the labels that each got.

#8563 Cpp enumerate stereoisomers
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/EnumerateStereoisomers/CMakeLists.txt
  Code/GraphMol/EnumerateStereoisomers/EnumerateStereoisomers.cpp
  Code/GraphMol/EnumerateStereoisomers/EnumerateStereoisomers.h
  Code/GraphMol/EnumerateStereoisomers/Flippers.cpp
  Code/GraphMol/EnumerateStereoisomers/Flippers.h
  Code/GraphMol/EnumerateStereoisomers/Wrap/CMakeLists.txt
  Code/GraphMol/EnumerateStereoisomers/Wrap/rdEnumerateStereoisomers.cpp
  Code/GraphMol/EnumerateStereoisomers/Wrap/testEnumerateStereoisomers.py
  Code/GraphMol/EnumerateStereoisomers/catch_tests.cpp
Labels: enhancement

#8571 update to win-2022 for CI
  .azure-pipelines/vs_build.yml
  .azure-pipelines/vs_build_dll.yml
  .azure-pipelines/vs_build_swig.yml
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#8567 Some cleanup of the xyz2mol code
  Code/GraphMol/DetermineBonds/DetermineBonds.cpp
Labels: Cleanup

#8580 Bump maeparser to 1.3.3 (fixes #8525)
  External/CoordGen/CMakeLists.txt
Labels: enhancement

#8582 CIP labeler: attempt to resolve "easy" stereo centers first
  Code/GraphMol/CIPLabeler/CIPLabeler.cpp
  Code/GraphMol/CIPLabeler/catch_tests.cpp
Labels: enhancement

#8601 Fixed out of bounds vector access in GetGeodesicMatrix
  Code/GraphMol/Descriptors/GETAWAY.cpp
Labels: bug

#8589 Make assignCIPLabels Ctrl+c interruptable
  Code/GraphMol/CIPLabeler/CIPLabeler.cpp
  Code/GraphMol/CIPLabeler/Wrap/rdCIPLabeler.cpp
  Code/GraphMol/CIPLabeler/catch_tests.cpp
  Code/GraphMol/CIPLabeler/rules/SequenceRule.cpp
  Code/RDGeneral/ControlCHandler.h
Labels: enhancement
