Repository rdkit/rdkit, pull requests merged in 2025-04, with the labels that each got.

#8399 add correct export to SynthonSpace.h
  Code/GraphMol/SynthonSpaceSearch/SynthonSpace.h
Labels: bug

#8404 Bump MaeParser version to 1.3.2
  External/CoordGen/CMakeLists.txt
Labels: enhancement

#8402 prep for next release cycle
  CMakeLists.txt
  Docs/Book/conf.py
  ReleaseNotes.md
Labels: infrastructure, not in release notes

#8372 Speed up GetProp Python keyerrors
  Code/GraphMol/Wrap/Atom.cpp
  Code/GraphMol/Wrap/Bond.cpp
  Code/GraphMol/Wrap/Conformer.cpp
  Code/GraphMol/Wrap/Mol.cpp
  Code/GraphMol/Wrap/SubstanceGroup.cpp
  Code/GraphMol/Wrap/props.hpp
Labels: enhancement, optimization

#8415 Avoid a segfault in CoordGen when a double bond has stereo spec but no stereo atoms
  Code/GraphMol/Depictor/catch_tests.cpp
  External/CoordGen/CoordGen.h
Labels: bug

#8419 bump gcc version in CI
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#8039 switch to C++20
  .azure-pipelines/linux_build.yml
  .azure-pipelines/linux_build_cartridge.yml
  CMakeLists.txt
  Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp
  Code/GraphMol/FMCS/CMakeLists.txt
  Code/GraphMol/FMCS/Seed.h
  Code/GraphMol/FMCS/TargetMatch.cpp
  Code/GraphMol/FMCS/TargetMatch.h
  Code/GraphMol/FileParsers/CDXMLParser.cpp
  Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h
  Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogUtils.h
  Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
  External/YAeHMOP/EHTTools.cpp
  azure-pipelines.yml
  rdkit/Chem/nbtests/github4823.ipynb
Labels: enhancement

#8410 Enable the chiral flag on enumerated isomers
  rdkit/Chem/EnumerateStereoisomers.py
  rdkit/Chem/UnitTestMol3D.py
Labels: enhancement

#8434 Support pickling Shape inputs
  .azure-pipelines/mac_build.yml
  .azure-pipelines/mac_build_java.yml
  External/pubchem_shape/PubChemShape.hpp
  External/pubchem_shape/test.cpp
Labels: enhancement

#8439 bump versions of SDK in MacOS CI jobs
  .azure-pipelines/mac_build.yml
  .azure-pipelines/mac_build_java.yml
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#8409 Moving towards getting all tests to pass when using the new stereo code
  Code/GraphMol/CIPLabeler/CIPLabeler.cpp
  Code/GraphMol/CIPLabeler/Wrap/pyCIPLabelWrapTest.py
  Code/GraphMol/CIPLabeler/catch_tests.cpp
  Code/GraphMol/CMakeLists.txt
  Code/GraphMol/ChemReactions/testReaction.cpp
  Code/GraphMol/ChemTransforms/MolFragmenter.cpp
  Code/GraphMol/ChemTransforms/catch_tests.cpp
  Code/GraphMol/Depictor/DepictUtils.cpp
  Code/GraphMol/Depictor/EmbeddedFrag.cpp
  Code/GraphMol/Depictor/Wrap/testDepictor.py
  Code/GraphMol/Depictor/catch_tests.cpp
  Code/GraphMol/Depictor/testDepictor.cpp
  Code/GraphMol/DistGeomHelpers/catch_tests.cpp
  Code/GraphMol/FileParsers/CMakeLists.txt
  Code/GraphMol/FileParsers/file_parsers_catch.cpp
  Code/GraphMol/FileParsers/test1.cpp
  Code/GraphMol/FileParsers/testMol2ToMol.cpp
  Code/GraphMol/FileParsers/testMolSupplier.cpp
  Code/GraphMol/FileParsers/testMolWriter.cpp
  Code/GraphMol/FindStereo.cpp
  Code/GraphMol/Fingerprints/CMakeLists.txt
  Code/GraphMol/Fingerprints/FingerprintUtil.cpp
  Code/GraphMol/Fingerprints/MorganGenerator.cpp
  Code/GraphMol/Fingerprints/test1.cpp
  Code/GraphMol/MarvinParse/test_data/DoubleBondChain.expected.sdf
  Code/GraphMol/MarvinParse/test_data/Na_Mg_Al_OH.expected.sdf
  Code/GraphMol/MolDraw2D/catch_tests.cpp
  Code/GraphMol/MolDraw2D/test1.cpp
  Code/GraphMol/MolInterchange/test1.cpp
  Code/GraphMol/MolStandardize/CMakeLists.txt
  Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
  Code/GraphMol/MolStandardize/testPipeline.cpp
  Code/GraphMol/MolStandardize/testTautomer.cpp
  Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
  Code/GraphMol/RWMol.cpp
  Code/GraphMol/SmilesParse/CMakeLists.txt
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/SmilesParse/test.cpp
  Code/GraphMol/Substruct/test1.cpp
  Code/GraphMol/Wrap/rough_test.py
  Code/GraphMol/catch_adjustquery.cpp
  Code/GraphMol/catch_canon.cpp
  Code/GraphMol/catch_chirality.cpp
  Code/GraphMol/molopstest.cpp
  Code/GraphMol/new_canon.h
  Code/GraphMol/test1.cpp
  Code/GraphMol/testChirality.cpp
  Code/RDGeneral/Invariant.h
  Code/RDGeneral/types.cpp
  Code/RDGeneral/types.h
  ReleaseNotes.md
  rdkit/Chem/Pharm3D/EmbedLib.py
  rdkit/Chem/__init__.py
Labels: enhancement, changes results

#8445 switch to target_platform=14
  azure-pipelines.yml
Labels: infrastructure, not in release notes

#8451 add StereoGroup.getBonds() to Python wrapper
  Code/GraphMol/Wrap/StereoGroup.cpp
  Code/GraphMol/Wrap/rough_test.py
Labels: enhancement

#8448 add function to overwrite __setattr__ to only accept valid arguments
  Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
  Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
  Code/RDBoost/Wrap.cpp
  Code/RDBoost/Wrap.h
Labels: enhancement

#8453 Protect Python DrawOptions from bad attributes.
  Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
  Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
Labels: enhancement

#8454 Add a custom CXSMILES feature to indicate Zero Order Bonds
  Code/GraphMol/SmilesParse/CXSmilesOps.cpp
  Code/GraphMol/SmilesParse/SmilesWrite.h
  Code/GraphMol/SmilesParse/catch_tests.cpp
  Code/GraphMol/Wrap/rdmolfiles.cpp
  Docs/Book/RDKit_Book.rst
Labels: enhancement

#8452 add quick H-H bond removal to connectTheDots
  Code/GraphMol/DetermineBonds/DetermineBonds.cpp
  Code/GraphMol/DetermineBonds/catch_tests.cpp
  Code/GraphMol/FileParsers/ProximityBonds.cpp
  Code/GraphMol/FileParsers/ProximityBonds.h
  Code/GraphMol/FileParsers/connectTheDots_catch.cpp
Labels: enhancement

#8412 Consolidate MinimalLib Dockerfiles to avoid code duplication
  Code/MinimalLib/README.md
  Code/MinimalLib/docker/Dockerfile
  Code/MinimalLib/docker/Dockerfile_1_deps
  Code/MinimalLib/docker/Dockerfile_2_rdkit_clone_from_github
  Code/MinimalLib/docker/Dockerfile_2_rdkit_copy_from_local
  Code/MinimalLib/docker/Dockerfile_3_rdkit_build
  Code/MinimalLib/docker/Dockerfile_4_rdkit_export
  Code/MinimalLib/docker/Dockerfile_legacy_browsers
  Code/MinimalLib/docker/certs/.gitignore
  Code/MinimalLib/docker/docker_compose_build_minimallib.yml
  Code/MinimalLib/scripts/build_rdkitjs.sh
  azure-pipelines.yml
Labels: Cleanup

#8470 Clarify Docstring of molzip when called with a Single mol object
  Code/GraphMol/Wrap/MolOps.cpp
Labels: documentation

#8482 A couple optimizations to when the ring finding code is called
  Code/GraphMol/MolOps.cpp
  Code/GraphMol/WedgeBonds.cpp
Labels: enhancement, optimization

#8293 Add documentation for SynthonSpaceSearch.
  Docs/Book/GettingStartedInPython.rst
Labels: documentation
